### ISSUE TITLE
panic on Windows: The requested operation cannot be performed on a file with a user-mapped section open

### ISSUE THREAD

**Issue by wildan2711** [dgraph-io/dgraph#4140] opened 2019-10-08 13:18 UTC
### What version of Dgraph are you using?

v1.1

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, OS)?

RAM: 8GB
OS: Windows 10

### Steps to reproduce the issue (command/config used to run Dgraph).

Run `dgraph zero` on Windows 10.

### Expected behaviour and actual result.

Dgraph zero runs successfully, instead throws panic:

```
2019/10/08 20:15:04 truncate zw\000000.vlog: The requested operation cannot be performed on a file with a user-mapped section open.
During db.vlog.open
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.Wrapf
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/error.go:82
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:323
github.com/dgraph-io/dgraph/dgraph/cmd/zero.run
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:208
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init.0.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:73
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68
main.main
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
Error while opening WAL store
github.com/dgraph-io/dgraph/x.Checkf
        /tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:49
github.com/dgraph-io/dgraph/dgraph/cmd/zero.run
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:209
github.com/dgraph-io/dgraph/dgraph/cmd/zero.init.0.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/zero/run.go:73
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68
main.main
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

**Comment by wildan2711** [comment] 2019-10-08 13:30
Rerunning Dgraph zero on the same folder as the above, seems to fix the issue (Dgraph zero runs successfully.

But running Dgraph alpha returns a similar error:
```
2019/10/08 20:20:14 truncate p\000000.vlog: The requested operation cannot be performed on a file with a user-mapped section open.
During db.vlog.open
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.Wrapf
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/error.go:82
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:323
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.OpenManaged
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:26
github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage
        /tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:187
github.com/dgraph-io/dgraph/edgraph.InitServerState
        /tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:97
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:504
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.2.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:87
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68
main.main
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
Error while creating badger KV posting store
github.com/dgraph-io/dgraph/x.Checkf
        /tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:49
github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage
        /tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:188
github.com/dgraph-io/dgraph/edgraph.InitServerState
        /tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:97
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.2.func1
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:87
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
github.com/dgraph-io/dgraph/dgraph/cmd.Execute
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:68
main.main
        /tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
```

Rerunning `dgraph alpha` atleast 2 more times, fixes it. But all alter/query fails:

First attempt:
```
E1008 20:22:22.653040    6992 draft.go:456] Applying proposal. Error: truncate p\000000.vlog: The requested 
operation cannot be performed on a file with a user-mapped section open.. Proposal: "mutations:<group_id:1 start_ts:2 drop_op:ALL > key:\"01-13836896152505404349\" index:7 ".
```
Second attempt:
```
E1008 20:27:54.807594    6992 draft.go:456] Applying proposal. Error: Create value log file. Path=p\000000.vlog. Error=open p\000000.vlog: The file exists.. Proposal: "mutations:<group_id:1 start_ts:6 drop_op:ALL > key:\"01-13236944105340551348\" index:15 ".
```

All subsequent attempts, return atleast `The file exists..`

**Comment by MichelDiz** [comment] 2019-10-08 16:20
Duplicate of #3800

please, when you have a panic or issue, search for keywords related to it. e.g: "windows", "Windows panic", "The requested operation cannot be performed" e.g. https://github.com/dgraph-io/dgraph/issues?q=is%3Aissue+%22The+requested+operation+cannot+be+performed%22+is%3Aclosed before opening an issue.

You can find faster solutions by searching for it.

Cheers.

**Closed by MichelDiz** 2019-10-08 16:20 UTC
