### ISSUE TITLE
When running dgraph 1.0 with the tour 1million.rdf.gz data, allofterms, anyofterms, regexp don't work properly

### ISSUE THREAD

**Issue by sgon00** [dgraph-io/dgraph#1935] opened 2017-12-19 09:28 UTC
```
Dgraph version   : v1.0.0
Commit SHA-1     : 7a64f54b
Commit timestamp : 2017-12-18 15:04:40 +0530
Branch           : HEAD
```

dgraph linux binary: `dgraph-linux-amd64-v1.0.0.tar.gz`

OS: Manjaro (Based on Arch Linux. I consider it's the same as arch linux)

I completed the tour in my spare time and went to do something else. Today, I see there is version 1.0. I am very happy to upgrade and try it. After the upgrade, I ran it with the old tour database and ran a query. Basically, it's https://tour.dgraph.io/search/2/. It just queries `Peter Jackson`. 

```
{
  peters(func: allofterms(name@en, "Peter Jackson")) {
    name@en
  }
}
```

But the result is `Your query did not return any results`. no result.

```
{
  "data": {
    "peters": []
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 44133,
      "processing_ns": 1504664,
      "encoding_ns": 730066
    },
    "txn": {
      "start_ts": 30002,
      "lin_read": {
        "ids": {
          "1": 182
        }
      }
    }
  }
}
```

I thought the old database didn't work with the version 1.0. So I removed the complete database and start everything clean from scratch. That means I create empty db and live load 1 million data again with the version 1.0 and after that, I re-ran the query, the result is the same. no result. Then I tried some other queries. they can return the results fine. So, what's wrong with `Peter Jackson`. It's just gone in version 1.0...

Btw, I ran the following query too, and no result:

```
{
  aliens(func: regexp(name@en, /.*alien.*/i)) @cascade {
    name@en
    ~genre {
      name@en
      starring {
        performance.actor @filter(regexp(name@en,
          /(.*ali.*e.*n.*)|(.*a.*lie.*n.*)|(.*a.*l.*ien.*)/i)) {
          name@en
        }
      }
    }
  }
}
```

It returns:

```
{
  "data": {
    "aliens": []
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 116327,
      "processing_ns": 200264070,
      "encoding_ns": 649608
    },
    "txn": {
      "start_ts": 30003,
      "lin_read": {
        "ids": {
          "1": 182
        }
      }
    }
  }
}
```

To prove my database does have something, the following query:

```
{
  peters(func: anyofterms(name@en, "Peter Jackson")) {
    name@en
  }
}
```

returns the result:

```
{
  "data": {
    "peters": [
      {
        "name@en": "John M. Jackson"
      },
      {
        "name@en": "Peter Maher"
      },
      {
        "name@en": "Peter Fitzgerald"
      },
      {
        "name@en": "Peter James Haworth"
      },
      {
        "name@en": "Peter"
      },
      {
        "name@en": "Peter Thompson"
      },
...
...
...
...
```

Thanks a lot for your help.

**Comment by sgon00** [comment] 2017-12-19 13:37
Some Updates (I did some more tests on this issue.):

### If I don't apply the schema mutation at tour.dgraph.io/search/1/

```
name: string @index(term, exact, fulltext, trigram) .
```

Actual steps:

1. Fresh install dgraph 0.9.4 linux binary
2. Create the schema by following https://tour.dgraph.io/moredata/1/
3. Load the dataset with `dgraph live -r 1million.rdf.gz --zero localhost:5080`
4. Shutdown dgraph server and zero properly.
5. Upgrade to dgraph 1.0.0
6. Run the query at https://tour.dgraph.io/search/2/ `peters(func: allofterms(name@en, "Peter Jackson")) { name@en  }`. It can return `Peter Jackson` successfully.

### If I follow the tour and apply the schema mutation at tour.dgraph.io/search/1/

Actual steps:

1. Fresh install dgraph 0.9.4 linux binary
2. Create the schema by following https://tour.dgraph.io/moredata/1/
3. Load the dataset with `dgraph live -r 1million.rdf.gz --zero localhost:5080`
4. Apply the schema mutation at tour.dgraph.io/search/1/ `name: string @index(term, exact, fulltext, trigram) .`
5. Shutdown dgraph server and zero properly.
6. Upgrade to dgraph 1.0.0
7. Run the `allofterms` query at https://tour.dgraph.io/search/2/ `peters(func: allofterms(name@en, "Peter Jackson")) { name@en  }`. The `Peter Jackson` can not be returned. **This is unexpected.**
8. Run the `anyofterms` query `peters(func: anyofterms(name@en, "Peter Jackson")) { name@en  }`. The `Peter Jackson` can not be returned. **This is unexpected.**
9. Run the `eq` query `peters(func: eq(name@en, "Peter Jackson")) { uid name@en }`, **The `Peter Jackson` can be returned in the `eq` query**. That means `Peter Jackson` is in the database, the actual output:

```
  "data": {
    "peters": [
      {
        "uid": "0x75304",
        "name@en": "Peter Jackson"
      }
    ]
  }
```

**Comment by peterstace** [comment] 2017-12-20 01:25
Thank you for reporting the issue with such a high level of detail.

I could reproduce the problem on the first try, I'll continue to investigate what the problem is and then make a fix.

**Comment by peterstace** [comment] 2017-12-20 01:36
I've also reproduced this using only v1.0, so this doesn't have anything to do with the upgrade.

**Comment by peterstace** [comment] 2017-12-20 03:33
Fixed in master by @janardhan1993 's change, closing.

**Closed by peterstace** 2017-12-20 03:33 UTC
Labels: bug
