### ISSUE TITLE
Error while joining cluster. No node has been set up yet.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#5038] opened 2020-03-25 23:33 UTC
### What version of Dgraph are you using?
v20.03.0-beta.20200320

### Have you tried reproducing the issue with the latest release?
I have not tried with the latest release (currently, v1.2.2).

### What is the hardware spec (RAM, OS)?
Ubuntu Linux. Docker.

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run 6-node Dgraph cluster. I used the compose tool:

```
$ cd ./compose
$ ./run.sh -a 3 -z 3 --local=false --tag=v20.03.0-beta.20200320 --port_offset=0
```
2. The cluster does not converge. In Zero logs, I see this:

```
W0325 23:25:36.891973      17 raft.go:572] Zero node: 0x1 unable to reach quorum. Error: context deadline exceeded
W0325 23:25:37.604362      17 node.go:671] [0x1] Read index context timed out
I0325 23:25:37.604557      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:25:37.604686      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:25:37.604875      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:25:37.604997      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:25:37.605213      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:25:37.605442      17 zero.go:417] Got connection request: id:2 addr:"alpha2:7082"
I0325 23:25:37.605797      17 pool.go:160] CONNECTING to alpha2:7082
W0325 23:25:37.607603      17 pool.go:254] Connection lost with alpha2:7082. Error: rpc error: code = Unknown desc = No node has been set up yet
I0325 23:25:37.614059      17 zero.go:562] Connected: id:2 group_id:1 addr:"alpha2:7082"
I0325 23:25:37.614183      17 zero.go:417] Got connection request: id:3 addr:"alpha3:7083"
I0325 23:25:37.614364      17 pool.go:160] CONNECTING to alpha3:7083
W0325 23:25:37.615889      17 pool.go:254] Connection lost with alpha3:7083. Error: rpc error: code = Unknown desc = No node has been set up yet
I0325 23:25:37.620909      17 zero.go:562] Connected: id:3 group_id:1 addr:"alpha3:7083"
I0325 23:25:37.621036      17 zero.go:417] Got connection request: id:1 addr:"alpha1:7080"
I0325 23:25:37.621298      17 pool.go:160] CONNECTING to alpha1:7080
W0325 23:25:37.622860      17 pool.go:254] Connection lost with alpha1:7080. Error: rpc error: code = Unknown desc = No node has been set up yet
I0325 23:25:37.632678      17 zero.go:562] Connected: id:1 group_id:1 addr:"alpha1:7080"
```

And then it continues to output this in the logs repeatedly:
```
I0325 23:29:53.761151      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:29:53.762873      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:29:54.764671      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:29:54.765937      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:29:55.767221      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:29:55.768950      17 zero.go:435] Connected: cluster_info_only:true
I0325 23:29:56.770856      17 zero.go:417] Got connection request: cluster_info_only:true
I0325 23:29:56.772370      17 zero.go:435] Connected: cluster_info_only:true
```

In Alpha, these logs output repeatedly:

```
I0325 23:25:47.412196      16 draft.go:1467] Calling IsPeer
E0325 23:25:47.413043      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:48.413188      16 draft.go:1467] Calling IsPeer
E0325 23:25:48.414397      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:49.414579      16 draft.go:1467] Calling IsPeer
E0325 23:25:49.415526      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:50.415814      16 draft.go:1467] Calling IsPeer
E0325 23:25:50.416740      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:51.416922      16 draft.go:1467] Calling IsPeer
E0325 23:25:51.418140      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:52.307142      16 query.go:123] Dgraph query execution failed : Dgraph query failed because Please retry again, server is not ready to accept requests
I0325 23:25:52.307199      16 admin.go:510] Error reading GraphQL schema: Dgraph query failed because Dgraph query failed because Please retry again, server is not ready to accept requests.
I0325 23:25:52.418384      16 draft.go:1467] Calling IsPeer
E0325 23:25:52.419375      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:53.419513      16 draft.go:1467] Calling IsPeer
E0325 23:25:53.420343      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:54.420632      16 draft.go:1467] Calling IsPeer
E0325 23:25:54.421497      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:55.421824      16 draft.go:1467] Calling IsPeer
E0325 23:25:55.422729      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:56.423023      16 draft.go:1467] Calling IsPeer
E0325 23:25:56.423961      16 draft.go:1500] Error while calling hasPeer: error while joining cluster: rpc error: code = Unknown desc = No node has been set up yet. Retrying...
I0325 23:25:57.307742      16 query.go:123] Dgraph query execution failed : Dgraph query failed because Please retry again, server is not ready to accept requests
```
### Expected behaviour and actual result.

The cluster should be up and running as healthy when starting Dgraph for the first time.

**Comment by martinmr** [comment] 2020-03-25 23:54
I can't reproduce this on my machine. Everything works as expected.

**Comment by martinmr** [comment] 2020-03-26 21:34
Tried to reproduce this multiple times but I never see the repeated outputs. I see the messages saying the connection to the alphas is lost but the cluster recovers without manual intervention.

**Comment by martinmr** [comment] 2020-03-30 19:45
Closing because this could not be reproduced.

**Closed by martinmr** 2020-03-30 19:45 UTC
Labels: kind/bug, priority/P0, status/accepted

**Comment by danielmai** [comment] 2020-03-30 20:06
I ran embargo 32 times and the blockade test passed.
