### ISSUE TITLE
slash graphql introspection query fails with apollo client

### ISSUE THREAD

**Issue by martaver** [dgraph-io/dgraph#5792] opened 2020-07-01 19:58 UTC
I'm testing Slash GraphQL, and I'm using Apollo Client to send an introspection query to my /graphql instance.

Getting the introspection JSON is important because it allows us to codegen in the front-end.

However, when I run the introspection query with the /graphql instance, I get the following error:

```
GraphQL error: invalid character 'm' after object key:value pair\n" +
    "GraphQL error: Non-nullable field '__schema' (type __Schema!) was not present in result from Dgraph.  GraphQL error propagation triggered.
```

This same introspection query works fine with other graphql servers. I thought it likely that this is an incompatibility on dgraph's behalf.

I've set up a reproduction here: https://github.com/cleric-sh/repro/tree/dgraph-introspection

Just clone that repo, switch to the dgraph-introspection branch and do yarn && yarn update.

**Comment by gja** [comment] 2020-07-02 05:02
Hi @Martaver. Thanks for the bug. I think I was able to boil this down to a much simpler example. I've marked this as accepted, and we'll be looking at a fix for this.

```shell
 curl -vH "Content-Type: application/json" -d '{"operationName":"IntrospectionQuery","variables":{},"query":"query IntrospectionQuery {\n  __schema {\n    queryType {\n      name\n      __typename\n    }\n    mutationType {\n      name\n      __typename\n    }\n    subscriptionType {\n      name\n      __typename\n    }\n    types {\n      ...FullType\n      __typename\n    }\n    directives {\n      name\n      description\n      locations\n      args {\n        ...InputValue\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment FullType on __Type {\n  kind\n  name\n  description\n  fields(includeDeprecated: true) {\n    name\n    description\n    args {\n      ...InputValue\n      __typename\n    }\n    type {\n      ...TypeRef\n      __typename\n    }\n    isDeprecated\n    deprecationReason\n    __typename\n  }\n  inputFields {\n    ...InputValue\n    __typename\n  }\n  interfaces {\n    ...TypeRef\n    __typename\n  }\n  enumValues(includeDeprecated: true) {\n    name\n    description\n    isDeprecated\n    deprecationReason\n    __typename\n  }\n  possibleTypes {\n    ...TypeRef\n    __typename\n  }\n  __typename\n}\n\nfragment InputValue on __InputValue {\n  name\n  description\n  type {\n    ...TypeRef\n    __typename\n  }\n  defaultValue\n  __typename\n}\n\nfragment TypeRef on __Type {\n  kind\n  name\n  ofType {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                __typename\n              }\n              __typename\n            }\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n"}' https://smiling-jeans-9473.us-east-1.aws.thegaas.com/graphql
```

**Comment by Martaver** [comment] 2020-07-02 05:07
Btw, if I paste the introspection query into the API Explorer on the web UI, I get the introspection JSON displayed correctly.

**Comment by Martaver** [comment] 2020-07-02 05:21
Okay, I was able to get the introspection working using a simpler axios request. Still scratching my head about what's special about the apollo client query... formatting maybe?

**Comment by pawanrawal** [comment] 2020-07-02 12:47
I was able to reproduce this on Dgraph. It likely happens because `__typename` is not handled properly within the introspection code. The schema introspection query returns the correct result after `__typename`  is removed. This should be easy to fix though, working on a fix.

**Closed** 2020-07-08 10:13 UTC
Labels: area/graphql, status/accepted
