### ISSUE TITLE
Bug in query variables whe used with @cascade

### ISSUE THREAD

**Issue by vikram-ma** [dgraph-io/dgraph#4690] opened 2020-01-28 13:01 UTC
I have a schema, where, 
- one person can own multiple accounts (account1, account2)
- each account is is subscribed exactly one service (account1 -> service1, account2 -> service2)

For a user id say “1”, I want to get his “owns” predicate, which has subscribed to “service1”
Below query with @cascade works fine, and I get exactly one uid

```
{
  my_activities(func: eq(Id, 1)) @cascade {
    owns {
      uid
      subscribedTo @filter(eq(name, "service1"))
    }
  }
}
```

But when I use the same query in upsert, behavior is little bit strange. Even with cascade, I see multiple uid being returned
```
upsert{
  query{
    my_activities(func: eq(Id, 1)) @cascade {
      owns {
        subscribedTo @filter(eq(name, "Service1"))
	instance as uid
      }
  }
  mutation @if(eq(len(instance), 2) ) {
    # this block executes!!!
  }
  mutation @if(eq(len(instance), 1) ) {
     # this block DOESNOT execute. I was expecting this block to be executed.
  }
}
```

Note: See the discussion here https://discuss.dgraph.io/t/bug-in-cascade-directive/5896

**Comment by sleto-it** [comment] 2020-01-28 15:47
Hi @vikram-ma,

Many thanks for opening this issue. We are on it and will share an update or ask more questions as soon as possible

Thanks,

**Comment by mangalaman93** [comment] 2020-01-28 21:04
I am able to reproduce this issue as follows:

schema:
```
<Id>: int @index(int) .
<name>: string .
<owns>: [uid] .
<subscribedTo>: [uid] .
```

data:
```
{
  set {
    _:user <Id> "1" .
    _:user <owns> _:entity1 .
    _:entity1 <subscribedTo> _:service1 .
    _:service1 <name> "service1" .

    _:user <owns> _:entity2 .
    _:entity <subscribedTo> _:service2 .
    _:service2 <name> "service2" .
  }
}
```

query:
```
{
  my_activities(func: eq(Id, 1)) @cascade {
    owns {
      uid
      subscribedTo @filter(eq(name, "service1"))
    }
  }
}
```

upsert:
```
upsert{
  query{
    my_activities(func: eq(Id, 1)) @cascade {
      owns {
        subscribedTo @filter(eq(name, "Service1"))
        instance as uid
      }
    }
  }

  mutation @if(eq(len(instance), 2)) {
    set {
      _:data <wrong> "3" .
    }
  }

  mutation @if(eq(len(instance), 1)) {
    set {
      _:a <right> "3" .
    }
  }
}
```

Response that we get for final upsert:
```
{
  "data": {
    "code": "Success",
    "message": "Done",
    "queries": {
      "my_activities": []
    },
    "uids": {
      "data": "0x7"
    }
  },
  "extensions": {...},
    "txn": {
      "start_ts": 12,
      "commit_ts": 13,
      "preds": [
        "1-wrong"
      ]
    }
  }
}
```

There are two problems with this response:
1. `"my_activities": []` query response is empty.
2. Incorrect mutation was executed.

**Comment by mangalaman93** [comment] 2020-02-13 13:09
This is actually problem with our query processing logic, following query returns:

```Graphql
{
  var(func: eq(Id, 1)) @cascade {
    owns {
      instance as uid
      subscribedTo @filter(eq(name, "service1"))
    }
  }
    
  
  q(func: uid(instance)){
    uid
  }
}
```

following response:
```
{
  "data": {
    "q": [
      {
        "uid": "0x2"
      },
      {
        "uid": "0x4"
      }
    ]
  }
}
```

**Comment by mangalaman93** [comment] 2020-02-13 13:20
And, this is a duplicate of https://github.com/dgraph-io/dgraph/issues/4024.

**Closed by mangalaman93** 2020-02-13 13:20 UTC
Labels: area/querylang/cascade, kind/bug, status/accepted
