### ISSUE TITLE
Feature Request: Efficient Count Indexing

### ISSUE THREAD

**Issue by b-l-a-c-k-b-e-a-r-d** [dgraph-io/dgraph#3193] opened 2019-03-22 14:11 UTC
### What you wanted to do

Efficiently create graphs with count indexes (they do not necessarily need to be exact counts, approximations with some bounded error would be sufficient).  

### What you actually did

I have seen RDFs / second (for live indexing) go from 26,000/second to 200/second just by adding count indexes.  Two orders of magnitude reduction is a considerable hit.  

### Why that wasn't great, with examples

Count indexes are known to be slow (https://github.com/dgraph-io/dgraph/issues/2385#issuecomment-389022207). 

It might be helpful to other dgraph users if the documentation is updated so they know there is a significant performance penalty for using count indexes.

**Comment by MichelDiz** [comment] 2019-03-22 16:38
You're probably using BulkLoad. I would recommend you add @count or @reverse only when you start the Alphas for now.

**Comment by manishrjain** [comment] 2019-03-22 16:39
Yeah, we need a way to speed up the count index. They are *very* expensive as they stand.

**Comment by mangalaman93** [comment] 2019-03-22 16:42
This is on my to-do list. Let me bump it up and get some ideas out by next week.

**Comment by srfrog** [comment] 2019-03-22 18:42
Yes this is related to another feature to implement HyperLogLog++

Related: #3054

**Comment by campoy** [comment] 2019-09-13 15:38
I'm closing this as a duplicate of the older issue #3054.

**Closed by campoy** 2019-09-13 15:38 UTC
Labels: area/performance, priority/P1
