### ISSUE TITLE
Dgraph crashing when using orderdesc on a facet?

### ISSUE THREAD

**Issue by lazharichir** [dgraph-io/dgraph#1640] opened 2017-10-15 18:29 UTC
I loaded a bit of data and then generated some predicates linking two nodes, with two facets each time (weight, and updated.) When I query the data, it works fine. When I query the data using `orderdesc` or `orderasc`, dgraph crashes. It does crash whether I keep the (first: 5) or not.

Using the same query but on the datetime facet `updated` does work just fine. Seems like it's an issue with the `weight` facet (perhaps the float format?!)

This is the error in my terminal.
```
panic: interface conversion: interface {} is int64, not float64

goroutine 716390 [running]:
github.com/dgraph-io/dgraph/types.byValue.Less(0xc4201d5000, 0x1d0, 0x1d0, 0xc450a6f16c, 0x1, 0x1, 0xc4404e4040, 0xc45feb2000, 0x1d0, 0x200, ...)
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/types/sort.go:68 +0x53f
github.com/dgraph-io/dgraph/types.(*byValue).Less(0xc459191130, 0xe8, 0xae, 0xc446fe8001)
	<autogenerated>:14 +0x76
sort.medianOfThree(0x4e58ee0, 0xc459191130, 0xe8, 0xae, 0x122)
	/usr/local/go/src/sort/sort.go:78 +0x49
sort.doPivot(0x4e58ee0, 0xc459191130, 0x0, 0x1d0, 0x1, 0x1)
	/usr/local/go/src/sort/sort.go:104 +0x655
sort.quickSort(0x4e58ee0, 0xc459191130, 0x0, 0x1d0, 0x12)
	/usr/local/go/src/sort/sort.go:192 +0x80
sort.Sort(0x4e58ee0, 0xc459191130)
	/usr/local/go/src/sort/sort.go:220 +0x79
github.com/dgraph-io/dgraph/types.SortWithFacet(0xc4201d5000, 0x1d0, 0x1d0, 0xc4404e4040, 0xc45feb2000, 0x1d0, 0x200, 0xc450a6f16c, 0x1, 0x1, ...)
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/types/sort.go:98 +0x19f
github.com/dgraph-io/dgraph/query.(*SubGraph).sortAndPaginateUsingFacet(0xc4452ce280, 0x4e59aa0, 0xc45fc4e2a0, 0x1d0, 0x1053d6)
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/query/query.go:2156 +0x799
github.com/dgraph-io/dgraph/query.(*SubGraph).applyOrderAndPagination(0xc4452ce280, 0x4e59aa0, 0xc45fc4e2a0, 0xc44037f2c0, 0x0)
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/query/query.go:2073 +0x36a
github.com/dgraph-io/dgraph/query.ProcessGraph(0x4e59aa0, 0xc45fc4e2a0, 0xc4452ce280, 0xc44081d680, 0xc45fc4e480)
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/query/query.go:1959 +0x1667
created by github.com/dgraph-io/dgraph/query.ProcessGraph
	/Users/pawanrawal/go/src/github.com/dgraph-io/dgraph/query/query.go:2024 +0x11c5
```
And the query that **works**:
```
{
	me(func: eq(label@en, "Anarchism") ) {
		_uid_,
    		xid,
    		wikipedia.name,
    		related (first:5) @facets(weight) {
    			xid
    		}
	}
}
```
And the query that **crashes**:
```
{
	me(func: eq(label@en, "Anarchism") ) {
		_uid_,
    		xid,
    		wikipedia.name,
    		related (first:5) @facets(orderdesc: weight) {
    			xid
    		}
	}
}
```
And this is a sample of the RDFs I inserted (successfully since they are returned when not using any sorting.)
```
<0x1053b1> <related> uid(v562) (weight=0.371927750819, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v563) (weight=0.333186097632, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v564) (weight=0.294444444444, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v565) (weight=0.255702791257, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v566) (weight=0.21696113807, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v567) (weight=0.181552818216, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v569) (weight=0.342354112231, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v570) (weight=0.177316162747, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v572) (weight=0.449228567874, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v573) (weight=0.391968396168, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v574) (weight=0.334708224462, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v575) (weight=0.277448052756, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v576) (weight=0.22018788105, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v577) (weight=0.166261042678, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v583) (weight=0.460116280385, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v585) (weight=0.15788727137, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v586) (weight=0.395273564311, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v587) (weight=0.363265917857, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v588) (weight=0.331258271404, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v590) (weight=0.150241383601, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v595) (weight=0.171319578766, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v598) (weight=0.433076189291, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v599) (weight=0.394334536104, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v600) (weight=0.355592882917, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v601) (weight=0.316851229729, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v602) (weight=0.278109576542, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v603) (weight=0.239367923354, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v605) (weight=0.162761809962, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v610) (weight=0.397611048899, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v611) (weight=0.368128654971, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v612) (weight=0.338646261043, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v613) (weight=0.309163867115, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v614) (weight=0.279681473187, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v615) (weight=0.250199079258, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v616) (weight=0.22071668533, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v617) (weight=0.191234291402, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v618) (weight=0.161751897474, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v622) (weight=0.385969356014, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v623) (weight=0.336645692245, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v626) (weight=0.237170941538, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v627) (weight=0.187847277769, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v636) (weight=0.383407988055, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v637) (weight=0.348370038572, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v648) (weight=0.33751399776, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v651) (weight=0.199944008959, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v656) (weight=0.337619758616, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v657) (weight=0.280359586911, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v658) (weight=0.223099415205, updated=2017-10-15T20:09:17+02:00) .
<0x1053b1> <related> uid(v659) (weight=0.165839243499, updated=2017-10-15T20:09:17+02:00) .
```
And this is an example of what it returned (without sorting):
```
{
  "data": {
    "me": [
      {
        "_uid_": "0x1053b1",
        "xid": "Anarchism",
        "wikipedia.name": "Anarchism",
        "related": [
          {
            "xid": "Agriculture",
            "@facets": {
              "_": {
                "weight": 0.654526
              }
            }
          },
          {
            "xid": "Albert_Camus",
            "@facets": {
              "_": {
                "weight": 0.81443
              }
            }
          },
          {
            "xid": "Allen_Ginsberg",
            "@facets": {
              "_": {
                "weight": 0.727688
              }
            }
          },
          {
            "xid": "Anarcho-capitalism",
            "@facets": {
              "_": {
                "weight": 0.498815
              }
            }
          },
          {
            "xid": "Austrian_School",
            "@facets": {
              "_": {
                "weight": 0.368701
              }
            }
          }
        ]
      }
    ]
  }
}
Server latency: 39.7s
```

**Comment by peterstace** [comment] 2017-10-15 23:41
@lazharichir - which version of dgraph are you using?

**Comment by peterstace** [comment] 2017-10-15 23:58
I've been able to reproduce the problem. Here's a minimal working example:

```
mutation{
  schema{
    name: string @index(exact) .
  }
  set{
    _:a <name> "Hello" .
    _:a <related> _:b (weight=1) .
    _:a <related> _:c (weight=0.333186097632) .
  }
}
```
Crashes with the following query:
```
{
  q(func: eq(name, "Hello")) {
    name
    related @facets(orderasc: weight) {}
  }
}
```

The crash occurs because the `orderasc` tries to sort by weight. However, one of the weights is stored as a float, and another as an int. The sorting code assumes the types it is sorting are all the same.

In this case, it would make sense to just convert to the lowest common denominator and then do the sort (i.e. convert everything to floats). However, this wouldn't work in general. This bug would also show up if you were for example to have a string and an int, or a datetime and a bool in the same facet). In general, these no obvious way to convert to have sensible sorting.

**I suspect that you have an integer only weight somewhere. Can you confirm this for me?**

**Comment by peterstace** [comment] 2017-10-16 00:14
We definitely don't want dgraph to crash when it tries to sort facets containing different data types. However, facets don't have schema - their datatype is just whatever is automatically detected for that RDF. So we can't really check if the type is valid when the mutation occurs (since there is no concept of 'correct' type).

I think the best solution here is to artificially give an ordering to the different types. The ordering I propose:

* Bool
* Int and float together (can convert ints to float before sorting -- this will work without precision issues since int facets are 32 bits signed and float facets are 64 bits - all 32 bit integers can be stored exactly inside 64 bit floats).
* Date time
* String

With this proposal, we won't get any more of these types of crashes, data types that are all the same will still be sorted naturally, and mixes of int and float data will be sorted in a sensible way. I don't think there is any sensible way to sort e.g. string and bool types, so I don't think that it matters that all bools would arbitrarily come before all strings.

**Comment by manishrjain** [comment] 2017-10-16 00:15
SGTM!

**Comment by peterstace** [comment] 2017-10-16 02:46
PR: #1641

**Comment by peterstace** [comment] 2017-10-16 03:08
Merged into v0.8.3 branch at 1a8a448. Will do a release shortly.

**Comment by peterstace** [comment] 2017-10-16 03:51
v0.8.3 binaries have been updated

**Closed by peterstace** 2017-10-16 03:51 UTC
Labels: bug, investigate

**Comment by peterstace** [comment] 2017-10-16 03:54
Cherry-picked into master as well (commit 4d52b3819ae59476dd2897d49abb1ad79e1dce63).

**Comment by lazharichir** [comment] 2017-10-16 06:44
@peterstace Indeed, there is an int when the weight is 1 (from 0 to 1 scale) so I assume it may have crashed when it met both, plenty of floats, and an integer 1. Thanks for fixing super fast Peter!
