### ISSUE TITLE
Invalid function name : anyof

### ISSUE THREAD

**Issue by sayden** [dgraph-io/dgraph#716] opened 2017-03-19 10:56 UTC
I have compiled commit 1037adf and installed RocksDB from Arch repositories (I'm sorry, I don't know how to check RocksDB version).

I have populated with this data:

```
mutation {
 set {
   <_:mario> <name> "sayden" .
   <_:mario> <likes> <_:tesla> .
   <_:tesla> <name> "teslunia" .
 }
}
```

Now I want to now what like people with name `sayden`:

```
{
	me(func:anyof(name, "sayden")){
		name
		likes {
			name
		}
	}
}
```

Returns `Invalid function name : anyof`

Regards

**Comment by davcdhanesh1** [comment] 2017-03-19 11:44
Anyof has been replaced by 'anyofterms'. Just see if it gives you the same
result. The documentation is mostly for version 0.7. In next release anyof
would be replaced by anyofterms is what I believe.

**Comment by sayden** [comment] 2017-03-19 14:22
Thank you @davcdhanesh1 

Now it seems to found the function but no results are returned. Maybe I'm misinterpreting the docs:

```
{
	me(func:anyofterms(name, "sayden")){
		_uid_
		name
		likes {
			name
		}
	}
}
```

Returns
```
{}
```

**Comment by davcdhanesh1** [comment] 2017-03-19 14:50
Maybe I can guess the problem, but before that can u please share the
schema file that u are using.

**Comment by davcdhanesh1** [comment] 2017-03-19 16:44
@sayden, 

I tried the same queries that you have used to reproduce the issues. 

My schema file looks like this:

likes: uid @reverse
name: string @index

// Note that I haven't used keyword scalar, it's not required for anymore

Explaination of schema:

- '@reverse' means there can be edge from one node to another node named 'likes' which will be represented by uid datatype. In Dgraph terminology, it's called predicate.
- 'name' doesn't have @reverse property. What it implies is that 'name' will be used as an attributed on any node in Graph. So looking at your mutation block, <_:mario> is a node whose 'name' attribute is "sayden".

By using this schema, start the Dgraph server with below command:

dgraph --schema <name-of-schema-file>.schema

After doing this, if you try the same set of queries for mutation and getting nodes. You will get the expected same result.

Here is what I got in response for second fetch query.
```
{
  "me": [
    {
      "_uid_": "0x9d0a4b0abfc8a735",
      "likes": [
        {
          "_uid_": "0x935fe5006078efb7",
          "name": "teslunia"
        }
      ],
      "name": "sayden"
    }
  ]
}
```
I hope this resolves your issue. Please shout out if doesn't.

**Comment by sayden** [comment] 2017-03-19 19:19
Oook, @davcdhanesh1 is workingnow! Thank you very much.

I was trying without schema and using the following one:

```
name: string
likes: uid
```

Which makes me think that we'll have to index most (if not all) of our properties. I guess this will affect performance negatively.

Actually it makes sense but it's a little unintuitive at first. Also it's gonna be quite time consuming to makes schemas for each of our 50-60 types. I guess that a "index all with reverse too" option would be a bit too much problematic.

Feel free to close the issue, maybe you want to leave it open until you change the docs.

**Comment by manishrjain** [comment] 2017-03-20 00:08
Thanks for your help @davcdhanesh1!

Hey @sayden,

Documentation across various branches of Dgraph is an issue right now. MediaWiki does a single branch versioning. Maintaining multiple parallel branches of documentation isn't allowed. So, we're switching all our docs to Github, which would allow us to maintain docs for our various releases + master. This would avoid the issue that you faced.

We'll have the documentation up today or tomorrow -- and then we'll figure out how to make the branches work -- so expect some good docs by this weekend.

I'll ref this issue against another one, and close this.

**Closed by manishrjain** 2017-03-20 00:08 UTC

**Comment by manishrjain** [comment] 2017-03-20 00:10
#717

**Comment by manishrjain** [comment] 2017-03-20 00:15
@sayden : Question: Do all of your 50-60 predicates, need to be indexed? Typically, what we've seen with data is that most predicates are used for connections, but some for "properties", like name, dob, etc. How is your data structured?

**Comment by sayden** [comment] 2017-03-20 00:34
Well, in fact with "types" I meant Go types, each with 20-30 fields, say 1000 fields so just indexing like 30% of them will still be quite a lot of work. Other 70% will be properties, of course. Some data won't be inserted at all and our "source of truth" will still be in the main app database (which stores JSON documents).

Answering your question, probably we won't need to index everything but for a fraud detection system, our use case is to get information by discovering hidden relationships. It's hard to know in advance the type of relations you're looking for each particular business so it's going to be something slightly more complex than a "fraud ring" to just index in advance address, phone, etc.

By the way, I also realized that it was a "bad weekend" to start digging with this product with the recent version change and the outdated documentation. Just give it some time when you can, I think you're doing a great work.

**Comment by manishrjain** [comment] 2017-03-20 00:53
@sayden : Typically, you'll pick up the latest released version of Dgraph, instead of master. If you're a user, that's the recommended path. The documentation is synced up to that release. I won't call it outdated :-). Having said that, we do need docs for master because people often try to use the master branch directly (we don't recommend it).

It's not clear from your explanation, but I think there's probably some misunderstanding about how Dgraph works -- traversing relationships doesn't require indexing. Also, a 1000 fields doesn't necessarily equate to a 1000 predicates. So, you might have fewer predicates, and only some of those need indexing.

**Comment by sayden** [comment] 2017-03-20 19:34
Forgive me for saying that docs are "outdated", I meant that most users will take the latest released version **unless** you see that the current released version is being replaced and the API is not fully compatible. Nobody wants to rewrite code in the short term, you know.

As you say, we'll try to add as many properties (no predicates) as possible but the key for us is to not be limited anyhow.

Our queries are like find "a telephone number or a credit card that is shared by users", etc. We are interested in exploring relationships in dgraph. To do aggregations we already have our current datastore.
