### ISSUE TITLE
Potential index consistency issue after deletion

### ISSUE THREAD

**Issue by Smerity** [dgraph-io/dgraph#2612] opened 2018-09-25 01:34 UTC
- What version of Dgraph are you using?
Dgraph version   : v1.0.8
Commit SHA-1     : 1dd8376f
Commit timestamp : 2018-08-31 10:47:07 -0700
Branch           : HEAD

- Have you tried reproducing the issue with latest release?
As far as I am aware this is the latest release (according to Github Releases).

- What is the hardware spec (RAM, OS)?
Macbook Pro, 16GB

- Steps to reproduce the issue (command/config used to run Dgraph).
Included is a Python script 34 lines long: [https://gist.github.com/Smerity/0dafff2524da75f102a13a8c71bbf8be](https://gist.github.com/Smerity/0dafff2524da75f102a13a8c71bbf8be)

1. Create two objects, each with a UID and small text field `snippet`
2. Query based on `has(snippet)` returns two results
3. Delete one of the two objects using `txn.mutate(del_obj({'uid': <UID>}))`
4. Query based on `has(snippet)` still returns two results - one of which is an empty object (only UID)

- Expected behaviour and actual result.
Expected behaviour would be for `has(snippet)` to not have a phantom ghost UID appear. At the end only a single object should be return.

Unless I misunderstand something my guess is this may be a bug in the index creation and maintenance step. I suspect this as when you modify the schema (i.e. add or change an index over the `snippet` predicate) the query no longer returns phantom ghost UID objects.

**Comment by manishrjain** [comment] 2018-09-25 01:41
Can you test with v1.0.9-rc4? It was fixed.

Duplicate of https://github.com/dgraph-io/dgraph/issues/2574.

**Closed by manishrjain** 2018-09-25 01:41 UTC

**Comment by Smerity** [comment] 2018-09-25 01:43
Thanks and sorry @manishrjain!

I tried searching earlier for GitHub issues but realized GitHub had defaulted to `is:open` and I didn't also check `is:closed`.

Very appreciative of the quick reply and doubly happy that all I need to do is update my version to rc4 =]
