### ISSUE TITLE
Still have infinite TryAbort on 1.0.14-rc1

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3183] opened 2019-03-21 08:49 UTC
1 dgraph node is infinitely trying to abort transaction
max_retries is set to 10
logs are here: https://drive.google.com/file/d/1uxWh65G7RpBptXOmMj5asYKJ1-Vsk2LL/view?usp=sharing

**Comment by manishrjain** [comment] 2019-03-21 12:06
Seems like your proposals are not going through. So, the aborted txns are unable to get applied to the Alphas. So, the real question is, why are the proposals stuck...

**Comment by manishrjain** [comment] 2019-03-21 12:13
We have tracing around proposals, so looking at /z/tracez should help --- there should already be other proposals which are probably stuck as well. Does the cluster have quorum? There're no logs from other Alphas, so not sure what they're seeing.

We can also add OpenCensus tracing in txn aborts, so we can get a better idea for why those proposals are not getting applied.

**Comment by makitka2007** [comment] 2019-03-21 13:37
unfortunately i already restarted it since didn't have time to wait, will try this trace endpoint next time

**Comment by makitka2007** [comment] 2019-03-21 15:58
ok, i got it again, but now there are only 2 nodes, 1 was killed and not rescued by amazon due to some amazon limits issue. other 2 nodes have a quorum
i am not sure that it's the same case as before but again got infinite tries to abort transaction
here is an output for trace for "tryAbort" errors: https://drive.google.com/file/d/1ke0HrUd-QiYWerthMKHBq1aGjQAl85tW/view?usp=sharing

**Comment by manishrjain** [comment] 2019-03-21 20:46
That image doesn't have the trace which can show what's happening with the proposal.

**Comment by emhagman** [comment] 2019-04-23 02:14
Same thing happened to us, 3 replica nodes, 1 zero. Using version **1.0.13**

```
ts:1856710 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1856578 commit_ts:1856627 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1856572 commit_ts:1856626 > txns:<start_ts:1849507 > txns:<start_ts:1856568 commit_ts:1856618 > txns:<start_ts:1856566 commit_ts:1856684 > txns:<start_ts:1849478 > txns:<start_ts:1856683 commit_ts:1856685 > txns:<start_ts:1856500 commit_ts:1856676 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1856582 commit_ts:1856691 > txns:<start_ts:1856706 commit_ts:1856707 > txns:<start_ts:1849562 > txns:<start_ts:1849444 >
cluster0-node2_1  | I0423 01:57:41.808058       8 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1849592 > txns:<start_ts:1856467 > txns:<start_ts:1849405 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1849520 > txns:<start_ts:1849483 > txns:<start_ts:1849424 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1849507 > txns:<start_ts:1849478 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1849562 > txns:<start_ts:1849444 >
cluster0-node2_1  | I0423 01:58:11.730462       8 draft.go:1036] Skipping snapshot at index: 957757. Insufficient discard entries: 0. MinPendingStartTs: 1846896
cluster0-node2_1  | I0423 01:58:11.730563       8 draft.go:925] Found 52 old transactions. Acting to abort them.
cluster0-node2_1  | I0423 01:58:11.820115       8 draft.go:885] TryAbort 52 txns with start ts. Error: <nil>
cluster0-node2_1  | I0423 01:58:11.820128       8 draft.go:892] TryAbort returned with delta: txns:<start_ts:1846899 > txns:<start_ts:1856464 commit_ts:1856589 > txns:<start_ts:1856579 commit_ts:1856689 > txns:<start_ts:1856542 commit_ts:1856678 > txns:<start_ts:1856573 commit_ts:1856687 > txns:<start_ts:1856569 commit_ts:1856686 > txns:<start_ts:1856567 commit_ts:1856585 > txns:<start_ts:1849520 > txns:<start_ts:1856550 commit_ts:1856681 > txns:<start_ts:1849483 > txns:<start_ts:1856558 commit_ts:1856682 > txns:<start_ts:1856480 commit_ts:1856674 > txns:<start_ts:1849424 > txns:<start_ts:1856708 commit_ts:1856710 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1856578 commit_ts:1856627 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1856572 commit_ts:1856626 > txns:<start_ts:1849507 > txns:<start_ts:1856568 commit_ts:1856618 > txns:<start_ts:1856566 commit_ts:1856684 > txns:<start_ts:1849478 > txns:<start_ts:1856683 commit_ts:1856685 > txns:<start_ts:1856500 commit_ts:1856676 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1856582 commit_ts:1856691 > txns:<start_ts:1856706 commit_ts:1856707 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856711 commit_ts:1856712 > txns:<start_ts:1856467 > txns:<start_ts:1856493 commit_ts:1856675 > txns:<start_ts:1857024 commit_ts:1857025 > txns:<start_ts:1856799 commit_ts:1856800 > txns:<start_ts:1856547 commit_ts:1856680 > txns:<start_ts:1856576 commit_ts:1856688 > txns:<start_ts:1849405 > txns:<start_ts:1856907 commit_ts:1856908 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1856581 commit_ts:1856628 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 >
cluster0-node2_1  | I0423 01:58:11.820234       8 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1846899 > txns:<start_ts:1849520 > txns:<start_ts:1849483 > txns:<start_ts:1849424 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1849507 > txns:<start_ts:1849478 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856467 > txns:<start_ts:1849405 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 >
cluster0-node2_1  | I0423 01:58:41.731645       8 draft.go:1036] Skipping snapshot at index: 957757. Insufficient discard entries: 0. MinPendingStartTs: 1846896
cluster0-node2_1  | I0423 01:58:41.731736       8 draft.go:925] Found 52 old transactions. Acting to abort them.
cluster0-node2_1  | I0423 01:58:41.811844       8 draft.go:885] TryAbort 52 txns with start ts. Error: <nil>
cluster0-node2_1  | I0423 01:58:41.811859       8 draft.go:892] TryAbort returned with delta: txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1856582 commit_ts:1856691 > txns:<start_ts:1856706 commit_ts:1856707 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856711 commit_ts:1856712 > txns:<start_ts:1856467 > txns:<start_ts:1856493 commit_ts:1856675 > txns:<start_ts:1857024 commit_ts:1857025 > txns:<start_ts:1856799 commit_ts:1856800 > txns:<start_ts:1856547 commit_ts:1856680 > txns:<start_ts:1856576 commit_ts:1856688 > txns:<start_ts:1849405 > txns:<start_ts:1856907 commit_ts:1856908 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1856581 commit_ts:1856628 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1856464 commit_ts:1856589 > txns:<start_ts:1856579 commit_ts:1856689 > txns:<start_ts:1856542 commit_ts:1856678 > txns:<start_ts:1856573 commit_ts:1856687 > txns:<start_ts:1856569 commit_ts:1856686 > txns:<start_ts:1856567 commit_ts:1856585 > txns:<start_ts:1849520 > txns:<start_ts:1856550 commit_ts:1856681 > txns:<start_ts:1849483 > txns:<start_ts:1856558 commit_ts:1856682 > txns:<start_ts:1856480 commit_ts:1856674 > txns:<start_ts:1849424 > txns:<start_ts:1856708 commit_ts:1856710 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1856578 commit_ts:1856627 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1856572 commit_ts:1856626 > txns:<start_ts:1849507 > txns:<start_ts:1856568 commit_ts:1856618 > txns:<start_ts:1856566 commit_ts:1856684 > txns:<start_ts:1849478 > txns:<start_ts:1856683 commit_ts:1856685 > txns:<start_ts:1856500 commit_ts:1856676 > txns:<start_ts:1846958 >
cluster0-node2_1  | I0423 01:58:41.811949       8 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856467 > txns:<start_ts:1849405 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1849520 > txns:<start_ts:1849483 > txns:<start_ts:1849424 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1849507 > txns:<start_ts:1849478 > txns:<start_ts:1846958 >
cluster0-node2_1  | I0423 01:59:11.729774       8 draft.go:1036] Skipping snapshot at index: 957757. Insufficient discard entries: 0. MinPendingStartTs: 1846896
cluster0-node2_1  | I0423 01:59:11.729885       8 draft.go:925] Found 52 old transactions. Acting to abort them.
cluster0-node2_1  | I0423 01:59:11.807063       8 draft.go:885] TryAbort 52 txns with start ts. Error: <nil>
cluster0-node2_1  | I0423 01:59:11.807075       8 draft.go:892] TryAbort returned with delta: txns:<start_ts:1856567 commit_ts:1856585 > txns:<start_ts:1849520 > txns:<start_ts:1856550 commit_ts:1856681 > txns:<start_ts:1849483 > txns:<start_ts:1856558 commit_ts:1856682 > txns:<start_ts:1856480 commit_ts:1856674 > txns:<start_ts:1849424 > txns:<start_ts:1856708 commit_ts:1856710 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1856578 commit_ts:1856627 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1856572 commit_ts:1856626 > txns:<start_ts:1849507 > txns:<start_ts:1856568 commit_ts:1856618 > txns:<start_ts:1856566 commit_ts:1856684 > txns:<start_ts:1849478 > txns:<start_ts:1856683 commit_ts:1856685 > txns:<start_ts:1856500 commit_ts:1856676 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1856582 commit_ts:1856691 > txns:<start_ts:1856706 commit_ts:1856707 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856711 commit_ts:1856712 > txns:<start_ts:1856467 > txns:<start_ts:1856493 commit_ts:1856675 > txns:<start_ts:1857024 commit_ts:1857025 > txns:<start_ts:1856799 commit_ts:1856800 > txns:<start_ts:1856547 commit_ts:1856680 > txns:<start_ts:1856576 commit_ts:1856688 > txns:<start_ts:1849405 > txns:<start_ts:1856907 commit_ts:1856908 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1856581 commit_ts:1856628 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1856464 commit_ts:1856589 > txns:<start_ts:1856579 commit_ts:1856689 > txns:<start_ts:1856542 commit_ts:1856678 > txns:<start_ts:1856573 commit_ts:1856687 > txns:<start_ts:1856569 commit_ts:1856686 >
cluster0-node2_1  | I0423 01:59:11.807175       8 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1849520 > txns:<start_ts:1849483 > txns:<start_ts:1849424 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1849507 > txns:<start_ts:1849478 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856467 > txns:<start_ts:1849405 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 >
cluster0-node2_1  | I0423 01:59:41.729204       8 draft.go:1036] Skipping snapshot at index: 957757. Insufficient discard entries: 0. MinPendingStartTs: 1846896
cluster0-node2_1  | I0423 01:59:41.729303       8 draft.go:925] Found 52 old transactions. Acting to abort them.
cluster0-node2_1  | I0423 01:59:41.808519       8 draft.go:885] TryAbort 52 txns with start ts. Error: <nil>
cluster0-node2_1  | I0423 01:59:41.808530       8 draft.go:892] TryAbort returned with delta: txns:<start_ts:1856493 commit_ts:1856675 > txns:<start_ts:1857024 commit_ts:1857025 > txns:<start_ts:1856799 commit_ts:1856800 > txns:<start_ts:1856547 commit_ts:1856680 > txns:<start_ts:1856576 commit_ts:1856688 > txns:<start_ts:1849405 > txns:<start_ts:1856907 commit_ts:1856908 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1856581 commit_ts:1856628 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1856464 commit_ts:1856589 > txns:<start_ts:1856579 commit_ts:1856689 > txns:<start_ts:1856542 commit_ts:1856678 > txns:<start_ts:1856573 commit_ts:1856687 > txns:<start_ts:1856569 commit_ts:1856686 > txns:<start_ts:1856567 commit_ts:1856585 > txns:<start_ts:1849520 > txns:<start_ts:1856550 commit_ts:1856681 > txns:<start_ts:1849483 > txns:<start_ts:1856558 commit_ts:1856682 > txns:<start_ts:1856480 commit_ts:1856674 > txns:<start_ts:1849424 > txns:<start_ts:1856708 commit_ts:1856710 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1856578 commit_ts:1856627 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1856572 commit_ts:1856626 > txns:<start_ts:1849507 > txns:<start_ts:1856568 commit_ts:1856618 > txns:<start_ts:1856566 commit_ts:1856684 > txns:<start_ts:1849478 > txns:<start_ts:1856683 commit_ts:1856685 > txns:<start_ts:1856500 commit_ts:1856676 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1856582 commit_ts:1856691 > txns:<start_ts:1856706 commit_ts:1856707 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856711 commit_ts:1856712 > txns:<start_ts:1856467 >
cluster0-node2_1  | I0423 01:59:41.808623       8 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1849405 > txns:<start_ts:1849582 > txns:<start_ts:1849427 > txns:<start_ts:1846896 > txns:<start_ts:1849475 > txns:<start_ts:1849586 > txns:<start_ts:1849548 > txns:<start_ts:1846899 > txns:<start_ts:1849520 > txns:<start_ts:1849483 > txns:<start_ts:1849424 > txns:<start_ts:1849572 > txns:<start_ts:1849545 > txns:<start_ts:1846917 > txns:<start_ts:1846951 > txns:<start_ts:1849525 > txns:<start_ts:1849458 > txns:<start_ts:1849507 > txns:<start_ts:1849478 > txns:<start_ts:1846958 > txns:<start_ts:1849471 > txns:<start_ts:1849579 > txns:<start_ts:1849562 > txns:<start_ts:1849444 > txns:<start_ts:1849592 > txns:<start_ts:1856467 >
```

**Comment by manishrjain** [comment] 2019-04-26 01:08
Is this still happening @emhagman @makitka2007 ?

**Comment by emhagman** [comment] 2019-04-30 00:36
I'm not sure. I did notice a call fail to write to the graph today after 10 retries, I'm going to check the logs again tonight and see if was related. I'll get back to you in a few hours.

**Comment by emhagman** [comment] 2019-04-30 05:32
It is still happening on 1.0.14 for me.

```
cluster0-node1_1  | I0430 03:06:53.164990     899 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1442510 > txns:<start_ts:1443079 > txns:<start_ts:1442079 > txns:<start_ts:1442237 > txns:<start_ts:1442069 > txns:<start_ts:1442348 > txns:<start_ts:1444246 > txns:<start_ts:1443433 > txns:<start_ts:1442504 > txns:<start_ts:1442143 > txns:<start_ts:1443053 > txns:<start_ts:1442323 > txns:<start_ts:1442153 > txns:<start_ts:1443288 > txns:<start_ts:1444600 > txns:<start_ts:1442075 > txns:<start_ts:1442729 > txns:<start_ts:1443785 > txns:<start_ts:1442222 > txns:<start_ts:1443205 > txns:<start_ts:1443591 > txns:<start_ts:1441878 > txns:<start_ts:1443714 > txns:<start_ts:1441896 > txns:<start_ts:1441892 > txns:<start_ts:1443222 > txns:<start_ts:1444213 > txns:<start_ts:1444506 > txns:<start_ts:1443021 > txns:<start_ts:1444391 > txns:<start_ts:1443316 > txns:<start_ts:1444265 > txns:<start_ts:1442284 > txns:<start_ts:1443225 > txns:<start_ts:1443941 > txns:<start_ts:1442408 > txns:<start_ts:1441870 > txns:<start_ts:1442980 > txns:<start_ts:1442101 > txns:<start_ts:1442240 > txns:<start_ts:1443654 > txns:<start_ts:1443340 > txns:<start_ts:1442097 > txns:<start_ts:1444194 > txns:<start_ts:1444657 > txns:<start_ts:1442983 > txns:<start_ts:1442055 > txns:<start_ts:1443935 > txns:<start_ts:1442082 > txns:<start_ts:1444253 > txns:<start_ts:1442835 > txns:<start_ts:1444494 > txns:<start_ts:1443180 > txns:<start_ts:1443056 > txns:<start_ts:1444219 > txns:<start_ts:1443044 > txns:<start_ts:1444388 > txns:<start_ts:1443399 > txns:<start_ts:1442671 > txns:<start_ts:1444593 > txns:<start_ts:1442806 > txns:<start_ts:1444310 > txns:<start_ts:1442418 > txns:<start_ts:1443347 > txns:<start_ts:1441881 > txns:<start_ts:1442639 > txns:<start_ts:1442746 > txns:<start_ts:1442089 > txns:<start_ts:1444250 > txns:<start_ts:1444097 > txns:<start_ts:1443322 > txns:<start_ts:1442741 > txns:<start_ts:1442995 > txns:<start_ts:1444094 > txns:<start_ts:1442625 > txns:<start_ts:1443035 > txns:<start_ts:1442383 > txns:<start_ts:1442379 > txns:<start_ts:1442587 > txns:<start_ts:1442513 > txns:<start_ts:1442744 > txns:<start_ts:1442392 > txns:<start_ts:1442678 > txns:<start_ts:1444561 > txns:<start_ts:1442341 > txns:<start_ts:1442647 > txns:<start_ts:1442134 > txns:<start_ts:1442375 > txns:<start_ts:1443811 > txns:<start_ts:1444216 > txns:<start_ts:1444570 > txns:<start_ts:1444491 > txns:<start_ts:1444674 > txns:<start_ts:1444622 > txns:<start_ts:1443588 > txns:<start_ts:1443772 > txns:<start_ts:1444488 > txns:<start_ts:1442405 > txns:<start_ts:1442965 > txns:<start_ts:1442619 > txns:<start_ts:1442073 > txns:<start_ts:1444091 > txns:<start_ts:1443211 > txns:<start_ts:1444649 > txns:<start_ts:1444063 > txns:<start_ts:1443631 > txns:<start_ts:1443967 > txns:<start_ts:1443766 > txns:<start_ts:1444215 > txns:<start_ts:1443313 > txns:<start_ts:1444230 > txns:<start_ts:1442756 > txns:<start_ts:1442559 > txns:<start_ts:1442388 > txns:<start_ts:1442397 > txns:<start_ts:1442415 > txns:<start_ts:1442244 > txns:<start_ts:1444236 > txns:<start_ts:1443970 > txns:<start_ts:1444652 > txns:<start_ts:1443747 > txns:<start_ts:1442281 > txns:<start_ts:1442971 > txns:<start_ts:1444242 > txns:<start_ts:1442234 > txns:<start_ts:1442225 > txns:<start_ts:1443041 > txns:<start_ts:1443018 > txns:<start_ts:1443991 > txns:<start_ts:1444581 > txns:<start_ts:1444088 > txns:<start_ts:1443071 > txns:<start_ts:1441862 > txns:<start_ts:1442231 > txns:<start_ts:1442228 > txns:<start_ts:1443259 > txns:<start_ts:1442653 > txns:<start_ts:1444371 > txns:<start_ts:1442137 > txns:<start_ts:1442732 > txns:<start_ts:1442753 > txns:<start_ts:1443310 > txns:<start_ts:1442622 > txns:<start_ts:1443337 > txns:<start_ts:1442821 > txns:<start_ts:1443061 > txns:<start_ts:1442532 > txns:<start_ts:1443065 > txns:<start_ts:1443328 > txns:<start_ts:1442986 > txns:<start_ts:1442590 > txns:<start_ts:1444225 > txns:<start_ts:1442519 > txns:<start_ts:1443214 > txns:<start_ts:1443245 > txns:<start_ts:1442130 > txns:<start_ts:1443988 > txns:<start_ts:1444304 > txns:<start_ts:1443320 > txns:<start_ts:1442124 > txns:<start_ts:1443007 > txns:<start_ts:1444662 > txns:<start_ts:1442636 > txns:<start_ts:1443038 > txns:<start_ts:1442738 > txns:<start_ts:1443944 > txns:<start_ts:1443693 > txns:<start_ts:1443769 > txns:<start_ts:1443479 > txns:<start_ts:1444330 > txns:<start_ts:1443615 > txns:<start_ts:1442317 > txns:<start_ts:1443973 > txns:<start_ts:1443427 > txns:<start_ts:1443502 > txns:<start_ts:1444723 > txns:<start_ts:1442809 > txns:<start_ts:1444632 > txns:<start_ts:1442642 > txns:<start_ts:1443334 > txns:<start_ts:1444567 > txns:<start_ts:1441888 > txns:<start_ts:1444564 > txns:<start_ts:1443255 > txns:<start_ts:1444646 > txns:<start_ts:1444014 > txns:<start_ts:1444070 > txns:<start_ts:1442541 > txns:<start_ts:1443003 > txns:<start_ts:1442839 > txns:<start_ts:1442605 > txns:<start_ts:1444077 > txns:<start_ts:1444189 > txns:<start_ts:1442656 > txns:<start_ts:1442526 > txns:<start_ts:1442650 > txns:<start_ts:1444256 > txns:<start_ts:1444006 > txns:<start_ts:1442825 > txns:<start_ts:1443627 > txns:<start_ts:1444684 > txns:<start_ts:1442369 > txns:<start_ts:1442400 > txns:<start_ts:1443217 > txns:<start_ts:1442444 >
cluster0-node1_1  | I0430 03:06:53.170427     899 draft.go:928] abortOldTransactions for 205 txns. Error: <nil>
cluster0-node1_1  | I0430 03:07:22.778803     899 draft.go:925] Found 84 old transactions. Acting to abort them.
cluster0-node1_1  | I0430 03:07:22.782782     899 draft.go:312] Creating snapshot at index: 731994. ReadTs: 1446818.
cluster0-node1_1  | I0430 03:07:22.928883     899 draft.go:885] TryAbort 84 txns with start ts. Error: <nil>
cluster0-node1_1  | I0430 03:07:22.928899     899 draft.go:892] TryAbort returned with delta: txns:<start_ts:1445303 > txns:<start_ts:1445103 > txns:<start_ts:1445002 > txns:<start_ts:1445328 > txns:<start_ts:1445347 > txns:<start_ts:1445011 > txns:<start_ts:1445162 > txns:<start_ts:1445389 > txns:<start_ts:1445083 > txns:<start_ts:1445558 > txns:<start_ts:1445176 > txns:<start_ts:1444887 > txns:<start_ts:1445076 > txns:<start_ts:1444824 > txns:<start_ts:1445317 > txns:<start_ts:1445635 > txns:<start_ts:1445086 > txns:<start_ts:1445028 > txns:<start_ts:1445314 > txns:<start_ts:1445400 > txns:<start_ts:1445577 > txns:<start_ts:1445029 > txns:<start_ts:1445148 > txns:<start_ts:1445106 > txns:<start_ts:1444939 > txns:<start_ts:1445495 > txns:<start_ts:1445005 > txns:<start_ts:1444936 > txns:<start_ts:1445583 > txns:<start_ts:1445014 > txns:<start_ts:1444942 > txns:<start_ts:1445186 > txns:<start_ts:1445032 > txns:<start_ts:1445606 > txns:<start_ts:1445663 > txns:<start_ts:1445165 > txns:<start_ts:1445174 > txns:<start_ts:1444732 > txns:<start_ts:1445338 > txns:<start_ts:1445589 > txns:<start_ts:1445580 > txns:<start_ts:1445570 > txns:<start_ts:1445089 > txns:<start_ts:1445666 > txns:<start_ts:1444862 > txns:<start_ts:1445202 > txns:<start_ts:1445552 > txns:<start_ts:1445153 > txns:<start_ts:1445629 > txns:<start_ts:1444996 > txns:<start_ts:1445252 > txns:<start_ts:1445731 > txns:<start_ts:1445682 > txns:<start_ts:1445260 > txns:<start_ts:1445708 > txns:<start_ts:1444993 > txns:<start_ts:1445489 > txns:<start_ts:1445522 > txns:<start_ts:1444879 > txns:<start_ts:1445100 > txns:<start_ts:1445269 > txns:<start_ts:1445596 > txns:<start_ts:1445372 > txns:<start_ts:1445633 > txns:<start_ts:1445565 > txns:<start_ts:1445640 > txns:<start_ts:1445336 > txns:<start_ts:1445263 > txns:<start_ts:1444911 > txns:<start_ts:1445040 > txns:<start_ts:1445073 > txns:<start_ts:1445637 > txns:<start_ts:1445486 > txns:<start_ts:1445022 > txns:<start_ts:1445320 > txns:<start_ts:1444859 > txns:<start_ts:1445655 > txns:<start_ts:1445646 > txns:<start_ts:1445642 > txns:<start_ts:1444999 > txns:<start_ts:1445180 > txns:<start_ts:1444915 > txns:<start_ts:1445658 > txns:<start_ts:1445171 >
cluster0-node1_1  | I0430 03:07:22.929028     899 draft.go:909] TryAbort selectively proposing only aborted txns: txns:<start_ts:1445303 > txns:<start_ts:1445103 > txns:<start_ts:1445002 > txns:<start_ts:1445328 > txns:<start_ts:1445347 > txns:<start_ts:1445011 > txns:<start_ts:1445162 > txns:<start_ts:1445389 > txns:<start_ts:1445083 > txns:<start_ts:1445558 > txns:<start_ts:1445176 > txns:<start_ts:1444887 > txns:<start_ts:1445076 > txns:<start_ts:1444824 > txns:<start_ts:1445317 > txns:<start_ts:1445635 > txns:<start_ts:1445086 > txns:<start_ts:1445028 > txns:<start_ts:1445314 > txns:<start_ts:1445400 > txns:<start_ts:1445577 > txns:<start_ts:1445029 > txns:<start_ts:1445148 > txns:<start_ts:1445106 > txns:<start_ts:1444939 > txns:<start_ts:1445495 > txns:<start_ts:1445005 > txns:<start_ts:1444936 > txns:<start_ts:1445583 > txns:<start_ts:1445014 > txns:<start_ts:1444942 > txns:<start_ts:1445186 > txns:<start_ts:1445032 > txns:<start_ts:1445606 > txns:<start_ts:1445663 > txns:<start_ts:1445165 > txns:<start_ts:1445174 > txns:<start_ts:1444732 > txns:<start_ts:1445338 > txns:<start_ts:1445589 > txns:<start_ts:1445580 > txns:<start_ts:1445570 > txns:<start_ts:1445089 > txns:<start_ts:1445666 > txns:<start_ts:1444862 > txns:<start_ts:1445202 > txns:<start_ts:1445552 > txns:<start_ts:1445153 > txns:<start_ts:1445629 > txns:<start_ts:1444996 > txns:<start_ts:1445252 > txns:<start_ts:1445731 > txns:<start_ts:1445682 > txns:<start_ts:1445260 > txns:<start_ts:1445708 > txns:<start_ts:1444993 > txns:<start_ts:1445489 > txns:<start_ts:1445522 > txns:<start_ts:1444879 > txns:<start_ts:1445100 > txns:<start_ts:1445269 > txns:<start_ts:1445596 > txns:<start_ts:1445372 > txns:<start_ts:1445633 > txns:<start_ts:1445565 > txns:<start_ts:1445640 > txns:<start_ts:1445336 > txns:<start_ts:1445263 > txns:<start_ts:1444911 > txns:<start_ts:1445040 > txns:<start_ts:1445073 > txns:<start_ts:1445637 > txns:<start_ts:1445486 > txns:<start_ts:1445022 > txns:<start_ts:1445320 > txns:<start_ts:1444859 > txns:<start_ts:1445655 > txns:<start_ts:1445646 > txns:<start_ts:1445642 > txns:<start_ts:1444999 > txns:<start_ts:1445180 > txns:<start_ts:1444915 > txns:<start_ts:1445658 > txns:<start_ts:1445171 >
```

**Comment by manishrjain** [comment] 2019-04-30 06:15
@emhagman : The system is working as expected. It is aborting your old pending transactions and letting the group take a snapshot (snapshots happening is always a great signal that system is making progress).

The real question is, why do you have so many transactions pending? You should ensure that your txns are getting committed or aborted correctly via the client.

**Comment by emhagman** [comment] 2019-04-30 14:46
Sorry, it appeared to be the same behavior, I see know the number is changing and it is working.

We use both NodeJS and Elixir. On NodeJS, we definitely do that but I believe it is because we use https://github.com/ospaarmann/exdgraph which does not support transactions yet. I just noticed https://github.com/liveforeverx/dlex on the Dgraph site which supports transactions and was inspired by exdgraph, I am going to give that a try and see.

However, I noticed the slow write from NodeJS. If there are many aborted transactions and Dgraph is trying to play catch up, would that cause writes to slow?

As a side note, would `hash` be a better index than `int` for ID? We never need to do any math on them

**Comment by campoy** [comment] 2019-09-13 16:50
Hey @manishrjain,

Could you give an update on this? Should we investigate further?
It'd be great if we could find a way to reproduce this.

**Comment by ashish-goswami** [comment] 2020-02-21 12:21
Hey @makitka2007 @emhagman, have you observed anything like above in any of latest
release? We have fixed deadlock in proposals(https://github.com/dgraph-io/dgraph/commit/04eafb1c3e54dac2a319c67537c5b99d6e46b240).

**Comment by manishrjain** [comment] 2020-04-09 21:14
Yeah, haven't seen this issue for a while now, and we're at 20.03. I think it's OK to close this issue.

**Closed by manishrjain** 2020-04-09 21:14 UTC
Labels: area/operations, kind/bug, priority/P2, status/needs-attention
