### ISSUE TITLE
Proper catching of errors like "readTs: 60534 less than minTs: 60535 for key"

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#2647] opened 2018-10-10 05:19 UTC
### What you wanted to do

I needed to catch those occasional and unpredictable errors and retry if they happen.

### What you actually did

I parsed the error message and if it matched the error string, modulo the numbers, I ran the query again.

### Why that wasn't great, with examples

Parsing an error string is :
- not efficient: It takes time to parse a string with a regexp matching
- not durable: The string message may change in the future

### Any external references to support your case

This request has been discussed in [that thread](https://discuss.dgraph.io/t/how-to-catch-errors-like-readts-60534-less-than-mints/3355).

**Comment by manishrjain** [comment] 2018-10-21 21:52
Following up on discussions with @srfrog in this direction, we could generate a unique string based code to reflect error; so it can be searched for by the user at their end, without us having to modify all our client libraries.

**Comment by mehdiym** [comment] 2018-10-22 07:31
Thx for your answer.
It would indeed be better, more durable.
Do you mean an error message prefix?

**Comment by mehdiym** [comment] 2018-10-22 07:34
Thx for your answer.
It would indeed be better, more durable.
Do you mean an error message prefix?

**Comment by manishrjain** [comment] 2018-12-18 20:17
Closing this issue as a duplicate of #2646 .

**Closed by manishrjain** 2018-12-18 20:17 UTC
Labels: enhancement
