### ISSUE TITLE
docker service crash after querying empty database

### ISSUE THREAD

**Issue by AndreSteenbergen** [dgraph-io/dgraph#586] opened 2017-02-14 11:55 UTC
to reproduce this issue run:

```docker run --rm -p 8090:8080 --name DGraph -v DGraph:/dgraph dgraph/dgraph dgraph --bindall=true --schema=my.schema```

then without mutating, just querying, the docker instance results in:
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xcf1569]

runtime stack:
runtime.throw(0xeaf4b1, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 73 [syscall, locked to thread]:
runtime.cgocall(0xa937b0, 0xc421e29688, 0x0)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc421e29658 sp=0xc421e29618
github.com/dgraph-io/dgraph/rdb._Cfunc_rdb_iter_value(0x7f9fc5633000, 0xc420015ce8, 0x0)
        github.com/dgraph-io/dgraph/rdb/_obj/_cgo_gotypes.go:518 +0x4e fp=0xc421e29688 sp=0xc421e29658
github.com/dgraph-io/dgraph/rdb.(*Iterator).Value(0xc4201284f8, 0xc4201c1a70)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/rdb/iterator.go:63 +0xa7 fp=0xc421e296e8 sp=0xc421e29688
github.com/dgraph-io/dgraph/worker.getInequalityTokens(0xc42008860f, 0x8, 0xc420214680, 0x20, 0xc42008860b, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/tokens.go:22 +0x13b fp=0xc421e297f8 sp=0xc421e296e8
github.com/dgraph-io/dgraph/worker.processTask(0xc420145680, 0xc400000001, 0x0, 0x0, 0x0)
        /home/ubuntu/go/src/github.com/dgraph-io/dgraph/worker/task.go:130 +0x343 fp=0xc421e29b00 sp=0xc421e297f8
```
etc. the only way to recover is restart the server

**Comment by pawanrawal** [comment] 2017-02-20 04:23
Hi @AndreSteenbergen 

I am unable to reproduce this, in fact I can't start the docker container because in `-v DGraph:/dgraph` , the path to the volume in the instance needs to be absolute (https://github.com/docker/docker/issues/4830), so it should be something like `-v $(pwd)/DGraph:/dgraph`.

Just to clarify, I ran 
```
docker run --rm -p 8090:8080 --name Dgraph -v $(pwd)/DGraph:/dgraph dgraph/dgraph:latest dgraph --bindall=true --schema=my.schema
```
and my `pwd` contained a DGraph directory with a `my.schema` file in it.

Could you try the above command and let me know if the issue persists?

**Comment by AndreSteenbergen** [comment] 2017-02-20 17:03
I am using docker 1.13.1 on windows. It is a named volume, that is created on the host machine, instead of the running directory. The command works for me. And the query is this: (the json parsing can be done better...)
```
       async Task<ulong> GetUid(string type, Guid id)
        {
            if (guidToGraphUid.Count > 100000000)
                guidToGraphUid.Clear();

            if (guidToGraphUid.ContainsKey(id)) return guidToGraphUid[id];
            var qry = $@"
{{
  obj(eq(""objectId"", ""{id.ToString("N")}"")) @filter(eq(""type"", ""{type}"")) {{
    _uid_
  }}
}}";
            var x = await _httpClient.PostAsync("", new StringContent(qry));
            if (x.IsSuccessStatusCode)
            {
                dynamic obj = JObject.Parse(await x.Content.ReadAsStringAsync());
                if (obj != null)
                {
                    JArray resultSet = obj.obj;
                    if (resultSet != null)
                    {
                        foreach (dynamic resultObject in resultSet)
                        {
                            string theUid = resultObject._uid_;
                            return guidToGraphUid[id] = HexLiteral2Unsigned(theUid);
                        }
                    }
                }
            }
            return 0;
        }
```

**Comment by AndreSteenbergen** [comment] 2017-02-20 17:03
Maybe the filter part is the problem

**Comment by pawanrawal** [comment] 2017-02-21 01:03
Hi @AndreSteenbergen I am unfamiliar with the code that you have here. Could you also upload the raw query and the contents of your schema file so that I can run it through our HTTP endpoint and reproduce the crash.

**Comment by AndreSteenbergen** [comment] 2017-02-21 15:00
```
scalar (
    objectId : id @index
    type : string @index
    name : string @index
)
```

and the query:
```
{
  obj(eq("objectId", "d507e730cc4f4ce2847743d23eda02f2")) @filter(eq("type", "website")) {
    _uid_
  }
}
```

**Comment by pawanrawal** [comment] 2017-03-01 00:03
This was associated with #642 and was a bug in Dgraph. It has been fixed and merged to master.

**Closed by pawanrawal** 2017-03-01 00:03 UTC
Labels: author to reply, bug
