### ISSUE TITLE
V1.1 Urgent Issue: Cannot Delete Outgoing Edge with N P * pattern After DGraph Upgrade

### ISSUE THREAD

**Issue by limwcj** [dgraph-io/dgraph#4182] opened 2019-10-17 01:40 UTC
## What version of DGraph are you using?
v1.1.0

## Have you tried reproducing the issue with the latest release?
Yes

## What is the hardware spec (RAM, OS)?
This issue happens on both our local dev environment (macOS) and server. Local mac is running 8gb RAM SSD, Remove server is running Ubuntu 16.04 and is using Dgraph's recommended i3.xLarge on AWS. 

## Description
After upgrading to DGraph V1.1, we've experienced a lot of bugs in our app regarding relationships not being removed. It took us a while to figure it out what the issue was, but we finally narrowed down the problem to node's not being able to delete outgoing edge with the delete <node> <edge> *  mutation. We never use to have this problem, but after the Dgraph upgrade to V1.1 we started experiencing this problem. The weird part about this issue is that it only happens *sometimes* which is very weird and makes us think it's a race condition issue. We tried manually deleting the relatioship in Ratel as well, but the outgoing edge never get's deleted. We've followed the migration steps and made sure to add all type definitinos for all nodes and to define their one-to-one or one-to-many relationships in the schma file as well but it still doesn't seem to work. The delete mutation fires and returns success but the edge still remains.

## Schema definition for the relationship between cell and column option node. 
![Schema definition for cell and column option node](https://user-images.githubusercontent.com/45704878/66970864-7ee80500-f0c1-11e9-8e21-b2cb0d656ed6.png)

## Before Delete Query 
![ Before delete query](https://user-images.githubusercontent.com/45704878/66970705-f6696480-f0c0-11e9-9112-fa6c8418afb8.png)

## Wildcard Delete Mutation with <node> <edge> * .
![Delete mutation for has_column_option edge](https://user-images.githubusercontent.com/45704878/66970776-2ca6e400-f0c1-11e9-8a17-ad9df6928a1f.png)

## After Wildcard Delete Query 
![image](https://user-images.githubusercontent.com/45704878/66970807-4d6f3980-f0c1-11e9-867f-cb6cfb2fd251.png)

As seen above the delete mutation does not delete the has_column_option edge.

# We noticed that if we delete the edge explicitly with the ID that it works with the `N P N` pattern but not `N P *` pattern.

```
delete {
  <node> <edge> <node> .
} 
```

but this *does not work* 

```
delete {
  <node> <edge> * .
} 
```

The issue above only happens *sometimes* which is very weird since only certain nodes/edges seem to exhibit the behavior of not being able to be deleted with the pattern S P *.

## Mutation Deleting Edge Explicitly with Outgoing Node ID with <node> <edge> <node> .
![Deleting explicitly with outgoing node ID](https://user-images.githubusercontent.com/45704878/66971539-41d14200-f0c4-11e9-8b54-1995ee191042.png)

## Query after deleting edge explicitly 
![Query node after deleting explicitly](https://user-images.githubusercontent.com/45704878/66971633-8ceb5500-f0c4-11e9-9690-80dafee12003.png)

This is an urgent issue on our end as our app right now is completely broken so any help with this issue would be greatly appreciated. Thanks in advance!

**Comment by MichelDiz** [comment] 2019-10-17 03:23
Hey limwcj, nice to hear you're using Dgraph in production.

One thing to mention, do never upgrade your production application to any version before testing your codebase (do a "clone" of your application and test it). As you said is the first time you have issues with relationships. That means you come from an old or very old Dgraph version. Be careful, we are always improving Dgraph and that means sometimes that you need to review your whole codebase and let it in testing for some time. Always test first.

So, I can't reproduce your issue. It may be another thing. Did you upgrade in the right way? exporting it and reimporting.

### Please try to reproduce the steps below.
### Sample
```JSON
{
  "set": [
    {
      "name": "Parent 1",
      "hasChild": {
      "name": "Child 1"
      }
    }
  ]
}
```
### Query

```graphql
{
  q(func: eq(name, "Parent 1")){
    uid
    name
    hasChild {
      uid
      name
    }
  }
}
```

### Result
```JSON
{
  "data": {
    "q": [
      {
        "uid": "0x2750",
        "name": "Parent 1",
        "hasChild": [
          {
            "uid": "0x2751",
            "name": "Child 1"
          }
        ]
      }
    ]
  }
}
```

### Delete

```JSON
{
  "delete": [
    {
      "uid": "0x2750",
      "hasChild": { #Delete the relation
        "uid": "0x2751"
    },
    {
      "uid": "0x2751" #than delete the child
    },
    }
  ]
}
```

### Query Again

```
{
  q(func: eq(name, "Parent 1")){
    uid
    name
    hasChild {
      uid
      name
    }
  }
}
```

**Comment by limwcj** [comment] 2019-10-17 03:56
We're currently testing our codebase on our staging environment, and it's very hard to catch this issue because it only happens *sometimes*. The most concerning aspect of this is that we are testing it with new data not old data so this bug actually reappears even locally on new data that we generate. Is there any logic that has changed the way delete operations work with S P *. that we're not aware of? Or maybe it's the one to one/one-to-many relation that has changed this? Thanks!

**Comment by limwcj** [comment] 2019-10-17 04:31
The weirdest thing is that after deleting it with S P *, the mutation returns success and you can clearly see the predicate that has been "deleted" in the response. But when you query the result it's still there. 

![Success After Deleting](https://user-images.githubusercontent.com/45704878/66977818-f75ac000-f0d9-11e9-8696-ec320e3c7089.png)

**Comment by MichelDiz** [comment] 2019-10-17 05:22
Well, if you can reproduce this with new data, surely I could be able to do it too. Need to know how. I'll try to create crazy tests in JS.

>Is there any logic that has changed the way delete operations work with S P *. 

Yes, you must have a well-defined type system and scalar/entities types also correctly defined (like one-one, one-many). Only this. As far as I know.

Can you share the whole context config you have? dgraph configs and so on. Can you replicate this in a simple configuration?

**Comment by limwcj** [comment] 2019-10-17 05:32
Hi @MichelDiz, thank you for your quick response. The issue on our end is it's actually something that happens even when we do the delete mutation in DGraph ratel (not just using the dgraph-js package). My current presumption is that the issue is not an issue with the Dgraph JS package but more of an issue with the delete operation itself. I think it would be easiest for us to show you in a short video. I will make a screen share of what we did and share this.

**Comment by mangalaman93** [comment] 2019-10-17 08:00
@limwcj Have you tried reproducing this issue on current master, just in case? Happy to provide binaries if needed.

**Comment by rickytyho** [comment] 2019-10-17 09:09
Hi @mangalaman93 , I'm with Lim as well. What do you need us to provide? We are currently using docker to pull Dgraph V1.1. Are you suggesting us clone master? That would require some significant changes on our end to get our setup running? Is it possible for us to export the data set to RDF and provide the relevant queries and mutations to replicate the issue on your end? Thanks!

**Comment by mangalaman93** [comment] 2019-10-17 09:35
oh, yeah! That'd work too. You could share the data (assuming no compliance issue) here or email me on aman@dgraph.io.

**Comment by rickytyho** [comment] 2019-10-17 10:01
Yep @mangalaman93 , we are going to export a part of the data set for you and provide the exact mutation and queries to make to replicate the bug. Thanks!

**Comment by mangalaman93** [comment] 2019-10-17 10:58
I can't see any issues, looks like a bug to me. This is such a common use case that we do not expect a bug in this use case. We have many test cases that test this scenario. Though, only when we could look into it, we'd know more.

**Comment by rickytyho** [comment] 2019-10-17 11:57
Hi Aman @mangalaman93 , thank you for your response. I sent an email to aman@dgraph.io with our DGraph dataset and replicate steps to see the bug. Thanks!

**Comment by animesh2049** [comment] 2019-10-17 13:54
I am able to reproduce the issue with the help of data set provided by @rickytyho . I am looking into it.

**Comment by martinmr** [comment] 2019-10-18 00:27
To clarify `S P *` deletions didn't change because of the type system (`S * *` deletions were changed by the type system). So it's probably nothing to do with the type system.

**Comment by rickytyho** [comment] 2019-10-18 03:59
We experienced the same bug again but this time we are unable to delete any predicates from the node with the S P *. We recorded another video [here](https://www.youtube.com/watch?v=DmDc_K9mqHQ) demonstrating the issue. We are currently exporting the data set and we will send this data to @animesh2049 and @mangalaman93 for review. Thanks!

**Comment by rickytyho** [comment] 2019-10-21 10:51
@animesh2049 Hi Amimesh, this is happening to us quite frequently and is causing our application to break in many places. Have you narrowed down on the source of the bug?

**Comment by rickytyho** [comment] 2019-10-22 05:36
After more experimentation, we also suspect that the issue may originate from DGraph Ratel since we were unable to remove a predicate using Ratel's dashboard but were able to remove it using JS )(*sometimes).

**Comment by rickytyho** [comment] 2019-10-23 01:08
Thanks @pawanrawal for the patch. This issue first surfaced when we loaded data from the bulk loader, but it also occurred again when we tested it locally with newly generated data. Does this patch address the same issue from newly created data as well (maybe something to do with the immutable layer)? Thanks

**Comment by animesh2049** [comment] 2019-10-23 09:35
There is a [PR](https://github.com/dgraph-io/dgraph/pull/4204) ready for this. Will be fixed as soon as that is merged.

**Closed** 2019-10-23 22:19 UTC
Labels: kind/bug, priority/P0, status/accepted

**Comment by rickytyho** [comment] 2019-10-24 01:23
Hi @pawanrawal , is there a planned scheduled release for this update fix?

**Comment by campoy** [comment] 2019-10-24 05:57
This should be released with 1.1.1, scheduled to be released in a couple of weeks.

Alternatively, you could compile from source or use the dgraph/dgraph:master Docker image

**Comment by rickytyho** [comment] 2019-10-28 06:16
@campoy Thanks a lot! We'll try using dgraph/dgraph:master for now.

**Comment by rickytyho** [comment] 2019-10-28 07:28
@campoy @martinmr @pawanrawal Just pulled Dgraph's master image and the bug still seems to exist. We tried it again and we are able to repro.

**Comment by rickytyho** [comment] 2019-10-28 07:36
@campoy , Just realized that the image dgraph/dgraph:master was built over a month ago. Is there a more recent image that encompasses the bug fix? Becuase dgraph/dgraph:master still has the same bug for 4182

**Comment by martinmr** [comment] 2019-10-29 17:44
We have some issues with our release script because we just moved to to using go modules and the script does not work with it.

But I managed to build and push a new docker image with the `master` tag. Can you give it a try? It doesn't come with Ratel because I haven't managed to make the script work with it. Should you need ratel you can always run it on your workstatoin. Let me know if you can pull the new image.

**Comment by rickytyho** [comment] 2019-11-01 04:01
Thanks a lot @martinmr . Currently, we've actually built our own image of Dgraph using master repo, but we'll switch over to using dgraph/dgraph:master to see if that works as well.
