### ISSUE TITLE
cluster got stuck, 1 node is spamming with transactions list all the time

### ISSUE THREAD

**Issue by makitka2007** [dgraph-io/dgraph#3184] opened 2019-03-21 11:30 UTC
it happened on different env with dgraph 1.0.14-rc1
both 3 nodes don't run queries but respond on healthcheck.
one node is spamming every few minutes with such list of transactions: https://drive.google.com/file/d/1ePQ9ueiTlQoLzsl-UOMIjFoUMRwKBCVr/view?usp=sharing

restart of all nodes doesn't help, after restart one node is spamming with "Node blocks too long" (https://drive.google.com/file/d/1oYUegvz4chjoUUhKax0dD1WHOJ_-N2HN/view?usp=sharing), and all nodes in a cluster don't respond. and that another one from first log start posting transaction list again

also there are mutation activity in dgraph metrics and pending proposals on 1 node, but actually nothing is loading there.

unfortunately i can't share all logs because they take too much space due to large messages and datadog fails on exporting them.

maybe it happens because 1 node was failing on OOM all the time until we replaced 32Gb instances with 64Gb ones.
here are out of memory errors: https://drive.google.com/file/d/1iJzvoDnx8X-W-JkA5v4xABPJx9SJ0OhW/view?usp=sharing

dgraph metrics for last 15 mins:
https://drive.google.com/file/d/1DW7B1eGSRDmsz0pcY5RMCFrXLHUMvF1B/view?usp=sharing

**Comment by manishrjain** [comment] 2019-03-21 12:57
Looks like duplicate of #3183 . If proposals don't go through, then Raft logs won't get trimmed and can cause OOM issues on restart.

**Comment by manishrjain** [comment] 2020-04-09 21:14
Duplicate of #3183 .

**Closed by manishrjain** 2020-04-09 21:14 UTC
Labels: kind/bug, priority/P2

**Comment by manishrjain** [comment] 2020-04-09 21:15
Also, the tick missed to fire was fixed. It was due to heartbeats happening every 20ms, while Etcd uses 100ms. After switching to that, we didn't see that again.
