### ISSUE TITLE
after stop alpha has panic

### ISSUE THREAD

**Issue by relunctance** [dgraph-io/dgraph#2845] opened 2018-12-25 05:57 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph version   : v1.0.11-rc3-66-g4ca67ca
Commit SHA-1     : 4ca67ca
Commit timestamp : 2018-12-24 18:53:10 -0800
Branch           : dev
Go version       : go1.11

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?
64G

- Steps to reproduce the issue (command/config used to run Dgraph).
```shell
kill `ps auxwww | grep dgraph | grep config | grep alpha | awk -F" " '{print $2}'`
```
- Expected behaviour and actual result.

```
I1225 13:53:05.329582   20363 run.go:492] Caught Ctrl-C. Terminating now (this may take a few seconds)...
E1225 13:53:05.329712   20363 run.go:291] GRPC listener canceled: accept tcp 0.0.0.0:9080: use of closed network connection
E1225 13:53:05.329845   20363 run.go:310] Stopped taking more http(s) requests. Err: accept tcp 0.0.0.0:8080: use of closed network connection
I1225 13:53:05.332536   20363 run.go:505] GRPC and HTTP stopped.
I1225 13:53:05.332558   20363 worker.go:93] Stopping group...
I1225 13:53:05.333842   20363 run.go:449] Finished disposing server state.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xce0542]

goroutine 1 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*Closer).Signal(...)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/y.go:186
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y.(*Closer).SignalAndWait(0x0)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/y/y.go:207 +0x22
github.com/dgraph-io/dgraph/worker.BlockingStop()
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/worker/worker.go:94 +0x5f
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run()
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:506 +0xb60
github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.1.func1(0xc0001c8240, 0xc0006ac000, 0x0, 0x2)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:81 +0x52
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001c8240, 0xc0001b3980, 0x2, 0x2, 0xc0001c8240, 0xc0001b3980)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ee7380, 0x3, 0x0, 0x0)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ee7380, 0x8b414d, 0x1eef56c)
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:58 +0x36
main.main()
        /home/gaoqilin/gopath/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x88
```

**Comment by manishrjain** [comment] 2019-01-15 06:09
I'm unable to reproduce this.

**Comment by srfrog** [comment] 2019-01-15 23:55
I'm closing this issue re-open if you are able to reproduce it against the latest.

**Closed by srfrog** 2019-01-15 23:55 UTC
Labels: bug
