### ISSUE TITLE
Ratel dashboard freezes after pressing cmd + enter in Firefox

### ISSUE THREAD

**Issue by ondrowan** [dgraph-io/dgraph#2288] opened 2018-03-30 15:47 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

1.0.4

- Have you tried reproducing the issue with latest release?

Yes.

- What is the hardware spec (RAM, OS)?

MacOS, 16GB RAM

- Steps to reproduce the issue (command/config used to run Dgraph).

Press cmd + enter in query text field when using the latest Firefox (Firefox 59.0.2). It freezes the tab for few tens of seconds before showing the results. It doesn't happen in Safari or Chrome. It doesn't happen if I click "Run" manually.

- Expected behaviour and actual result.

Showing results without freezing the tab.

**Comment by MichelDiz** [comment] 2018-03-30 18:34
Well, technically this would be a browser problem. I use multiple browsers. Firefox always gives me problems. I have even Quantum and that is what most bug. I find it difficult to be Ratel. For it is made with ReactJS. And when compiled, it is compiled for JS compatible versions.

**Comment by ondrowan** [comment] 2018-04-09 13:51
I suddenly cannot reproduce this issue with the same versions of Dgraph and Firefox. Feel free to close this issue if you cannot reproduce it as well.

**Comment by gpahal** [comment] 2018-04-10 05:54
I'm closing this for now as I also cannot reproduce this.

**Closed by gpahal** 2018-04-10 05:54 UTC
Labels: ratel

**Comment by ondrowan** [comment] 2018-04-18 16:27
I think I found a way to reproduce it. When I have lots of queries opened in Ratel, it gets gradually slower and slower until I hit this issue. After I click "Close all", performance gets significantly better.

**Comment by ondrowan** [comment] 2018-04-18 16:27
@gpahal I think I found a way to reproduce it. When I have lots of queries opened in Ratel, it gets gradually slower and slower until I hit this issue. After I click "Close all", performance gets significantly better.
