### ISSUE TITLE
Facet keys merge functionality

### ISSUE THREAD

**Issue by coolguru** [dgraph-io/dgraph#2225] opened 2018-03-14 07:23 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.4

- Have you tried reproducing the issue with latest release?
yes

- What is the hardware spec (RAM, OS)?

- Steps to reproduce the issue (command/config used to run Dgraph).
What’s the best way to update facet on value node  
```_:alice <car> "MA0123" (since=2006-02-02T13:01:09, first=true) .```
update this to
```<0xUID> <car> "MA0123" ( first=false) .```
^^^ this mutation also deletes since facet key value. How can I  only update first facet key without deleting since facet key?

- Expected behaviour and actual result.
Should delete since facet key

**Comment by pawanrawal** [comment] 2018-03-15 02:28
Seems like a duplicate of https://github.com/dgraph-io/dgraph/issues/1996.

**Closed** 2018-03-16 04:31 UTC
