### ISSUE TITLE
Dgraph leader lost

### ISSUE THREAD

**Issue by ansham22** [dgraph-io/dgraph#1832] opened 2017-11-24 11:08 UTC
Queries to Dgraph were stucking. I tried to do rolling restart of nodes with leader at last. Leader lost and then Dgraph wan't able to select leader and all 3 nodes atrting their own election.

I thought the issue might be related to Zero. Tried rolling restart of zero too but same problem occurred. 1 out of 3 zero node crashed logs as below:--

google.golang.org/grpc/transport.newHTTP2Server.func1(0xc427336300)
    /home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:256 +0x5e
created by google.golang.org/grpc/transport.newHTTP2Server
    /home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:255 +0xe3f

goroutine 29919 [select]:
google.golang.org/grpc/transport.(*http2Server).keepalive(0xc427336300)
    /home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:951 +0x264
created by google.golang.org/grpc/transport.newHTTP2Server
    /home/travis/gopath/src/google.golang.org/grpc/transport/http2_server.go:259 +0xe64

Dgraph version:--- 0.9.2

**Comment by janardhan1993** [comment] 2017-11-28 03:53
This is duplicate of  #1827 and has been fixed in master.

**Closed by janardhan1993** 2017-11-28 03:53 UTC
Labels: investigate
