### ISSUE TITLE
Illegal instruction running docker image

### ISSUE THREAD

**Issue by fils** [dgraph-io/dgraph#75] opened 2016-04-26 11:33 UTC
Following the instructions to pull and start the docker image (docker pull dgraph/dgraph:latest).  Once inside I get:

root@8881830c7daf:/go# mkdir /dgraph/m
root@8881830c7daf:/go# server --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
Illegal instruction

Mac OS X 10.11.4

bash-3.2$ docker version
Client:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.1
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   d12ea79
 Built:        Thu Aug 13 02:49:29 UTC 2015
 OS/Arch:      linux/amd64

**Comment by pawanrawal** [comment] 2016-04-26 14:21
Hey @fils 

Could you share the command you are using to run the docker container. Could you try it once without mounting volumes?

**Comment by fils** [comment] 2016-04-26 20:18
@pawanrawal 

```
bash-3.2$ docker run -t -i -v /Users/dfils/Semantic/dgraph:/dgraph -p 80:8080 dgraph/dgraph:latest
root@9e947fabd8d1:/go# server --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
Illegal instruction
root@9e947fabd8d1:/go# exit
exit
```


```
bash-3.2$ docker run -t -i  -p 80:8080 dgraph/dgraph:latest
root@34d87b943f28:/go# server --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
Illegal instruction
root@34d87b943f28:/go# 
```

**Comment by manishrjain** [comment] 2016-04-27 01:36
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;r8YruYML&#x2F;49-fix-illegal-instruction-bug"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fix Illegal Instruction Bug</a>

**Comment by pawanrawal** [comment] 2016-04-27 02:42
@fils Could you try upgrading your Go version to 1.6 ? Instructions [here](https://golang.org/doc/install)

**Comment by manishrjain** [comment] 2016-04-27 04:57
Inside Docker, the Go version shouldn't make any difference.

@pawanrawal -- Did you try running it yourself? Can you put down your system specs?

**Comment by pawanrawal** [comment] 2016-04-27 05:05
Right @manishrjain. My bad, regardless this is the Go version Docker is written in and not the one on his machine.

@fils I ran this on my machine and could not reproduce the issue.
My docker version is 1.10.3

`docker version` command outputs the following for me.
```Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 21:49:11 2016
 OS/Arch:      linux/amd64
```
I see that your docker version is about six months old, how about upgrading it and then trying to run this.

**Comment by fils** [comment] 2016-04-27 13:06
@pawanrawal I updated and pulled the image again and get the same results

```
Fils:~ dfils$ docker version
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:13:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 19:36:04 2016
 OS/Arch:      linux/amd64
Fils:~ dfils$ docker run -t -i -v /Users/dfils/Semantic/dgraph:/dgraph -p 80:8080 dgraph/dgraph:latest
root@6f2280faedaa:/go# server --mutations /dgraph/m --postings /dgraph/p --uids /dgraph/u
Illegal instruction
root@6f2280faedaa:/go# 
```

**Comment by fils** [comment] 2016-04-27 13:08
@pawanrawal   I also tried it without my local volume mount and got the same results.

**Comment by pawanrawal** [comment] 2016-04-27 13:46
@fils - That's a bit strange. I am trying to reproduce this and will get back to you soon.

**Comment by pawanrawal** [comment] 2016-04-27 15:10
@fils 
I tried reproducing this on `Mac OS X 10.11.4`, with docker version `1.11.0` but couldn't reproduce this. 

I did a fresh install of Docker toolbox from [here](https://docs.docker.com/engine/installation/mac/#installation). How did you install Docker ?

**Comment by fils** [comment] 2016-04-27 15:50
@pawanrawal   I got the toolbox from the same location.   
Docker toolbox 1.11.0
Same OS version..  
I even wiped out my images and pulled down dgraph fresh...   

I did an apt get install on strace but doesn't look like trace is not the right tool in this case.  

Is this there some process monitoring tool or command I can use to get more details on what is going on the with the executable.

**Comment by fils** [comment] 2016-04-27 19:19
@pawanrawal 

I tried GDB  and got warning: Error disabling address space randomization: Operation not permitted

```
root@e287410fdc92:/go# gdb /go/bin/server 
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /go/bin/server...done.
warning: File "/usr/local/go/src/runtime/runtime-gdb.py" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
(gdb) run
Starting program: /go/bin/server 
warning: Error disabling address space randomization: Operation not permitted
During startup program terminated with signal SIGILL, Illegal instruction.
(gdb) 
```

**Comment by fils** [comment] 2016-04-27 21:39
@manishrjain @pawanrawal 

I set ulimit and was able to get a core file trying to run server

I attached the core file here.   Don't know if it will help, but thought I would pass it along.

[core.zip](https://github.com/dgraph-io/dgraph/files/239436/core.zip)

**Comment by pawanrawal** [comment] 2016-04-28 08:20
@fils 

I am still not sure what the problem is here, still trying to figure it out.
As the gdb error above says 
```
To enable execution of this file add
    add-auto-load-safe-path /usr/local/go/src/runtime/runtime-gdb.py
line to your configuration file "/root/.gdbinit".
``` 
Also see this https://sourceware.org/gdb/onlinedocs/gdb/Auto_002dloading-safe-path.html

Could you try this and run the binary with gdb again ?

**Comment by manishrjain** [comment] 2016-04-28 09:00
Actually, I get the same issue.

$ docker version
Client:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   76d6bc9
 Built:        Tue Nov  3 17:43:42 UTC 2015
 OS/Arch:      linux/amd64

$ docker run -i -t -p 8080:8080 dgraph/dgraph:latest
root@53380a2cb002:/go# server
Illegal instruction (core dumped)
root@53380a2cb002:/go# server --help
Illegal instruction (core dumped)
root@53380a2cb002:/go#

**Comment by manishrjain** [comment] 2016-04-28 09:50
I pushed out a new docker image. It now works on my machine. Can you give it a try, @fils?

Note that this is from the HEAD. The code and the way data was being stored have changed. So, you won't be able to use the posting list directories from `benchmarks` repository. You'll have to load data from scratch.

**Comment by fils** [comment] 2016-04-28 13:27
@manishrjain   I pulled the new version and it looks like it's running.   I have LOTS of RDF data I can plug into it so I will try that next.    I'll dig up the references for loading RDF and start seeing if I can build some GraphQL calls.  That's the fun part..

**Comment by manishrjain** [comment] 2016-05-03 23:54
I reckon this works now. So, closing the issue. Feel free to reopen if you encounter more issues.

**Closed by manishrjain** 2016-05-03 23:54 UTC
Labels: bug
