### ISSUE TITLE
After edge filtering, scalar predicate filtering is too slow

### ISSUE THREAD

**Issue by coralzu** [dgraph-io/dgraph#3945] opened 2019-09-09 08:26 UTC
### What version of Dgraph are you using?
 v1.0.14
### Have you tried reproducing the issue with the latest release?
yes . 

### What is the hardware spec (RAM, OS)?
8GB RAM  , Windows 10

### Steps to reproduce the issue (command/config used to run Dgraph).
**1、start dgraph**
```
dgraph zero --my=localhost:5081 -o=1 
dgraph alpha --lru_mb 1024 --badger.tables ram --my=localhost:7081 --zero=localhost:5081 -o=1
```
**2、add data**
Create 10 nodes with name predicates, 10 nodes with code predicates, and connect them with UID predicates. Then create 1 million isolated nodes containing code predicates (the value of code predicates is the same as the first 10 nodes).
i use dgraph4j to add data, My code like this
```
// set schema
        DgraphProto.Operation op = DgraphProto.Operation.newBuilder()
                .setSchema(" name : string @index(hash) . \n code : string @index(hash) . \n link : uid @reverse .").build();
        dgraphClient.alter(op);
        // add data
        // Create 10 predicate names and 10 predicate codes and connect them using uid predicate link .
        StringBuilder sb = new StringBuilder();
        for (int x = 0; x < 10; x++) {
            sb.append(" _:name").append(x).append(" <name> \"name").append(x).append("\" . \n")
                    .append(" _:code").append(x).append(" <code> \"code").append(x).append("\" . \n")
                    .append(" _:name").append(x).append(" <link> _:code").append(x).append(" . \n");
        }
        DgraphProto.Mutation mu = DgraphProto.Mutation.newBuilder().setSetNquads(ByteString.copyFromUtf8(sb.toString()))
                .setCommitNow(true).build();
        dgraphClient.newTransaction().mutate(mu);
        // Create 1 million predicate codes ,No connection
        sb.delete(0, sb.length());
        for (int x = 10; x < 1000000; x++) {
            sb.append(" _:code").append(x).append(" <code> \"code").append((int)(Math.random()*10+1)).append("\" . \n");
            if (x % 50000 == 0) {
                DgraphProto.Mutation mu1 = DgraphProto.Mutation.newBuilder().setSetNquads(ByteString.copyFromUtf8(sb.toString()))
                        .setCommitNow(true).build();
                dgraphClient.newTransaction().mutate(mu1);
                sb.delete(0, sb.length());
            }
        }
```
**3、Starting from the name node, the associated code node is queried by uid predicate and filtered by value.**
this moment, the code node find only one,but the filter is too slow,my query like this
```
{
  aa(func:eq(name,"name1")){
     link @filter(eq(code,"code1")) {
       code
    }
  } 
}
```
then , i modify my query to use value variables for filtering,like this
```
{
  var(func:eq(name,"name1")){
    a as link {
      b as code
    }
  }
  
  body(func:uid(a)) @filter(eq(val(b),"code1")) {
    code 
  }
}
```
Response time has been greatly accelerated.Tests in version 1.0.14 are as follows.
![1](https://user-images.githubusercontent.com/45164615/64511088-22513780-d316-11e9-8c9d-844652501184.png)
![2](https://user-images.githubusercontent.com/45164615/64511100-28471880-d316-11e9-9dd1-fee765ae2809.png)

This situation also exists in V1.1.0 version, but it is not so obvious. Here is my test in V1.1.0 version.
![4](https://user-images.githubusercontent.com/45164615/64511454-ec608300-d316-11e9-949b-16f30ad45faf.png)
![3](https://user-images.githubusercontent.com/45164615/64511463-f5515480-d316-11e9-8494-118e5d7561fd.png)

### Expected behaviour and actual result.
I think that using filters directly after uid predicates should be consistent with using variables to filter , and there are many examples in official documents. 

For this reason, I have modified the query in my project to the second way mentioned above, and in the case of multiple filters in a query, I used a lot of variable blocks, which should not be reasonable. Queries I completed like this.
```
 { var(func:eq(jck_fw_jcxx_fj.tydzbm,"5501070011170800010002313")) { 
      process0 as uid 
      variable0 as jck_fw_jcxx_fj.syqk} 
 
 var(func:uid(process0)) @filter(( eq(val(variable0),"02")  or  eq(val(variable0),"01") )){ 
     result as ~frzcdlink { 
    variable1 as jck_fr_jcxx.frlb}} 
 
 total(func:uid(result)) @filter(( eq(val(variable1),"91")  or  eq(val(variable1),"92") )){ total : count(uid) } 
 
 body(func:uid(result),first:10,offset:0)  @filter(( eq(val(variable1),"91")  or  eq(val(variable1),"92") )) { expand(_all_) } }
```

by the way. When I wrote the above query, I found two problems with this approach.

**1、When using value variable filtering, multiple filtering conditions are only the first to take effect. This problem also exists in official document examples.**
[https://docs.dgraph.io/query-language/#inequality](url)
![5](https://user-images.githubusercontent.com/45164615/64512496-27fc4c80-d319-11e9-863e-540ca164a4ff.png)
![6](https://user-images.githubusercontent.com/45164615/64512509-2c286a00-d319-11e9-9ee3-52eb036ab133.png)

That's why the above value variable filtering uses a lot of or .

**2、Value variable filtering does not support alloftext.**
I wanted to replace the query in my other project in the same way, but found alloftext could not be applied when using value variable filtering.
![7](https://user-images.githubusercontent.com/45164615/64513210-98f03400-d31a-11e9-9ed8-715b09ed8074.png)

Is this a bug? Or is my use incorrect? If it's a bug, are you considering fixing it in a later version?

**Comment by campoy** [comment] 2019-09-13 15:46
Thanks for the very detailed report, @coralzu !
This seems related to #2713.

Could someone confirm?

**Comment by coralzu** [comment] 2019-09-16 01:40
Thank you very much for your reply.

I will look forward to the next release here.

**Comment by campoy** [comment] 2019-09-17 15:46
Ok, I'll close this issue as a duplicate of #2713. Thanks for the report!

**Closed by campoy** 2019-09-17 15:46 UTC
Labels: area/performance, exp/expert, kind/bug, status/accepted
