### ISSUE TITLE
error during query: readTs value less than minTs value

### ISSUE THREAD

**Issue by mpires** [dgraph-io/dgraph#2326] opened 2018-04-10 13:36 UTC
- What version of Dgraph are you using?
1.0.4 nightly (98c6102), also tried releases 1.0.3 and 1.0.4

- Have you tried reproducing the issue with latest release?
[I have, with the same erroneous results](https://discuss.dgraph.io/t/readts-x-less-than-mints-y-for-key-during-query/2415).

- What is the hardware spec (RAM, OS)?
3 GCE instances (4 vCPUs, 20 GB, 30GB SSD)

- Steps to reproduce the issue (command/config used to run Dgraph).
A fresh dgraph installation with the `p` folder that I sent privately to @pawanrawal 
And the following query:
```
{ranges(func:eq(view,"c4c97e30-87b1-11e7-bf97-a71a48b50a2d")) { xid }}
```
- Expected behaviour and actual result.
While some queries do work, the predicate `view` for certain keys (such as the above) seems corrupt, giving out the error `readTs: <X> less than minTs: <X+Y>`

**Comment by pawanrawal** [comment] 2018-04-11 06:28
Do you have the logs from the three Zero servers by any chance?

**Comment by aditya-pr** [comment] 2018-04-11 16:05
getting same error after increased mutation rate for a while.

**Comment by akshaydeo** [comment] 2018-04-30 10:12
This is not temporary! Once it starts coming, it keeps on coming for all the read and write transactions. Could you please look into it?

**Comment by willcj33** [comment] 2018-05-25 01:14
I am getting this issue as well. Just wanted to chime in. Its when I have a very high load of mutations flowing though.

**Comment by willcj33** [comment] 2018-05-25 01:46
Yes, I am on 1.0.5. It's definitely under high load. Is it something I can just retry after a backoff? I mean ive written like 100k events which is a alot of mutations per single event, in less than 1 hour, and I only got this error like twice. Also, we don't have alot of ram or cpu on our 5 machines we are testing with right now, if that matters.

**Comment by manishrjain** [comment] 2018-05-25 01:47
Yeah, it's a temporary error. You can just retry with a backoff.

**Comment by manishrjain** [comment] 2018-06-14 01:35
@akshaydeo : Can you retry from master, and check if you still see this error? Again, seeing this temporarily under high load is OK, what we're looking for is if you can't get out of this error even after the mutations stop.

**Comment by akshaydeo** [comment] 2018-06-14 02:19
This works for me now. I had to add a few retries in case of failures.

**Comment by manishrjain** [comment] 2018-06-14 02:20
Cool. Closing it then.

**Closed by manishrjain** 2018-06-14 02:20 UTC
Labels: bug, verify-fix

**Comment by mehdiym** [comment] 2018-09-21 12:47
Hello,
I do have such errors when doing massive parallel queries and mutations, but I don't know how to handle it: How can I know when I deal with that error and not other kind of errors?
I'd like to do a retry only when it's that error and return the error in other cases.
It would be great to have a dedicated error type for that.
Thanks.

**Comment by cocodrino** [comment] 2019-01-03 01:21
hi guys, I just wanted to say that yesterday I installed dgraph, I'm doing the tutorial, I'm just going through the second part and I'm already getting this same error, so it can't just be due to a high load.

I did the installation with the script that appears in the installation section, please if you require any log or any additional information do not hesitate to ask me, indicating the route and I will gladly send them ...

**Comment by danielmai** [comment] 2019-01-03 03:33
@cocodrino can you share steps to reproduce what you're seeing? Are you re-using any existing data (the p, w, and zw directories) when running Dgraph for the Tour? My guess is that Zero's zw directory was newly created while using existing Alpha's p and w directories.

Sharing the logs from Zero and Alpha would help.
