### ISSUE TITLE
panic: assignment to entry on nil map

### ISSUE THREAD

**Issue by campoy** [dgraph-io/dgraph#3885] opened 2019-08-30 00:26 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

v1.1.0-rc3

- Have you tried reproducing the issue with latest release?

yes

- What is the hardware spec (RAM, OS)?

Debian cloud instance on GCP

- Steps to reproduce the issue (command/config used to run Dgraph).

Not sure how to reproduce it, I was loading the data in the attached file after a `DROP ALL` and got the panic.

Once I restarted the alpha it paniced again once, then it started correctly.

Panic logs:

```
panic: assignment to entry in nil map

goroutine 3836 [running]:
github.com/dgraph-io/dgraph/posting.(*List).updateMutationLayer(0xc009827f20, 0xc021b17c20)
        /tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:318 +0x232
github.com/dgraph-io/dgraph/posting.(*List).addMutationInternal(0xc009827f20, 0x1945020, 0xc0093a4f80, 0xc0093a5700, 0xc00aef8500, 0x22b7200, 0xbf5238d24accf928)
        /tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:439 +0xb1
github.com/dgraph-io/dgraph/posting.(*Txn).addMutationHelper(0xc0093a5700, 0x1945020, 0xc0093a4f80, 0xc009827f20, 0x0, 0xc00aef8500, 0xc000000000, 0x0, 0x0, 0xc000040000, ...)
        /tmp/go/src/github.com/dgraph-io/dgraph/posting/index.go:361 +0x205
github.com/dgraph-io/dgraph/posting.(*List).AddMutationWithIndex(0xc009827f20, 0x1945020, 0xc0093a4f80, 0xc00aef8500, 0xc0093a5700, 0x0, 0x0)
        /tmp/go/src/github.com/dgraph-io/dgraph/posting/index.go:394 +0x11e
github.com/dgraph-io/dgraph/worker.runMutation(0x1945020, 0xc0093a4f80, 0xc00aef8500, 0xc0093a5700, 0x0, 0x0)
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/mutation.go:115 +0x35d
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func3(0xc00aef6468, 0x1cb, 0x373, 0xc0237a8340, 0xc022b9aa00)
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:284 +0xb1
github.com/dgraph-io/dgraph/worker.(*node).applyMutations.func4(0xc009827e60, 0xc021e6b6b0, 0xc013c3a7e0, 0xc8d, 0xe58)
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:313 +0x7d
created by github.com/dgraph-io/dgraph/worker.(*node).applyMutations
        /tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:312 +0x9a7
```

- Expected behaviour and actual result.

It should work
[pokedex.json.txt](https://github.com/dgraph-io/dgraph/files/3570399/pokedex.json.txt)

**Comment by gitlw** [comment] 2019-08-30 18:13
I tried a couple of things, including forcing a snapshot & rollup followed by a mutation with deletion that can go through the code in the stacktrace, but still couldn't reproduce the bug.

Also the data you attached has this
```"type": [                                                                                                                                      
        "Normal",                                                                                                                                    
        {                                                                                                                                            
          "uid": "_:Flying",                                                                                                                         
          "name": "Flying"                                                                                                                           
        }                                                                                                                                            
      ]```
and when I manually sent the type of "type" to [uid], dgraph complains it cannot accept the string "Normal".

**Comment by danielmai** [comment] 2019-08-30 19:04
@campoy what client were you using to send this mutation?

**Comment by campoy** [comment] 2019-09-03 14:25
I was sending the query with `curl`.

**Comment by manishrjain** [comment] 2019-09-03 19:53
Should be fixed by my change above.

**Closed by manishrjain** 2019-09-03 19:53 UTC
Labels: area/crash, kind/bug, priority/P0, status/accepted
