### ISSUE TITLE
Unable to search for predicate@lang data using expand(_forward_)

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/dgraph#4063] opened 2019-09-26 03:08 UTC
**- What version of Dgraph are you using?**

    Dgraph version   : v1.1.0  
    Dgraph SHA-256   : 
    7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
    Commit SHA-1     : ef7cdb28
    Commit timestamp : 2019-09-04 00:12:51 -0700
    Branch           : HEAD
    Go version       : go1.12.7
**- Have you tried reproducing the issue with latest release?**

    Yes
**- What is the hardware spec (RAM, OS)?**

    Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz ，linux， 128G
**- Steps to reproduce the issue (command/config used to run Dgraph).**

    {
        node(func: uid(0x2a737d0)) {
            uid
            expand(_all_)
        }
        me(func: uid(0x2a737d0)) {
            uid
            expand(_forward_)
        }
    }

**- Expected behaviour and actual result.**

Query result is:
    
    {
    "data": {
    "node": [
      {
        "uid": "0x2a737d0",
        "schemaorg:sameAs": [
          "https://www.wikidata.org/wiki/Q54182735",
          "https://en.wikipedia.org/wiki/Ben_Harvey_(Australian_radio_personality)"
        ],
        "schemaorg:description|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:description|sourceName": "google",
        "schemaorg:name|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:name|sourceName": "google",
        "schemaorg:name@en": "Ben Harvey",
        "schemaorg:name@ast": "Ben Harvey",
        "schemaorg:name@es": "Ben Harvey",
        "schemaorg:name@nl": "Ben Harvey",
        "schemaorg:name": "本·哈维",
        "schemaorg:disambiguatingDescription|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:disambiguatingDescription|sourceName": "google",
        "schemaorg:disambiguatingDescription": "电台主持人"
      }
    ],
    "me": [
      {
        "uid": "0x2a737d0",
        "schemaorg:disambiguatingDescription|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:disambiguatingDescription|sourceName": "google",
        "schemaorg:disambiguatingDescription": "电台主持人",
        "schemaorg:description|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:description|sourceName": "google",
        "schemaorg:sameAs": [
          "https://www.wikidata.org/wiki/Q54182735",
          "https://en.wikipedia.org/wiki/Ben_Harvey_(Australian_radio_personality)"
        ],
        "schemaorg:name|source": "https://www.google.com.hk/search?q=%E5%88%A9%E4%BA%9A%E5%A7%86%C2%B7%E6%96%AF%E7%89%B9%E6%99%AE%E5%B0%94%E9%A1%BF+%E6%9C%AC%C2%B7%E5%93%88%E7%BB%B4&hl=zh-cn&lr=zh-cn&safe=high&stick=H4sIAAAAAAAAAONgFuLVT9c3NEzPKEo2ybaoVIJw08xMzCtNKgq0-AJSi4rz84IzU1LLEyuLF7GqPe1Y-WTXrKfL2w5tfzZt_fPOnc9mrnu6YcrLhfsVns1Zc2j708kdz3dvAQCNn54tWQAAAA",
        "schemaorg:name|sourceName": "google",
        "schemaorg:name": "本·哈维",
      }
    ]
    },
    "extensions": {
    "server_latency": {
      "parsing_ns": 19757,
      "processing_ns": 28568961,
      "encoding_ns": 258632,
      "assign_timestamp_ns": 436561
    },
    "txn": {
      "start_ts": 195
    }
	}
    }

Use expand(_all_) to search for schemaorg:name@en, schemaorg:name@es, etc., but use expand(_forward_) to search only schemaorg:name。Dgraph1.0.15 uses expand(_forward_) to search for schemaorg:name@en, schemaorg:name@es, etc.

The issue tracker is not for questions.

If you have a question, please ask it on https://discuss.dgraph.io
Our Docs: https://docs.dgraph.io/
Slack Channel: https://slack.dgraph.io/

**Comment by animesh2049** [comment] 2019-09-26 14:03
I am able  to reproduce this issue. I ran below query on play.
```
{
  me(func: uid(0xe)) {
    uid
    expand(_all_)
  }
}
```
output of this query is 
```
{
  "data": {
    "me": [
      {
        "uid": "0xe",
        "name@ne": "संयुक्त राज्य अमेरिका",
        "name@en": "United States of America",
        "name@fi": "Yhdysvallat",
        "name@zh": "美国",
        "name@hu": "Amerikai Egyesült Államok",
        "name@sl": "Združene države Amerike",
        "name@da": "USA",
        "name@ca": "Estats Units d'Amèrica",
        "name@ko": "미국",
        "name@pt": "Estados Unidos",
        "name@no": "USA",
        "name@ms": "Amerika Syarikat",
        "name@th": "สหรัฐอเมริกา",
        "name@cs": "Spojené státy americké",
        "name@tr": "Amerika Birleşik Devletleri",
        "name@hr": "Sjedinjene Američke Države",
        "name@eo": "Usono",
        "name@es": "Estados Unidos",
        "name@sk": "Spojené štáty americké",
        "name@hi": "संयुक्त राज्य अमेरिका",
        "name@nl": "Verenigde Staten",
        "name@it": "Stati Uniti d'America",
        "name@fa": "ایالات متحدهٔ آمریکا",
        "name@vi": "Hoa Kỳ",
        "name@ru": "Соединённые Штаты Америки",
        "name@fr": "États-Unis",
        "name@ja": "アメリカ合衆国",
        "name@ro": "Statele Unite ale Americii",
        "name@uk": "Сполучені Штати Америки",
        "name@id": "Amerika Serikat",
        "name@iw": "ארצות הברית",
        "name@lt": "Jungtinės Amerikos Valstijos",
        "name@zh-Hant": "美國",
        "name@sr": "Сједињене Америчке Државе",
        "name@fil": "Estados Unidos",
        "name@el": "Ηνωμένες Πολιτείες Αμερικής",
        "name@sv": "USA",
        "name@pl": "Stany Zjednoczone",
        "name@ar": "الولايات المتحدة",
        "name@es-419": "Estados Unidos",
        "name@bg": "Съединени американски щати",
        "name@et": "Ameerika Ühendriigid",
        "name@lv": "Amerikas Savienotās Valstis",
        "name@de": "Vereinigte Staaten von Amerika"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 8464,
      "processing_ns": 434557,
      "encoding_ns": 48958
    },
    "txn": {
      "start_ts": 20001
    }
  }
}
```

For `_all_` we are getting all the predicates but when I run with `_forward_` or `_reverse_` it doesn't give any output.

Query with `_reverse_` :
```
{
  me(func: uid(0xe)) {
    uid
    expand(_reverse_)
  }
}
```
Response:
```
{
  "data": {
    "me": [
      {
        "uid": "0xe"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 7892,
      "processing_ns": 200307,
      "encoding_ns": 4413
    },
    "txn": {
      "start_ts": 20001
    }
  }
}
```
Query with `_forward_`:
```
{
  me(func: uid(0xe)) {
    uid
    expand(_forward_)
  }
}
```
Response: 
```
{
  "data": {
    "me": [
      {
        "uid": "0xe"
      }
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 9325,
      "processing_ns": 381029,
      "encoding_ns": 8072
    },
    "txn": {
      "start_ts": 20001
    }
  }
}
```

**Comment by animesh2049** [comment] 2019-09-27 13:27
I think your query isn't correct. Can you try the below query?
```
me(func: uid(0x2a737d0)) {
    uid
    expand(_forward_) {
        expand(_all_)
    }
}
```

**Comment by martinmr** [comment] 2019-09-27 17:19
This is something I ran into a couple weeks ago. Right now, language predicates are only expanded when using `expand(_all_)` but not `expand(_forward_)` or `expand(_reverse_)`.

I am not sure if it's a bug because the code makes it clear to only look for lang predicates when `_all_` is used but I agree it's not what I expected to happen.

**Comment by campoy** [comment] 2019-09-27 23:24
I could reproduce the error in v1.1.0

Given this schema:

```rdf
<name>: string @lang .

type Fruit {
  name: string
}
```

```graphql
{
  q(func: type(Fruit)) {
    expand(_all_)
  }
}
```

returns

```json
{
  "data": {
    "q": [
      {
        "name@en": "apple",
        "name@ca": "poma",
        "name@es": "manzana",
        "name@fr": "pomme"
      }
    ]
  }
}
```

while using `_forward_`:

```graphql
{
  q(func: type(Fruit)) {
    expand(_forward_)
  }
}
```

returns nothing:

```json
{
  "data": {
    "q": []
  }
}
```

## Regression

This is actually a regression from v1.0.x.

Given this schema:

```rdf
<name>: string @lang .
```

and this dataset

```rdf
{
  set {
    _:a <name> "apple"@en .
    _:a <name> "pomme"@fr .
    _:a <name> "poma"@ca .
    _:a <name> "manzana"@es .
  }
}
```

running this query:

```graphql
{
  q(func: has(name@.)) {
    expand(_all_)
  }
}
```

returns for v1.0.17:

```json
{
  "data": {
    "q": [
      {
        "name@en": "apple",
        "name@ca": "poma",
        "name@es": "manzana",
        "name@fr": "pomme"
      }
    ]
  }
}
```

**Comment by martinmr** [comment] 2019-10-08 22:33
Since we are removing `_forward_` and `_predicate_` I am closing this issue. Going forward `_all_` and the expand by type will include all the language-tagged values.

**Closed by martinmr** 2019-10-08 22:33 UTC
Labels: area/querylang, kind/bug, priority/P2, status/accepted
