### ISSUE TITLE
Full Text Search topic from docs has issue with fulltext indexing in "name" predicate

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/dgraph#2669] opened 2018-10-17 02:08 UTC
```
curl localhost:8080/query -XPOST -d '
{
  movie(func:alloftext(name@en, "the man maybe runs")) {
	 name@en
  }
}' | python -m json.tool | less
              
```

### Response
```
{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Attribute name is not indexed with type fulltext"
    }
  ],
  "data": null
}
```

**Comment by danielmai** [comment] 2018-12-13 01:47
Will be fixed once we run v1.0.11 on play and update the release.schema file with the `fulltext` index.

I did a test with v1.0.11-rc4 and the [release data and schema](https://github.com/dgraph-io/benchmarks/tree/master/data/release) with the `name` set with the fulltext index. I don't get any results when querying for `"the man maybe runs"`. But there are results when querying for `"the man runs"`. Our  [full-text docs](https://docs.dgraph.io/query-language/#full-text-search) say that `"maybe"` is ignored since it's a stop word.

Is `maybe` no longer considered a stop word? Has it ever been a stop word? I took a look at the stop word list at https://github.com/blevesearch/bleve/tree/master/analysis/lang/en and didn't find "maybe" listed. @srfrog Any idea why the current query doesn't return results and should we update the example query without "maybe"?

**Comment by srfrog** [comment] 2018-12-19 03:39
It seems "maybe" used to be a stopword, from old the generated list:
https://github.com/dgraph-io/dgraph/blob/v1.0.8/tok/stopwords.go#L20

The current list is based from http://snowballstem.org/ (Porter-Stemmer)

The index might need to be rebuilt to use the right values. I edited the example query and asked for the schema and I didn't see a fulltext index for `name`.

```
      {
        "predicate": "name",
        "type": "string",
        "index": true,
        "tokenizer": [
          "hash",
          "term",
          "trigram"
        ],
        "lang": true
      },
```

**Comment by MichelDiz** [comment] 2019-01-09 18:14
are We Already on v1.0.11 in play Dgraph?
I just tested and the error is still occurring.

We need to add fulltext to name predicate.

```
schema{}
{
        "predicate": "name",
        "type": "string",
        "index": true,
        "tokenizer": [
          "hash",
          "term",
          "trigram"
        ],
        "lang": true
      }

```


```
{
  movie(func:alloftext(name@en, "the")) {
	 name@en
  }
}

{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Attribute name is not indexed with type fulltext"
    }
  ],
  "data": null
}
```

```
{
  movie(func:alloftext(name@en, "the man runs")) {
	 name@en
  }
}

"errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Attribute name is not indexed with type fulltext"
    }
  ],
  "data": null
}
```
```
{
  movie(func:alloftext(name@en, "the man maybe runs")) {
	 name@en
  }
}

{
  "errors": [
    {
      "code": "ErrorInvalidRequest",
      "message": ": Attribute name is not indexed with type fulltext"
    }
  ],
  "data": null
}
```

**Comment by danielmai** [comment] 2019-01-09 21:49
We're running v1.0.11 on play.dgraph.io but did not update the schema with the full text index.

**Comment by danielmai** [comment] 2019-01-09 22:10
https://play.dgraph.io is now running with the fulltext index for the name predicate.

**Comment by danielmai** [comment] 2019-01-21 22:34
> the query should return something still. If it doesn't then it's a possible bug. Even "maybe runs" should work.

@srfrog, play.dgraph.io does not return anything for "maybe runs". Is that the expected behavior? There's no movie in the data set with a name that contains both "maybe" and "runs".

**Comment by srfrog** [comment] 2019-01-21 22:42
Yes, "maybe" is not a stopword. So it's searching for movies with "maybe" AND "run" in the name.

Options:
1- Remove "maybe" from the search, or,
2- Use `anyoftext()` instead (slow).

**Closed** 2019-01-21 23:08 UTC
Labels: documentation

**Comment by danielmai** [comment] 2019-01-21 23:09
Cool. The docs now use `alloftext(name@en, "the dog which barks")` as the example. Thanks, Gus.
