### ISSUE TITLE
min, max: Support more than two arguments

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#1050] opened 2017-06-13 06:33 UTC
Version: 0.7.7

---

When aggregating using `min` or `max`, as a user I would like to do the following:

    max(v1, v2, v3)

rather than

    max(max(v1, v2), v3)

Therefore it might be useful if `min` and `max` supported more than two arguments.

Use case: https://gist.github.com/sungwoncho/ddba3a287ad87288331c493c2de5a5cb#file-get_active_answers

-------

Dataset:

[dgraph-1-2017-07-10-18-51.rdf.gz](https://github.com/dgraph-io/dgraph/files/1134923/dgraph-1-2017-07-10-18-51.rdf.gz)
[dgraph-schema-1-2017-07-10-18-51.rdf.gz](https://github.com/dgraph-io/dgraph/files/1134924/dgraph-schema-1-2017-07-10-18-51.rdf.gz)

Query:

```
# You might need to change the value of id
{
  var (id: 0xd18499a5ac49c3a6) {
    Has.Answer {
      answerTs as Timestamp
      ~Post {
        historyTs as Timestamp
      }
      Comment {
        commentTs as Timestamp
      }
      commentTsMax as max(var(commentTs))
      historyTsMax as max(var(historyTs))
      lastActive as math(max(max(answerTs, commentTsMax), historyTsMax))
      # The following line should work, if replaced with the above line
      # lastActive as math(max(answerTs, commentTsMax, historyTsMax))
    }
  }

  question(id: 0xd18499a5ac49c3a6) {
    Has.Answer(orderdesc: var(lastActive)) {
      Body {
        Text
      }
    }
  }
}
```

**Comment by ashwin95r** [comment] 2017-07-03 02:23
Ping, @abhishekgahlot . Are you still on it?

**Comment by abhishekgahlot** [comment] 2017-07-03 18:49
@ashwin95r Yes, I am still working on this. Will give update soon.

**Comment by kshitij10496** [comment] 2018-02-02 08:08
@pawanrawal Would it be fine if I give this a try?

**Comment by pawanrawal** [comment] 2018-02-02 08:09
Sure, go ahead and give it a try @kshitij10496.

**Comment by martinmr** [comment] 2019-02-04 22:47
Update: I tried working on this and I got some basic math expressions to work with min and max using more than two arguments. However, there are some bugs in the parser that are caused by the need of knowing exactly how many arguments a function needs. Since this is a very basic assumption, I would need to rework the entire parser, which requires a lot more work than I initially thought.

**Comment by srfrog** [comment] 2019-02-12 04:54
@sungwoncho and @martinmr see the attached PR for a possible solution. Thx

**Comment by srfrog** [comment] 2019-02-13 03:43
I have extended the PR to include all binary operations: `min()`, `max()`, `logbase()`, `pow()`. Feel free to test it out.

**Comment by martinmr** [comment] 2019-07-23 19:16
Assigning to @pawanrawal to see if he has better luck with this than Gus and I did.

**Comment by minhaj-shakeel** [comment] 2020-07-20 19:09
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8404). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Closed** 2020-07-21 04:54 UTC
Labels: area/parsing, area/querylang, exp/expert, kind/enhancement, status/accepted
