### ISSUE TITLE
Exported rdf file not bulk loadable

### ISSUE THREAD

**Issue by whus6207** [dgraph-io/dgraph#2167] opened 2018-02-26 21:33 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.3

- Have you tried reproducing the issue with latest release?
We are using the latest release

- What is the hardware spec (RAM, OS)?
24G RAM
Ubuntu 16.04 x86_64 8 cores

- Steps to reproduce the issue (command/config used to run Dgraph).
Export data from a dgraph instance containing nodes with empty string and names
```
curl localhost:8080/admin/export
```
Ungzip and bulk load to a new dgraph zero
```
dgraph bulk -r dgraph-1-2018-02-21-20-40.rdf -s dgraph-1-2018-02-21-20-40.schema --map_shards=2 --reduce_shards=1 --http localhost:8000 --zero localhost:5080
```

- Expected behaviour and actual result.
Expect rdf to be loaded without issue, but actually get couple of errors including: 
```
2018/02/26 18:03:01 while lexing <_:uida273c7> <name> "FAAP SEMINÁRIOS E PALESTRAS\x00"^^<xs:string> .: Invalid escape character : 'x' in literal
while parsing line "<_:uida273c7> <name> \"FAAP SEMINÁRIOS E PALESTRAS\\x00\"^^<xs:string> ."
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).parseRDF
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:180
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:133
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).mapStage.func1
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:219
runtime.goexit
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337

github.com/dgraph-io/dgraph/x.Wrap
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:79
github.com/dgraph-io/dgraph/x.Check
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/x/error.go:41
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*mapper).run
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/mapper.go:133
github.com/dgraph-io/dgraph/dgraph/cmd/bulk.(*loader).mapStage.func1
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/dgraph/cmd/bulk/loader.go:219
runtime.goexit
        /home/travis/.gimme/versions/go1.9.2.linux.amd64/src/runtime/asm_amd64.s:2337
```
or
```
MAP 38s rdf_count:1.656M rdf_speed:42.90k/sec edge_count:3.311M edge_speed:85.80k/sec
MAP 39s rdf_count:1.774M rdf_speed:44.81k/sec edge_count:3.548M edge_speed:89.62k/sec
2018/02/26 18:22:14 RDF doesn't match schema: Input for predicate name of type scalar is uid
```
Which is caused by line like: `<_:uidf1f8b> <name> _:uidffffffffffffffff .`
We were able to fix it by removing all forward/backward slashes and replacing  `_:uidffffffffffffffff` with `""^^<xs:string>`

**Comment by pawanrawal** [comment] 2018-03-01 02:45
I have been able to reproduce the issue about the null-terminated string. The issue can be reproduced by sending the following JSON input.
```
{"name":"FAAP SEMINÁRIOS E PALESTRAS\u0000"}
```

I am working on a fix for this issue and am also trying to reproduce the other issue.

**Comment by pawanrawal** [comment] 2018-03-11 22:23
> Which is caused by line like: <_:uidf1f8b> <name> _:uidffffffffffffffff .

I was able to reproduce this issue. It can be reproduced by performing the following operations on an empty instance.

```
{
  set {
    _:n <first> "" .
  }
}
```

followed by a schema alter:

````
first: string .
````

It was caused because we were ignoring a Posting with empty value while doing rollup. It should be fixed by 03836c8552a9f25d375e75fcdccbde50c4735655.

**Closed by pawanrawal** 2018-03-11 22:23 UTC
Labels: bug

**Comment by manishrjain** [comment] 2018-03-12 21:18
Nice find and fix!

**Comment by tamethecomplex** [comment] 2018-04-17 20:08
@pawanrawal , FYI, when I export one of my instances using the current master, I have the same issue as above... e.g. this content is in my export:

```
<_:uid27d9> <Description> _:uidffffffffffffffff .
<_:uid11262> <Description> ""^^<xs:string> .
<_:uid113ad> <Description> ""^^<xs:string> .
```

Is this because there is old corrupt data in my instance, or does this reflect an issue still in master?

**Comment by pawanrawal** [comment] 2018-04-17 23:47
Yeah, this should be because you have old data. For now, you would have to manually change it. This issue should not occur in master.
