### ISSUE TITLE
Disappearing edges

### ISSUE THREAD

**Issue by emadsamir** [dgraph-io/dgraph#2193] opened 2018-03-06 00:32 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using? 1.0.3

- Have you tried reproducing the issue with latest release? yes

- What is the hardware spec (RAM, OS)? 8GB, LINUX

- Steps to reproduce the issue (command/config used to run Dgraph).
quads := fmt.Sprintf(<%s> * * ., node_id)
if parent_id != nil {
quads += fmt.Sprintf("\n<%s> <%s> <%s> .", parent_id, edge, node_id)
}
_, err := txn.Mutate(bgctx, &api.Mutation{
CommitNow: true,
DelNquads: byte(quads),
})

- Expected behaviour and actual result.
after that, parent_id, will not show any edge references to other nodes until you create a new one, which tells me that they are not deleted but only sort of hidden.

**Comment by pawanrawal** [comment] 2018-03-06 00:33
This is not a complete example. It would be really helpful if your example is a program/test which shows all the queries and mutations. @emadsamir can you please modify it to have this information?

**Comment by emadsamir** [comment] 2018-03-06 00:34
this is description i put on the forum:
I am just wondering if you are aware that when you delete a predicate on a parent node, that causes all the other predicates to not show until a new one is created.
for example given:
<1> p <2>
<1> p <3>
<1> p <4>

delete{
<1> p <3> .
}

then!
<1> p <2>
<1> p <4>
no longer recongized

until you create a new
<1> p <5>

**Comment by emadsamir** [comment] 2018-03-06 00:41
it might be helpful to state that I am querying via Ratel something like such:
{nodes(func: has(p)){
  uid
  expand(_all_){uid}
}}

before delete all 3 edges will show, after, no result
after a new edge created then 3 edges including newly created will show.

To be honest, I am surprised that no one has reported this yet, but maybe because I am really focused on testing creation and deletion of edges that became so apparent to me.

**Comment by pawanrawal** [comment] 2018-03-06 00:47
I could not reproduce this from the information that you have given. Is it possible for you to share a complete reproducible example in Go?

**Comment by emadsamir** [comment] 2018-03-06 00:51
it's part of a big project. I will work on isolating go code for you.

**Comment by emadsamir** [comment] 2018-03-06 01:40
The below reproduces the problem:
```
mu := &api.Mutation{
		CommitNow: true,
		SetNquads: []byte(`
<0x1> <type> "x" .
<0x2> <type> "y" .
<0x3> <type> "y" .
<0x4> <type> "y" .
<0x1> <to> <0x2> .
<0x1> <to> <0x3> .
<0x1> <to> <0x4> .
`),
	}
```

NOW query via Ratel:

```
{nodes(func: has(to)){
  uid
  expand(_all_){uid}
}}
```

you will get 4 nodes and 3 edges

Then run this

```
mu := &api.Mutation{
		CommitNow: true,DelNquads: []byte(\`
<0x4> * * .
<0x1> <to> <0x4> .
\`),
	}
```
NOW query via Ratel: all edges are gone!

**Comment by pawanrawal** [comment] 2018-03-06 04:55
Thanks, @emadsamir. That was helpful in reproducing the issue. I have a fix for this in PR #2195

**Comment by emadsamir** [comment] 2018-03-06 05:41
thanks @pawanrawal for getting on top of this & pointing out a workaround for the time being.
I was, maybe still am concerned about the data integrity of current release when you start manipulating data and schema. for example, I had a major issue when I toggled a predicate "reverse" property on and off, I had to resort to deleting all data and starting over. I do understand that might be a separate issue, but it was worth mentioning.

**Comment by pawanrawal** [comment] 2018-03-06 05:49
Can you share the issue about toggling the reverse property and why you had to delete all the data and start over again?

**Comment by emadsamir** [comment] 2018-03-06 06:04
```
server_1  | Got schema: [predicate:"roles" value_type:UID directive:REVERSE ]
zero_1    | 2018/03/03 07:39:33 oracle.go:84: purging below ts:20136, len(o.commits):2, len(o.aborts):0
server_1  | 2018/03/02 00:12:22 mutation.go:187: Done schema update predicate:"roles" value_type:UID directive:REVERSE 
server_1  | 2018/03/02 00:13:11 groups.go:296: Asking if I can serve tablet for: _share_hash_
server_1  | Got schema: [predicate:"roles" value_type:UID ]
```

after that I couldn't use Ratel after that, not sure if it's related to the below
```
server_1  | 2018/03/03 07:47:22 groups.go:454: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
server_1  | 2018/03/03 07:47:22 groups.go:670: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.

```

**Comment by pawanrawal** [comment] 2018-03-06 06:12
Are there any more logs after what you shared for the server? Could you clarify what you mean by you couldn't use Ratel? Was there any error message?

```
server_1  | Got schema: [predicate:"roles" value_type:UID ]
```

**Comment by emadsamir** [comment] 2018-03-06 06:18
Ratel service completely went down, and as the full log below shows it wouldn't even start again with docker-compose
server_1  | 2018/03/03 07:44:17 groups.go:86: Current Raft Id: 1
server_1  | 2018/03/03 07:44:17 gRPC server started.  Listening on port 9080
server_1  | 2018/03/03 07:44:17 HTTP server started.  Listening on port 8080
server_1  | 2018/03/03 07:44:17 worker.go:99: Worker listening at address: [::]:7080
zero_1    | Setting up grpc listener at: 0.0.0.0:5080
ratel_1   | 2018/03/03 07:44:17 Listening on port 8000...
server_1  | 2018/03/03 07:44:18 pool.go:118: == CONNECT ==> Setting zero:5080
zero_1    | Setting up http listener at: 0.0.0.0:6080
server_1  | 2018/03/03 07:44:21 groups.go:109: Connected to group zero. Connection state: member:<id:1 group_id:1 addr:"server:7080" > state:<counter:171 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"server:7080" > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:1674 > > tablets:<key:"dummy" value:<group_id:1 predicate:"dummy" space:17 > > tablets:<key:"roles" value:<group_id:1 predicate:"roles" space:51 > > tablets:<key:"type" value:<group_id:1 predicate:"type" space:995 > > > > zeros:<key:1 value:<id:1 addr:"zero:5080" > > maxLeaseId:30000 maxTxnTs:40000 maxRaftId:1 > 
zero_1    | 2018/03/03 07:44:18 zero.go:323: Got connection request: id:1 addr:"server:7080" 
server_1  | 2018/03/03 07:44:21 draft.go:140: Node ID: 1 with GroupID: 1
zero_1    | 2018/03/03 07:44:18 node.go:246: Found hardstate: {Term:5 Vote:1 Commit:168 XXX_unrecognized:[]}
server_1  | 2018/03/03 07:44:21 node.go:231: Found Snapshot, Metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:86 Term:5 XXX_unrecognized:[]}
zero_1    | 2018/03/03 07:44:18 node.go:258: Group 0 found 168 entries
server_1  | 2018/03/03 07:44:21 node.go:246: Found hardstate: {Term:5 Vote:1 Commit:86 XXX_unrecognized:[]}
zero_1    | 2018/03/03 07:44:18 raft.go:405: Restarting node for dgraphzero
server_1  | 2018/03/03 07:44:21 node.go:258: Group 1 found 0 entries
zero_1    | 2018/03/03 07:44:18 raft.go:567: INFO: 1 became follower at term 5
server_1  | 2018/03/03 07:44:21 draft.go:661: Restarting node for group: 1
zero_1    | 2018/03/03 07:44:18 raft.go:315: INFO: newRaft 1 [peers: [], term: 5, commit: 168, applied: 0, lastindex: 168, lastterm: 5]
server_1  | 2018/03/03 07:44:21 raft.go:567: INFO: 1 became follower at term 5
zero_1    | Running Dgraph zero...
server_1  | 2018/03/03 07:44:21 raft.go:315: INFO: newRaft 1 [peers: [1], term: 5, commit: 86, applied: 86, lastindex: 86, lastterm: 5]
zero_1    | 2018/03/03 07:44:18 pool.go:118: == CONNECT ==> Setting server:7080
server_1  | 2018/03/03 07:44:25 raft.go:749: INFO: 1 is starting a new election at term 5
zero_1    | 2018/03/03 07:44:18 node.go:127: Setting conf state to nodes:1 
server_1  | 2018/03/03 07:44:25 raft.go:580: INFO: 1 became candidate at term 6
zero_1    | 2018/03/03 07:44:21 raft.go:749: INFO: 1 is starting a new election at term 5
server_1  | 2018/03/03 07:44:25 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 6
zero_1    | 2018/03/03 07:44:21 raft.go:580: INFO: 1 became candidate at term 6
server_1  | 2018/03/03 07:44:25 raft.go:621: INFO: 1 became leader at term 6
zero_1    | 2018/03/03 07:44:21 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 6
server_1  | 2018/03/03 07:44:25 node.go:301: INFO: raft.node: 1 elected leader 1 at term 6
zero_1    | 2018/03/03 07:44:21 raft.go:621: INFO: 1 became leader at term 6
zero_1    | 2018/03/03 07:44:21 node.go:301: INFO: raft.node: 1 elected leader 1 at term 6
zero_1    | 2018/03/03 07:44:21 zero.go:420: Connected

**Closed** 2018-03-06 06:19 UTC
Labels: bug

**Comment by pawanrawal** [comment] 2018-03-06 06:23
I would suggest creating a separate issue for this so that we can resolve this appropriately. Also, if you have a reproducible scenario then that would be helpful.
