### ISSUE TITLE
No way to know which nodes were mutated as part of an upsert operation

### ISSUE THREAD

**Issue by pawanrawal** [dgraph-io/dgraph#4096] opened 2019-09-30 01:00 UTC
## Experience Report

Currently when I use upsert to mutate some nodes based on the result of a query, as an application developer I have no way to know if any nodes were updated or not. When new nodes are created, we get back `Uids` map which tells me about the nodes that were inserted into the graph. It would be helpful to know which nodes (uids) were mutated as part of an upsert operation. 

For e.g.

```
upsert {
  query {
    v as var(func: eq(dgraph.type,  "director"))
  }

  mutation {
    del {
      uid(v) * * .
    }
  }
}
```
If I can know, the list of uids for which the `S * *` operation was performed, I know how many entities were deleted. Similar to how SQL delete queries tell you how many rows were deleted.

### What you wanted to do

I wanted to know how many nodes were deleted/updated as part of an upsert operation.

### What you actually did

I tried doing an upsert operation to delete nodes based on the results of a query.

### Why that wasn't great, with examples

It wasn't great because I have no way of knowing how many nodes were affected (deleted or updated) by my operation.

### Any external references to support your case

This is similar to the Returning id clause that is available in the query language for  Postgres.

**Comment by MichelDiz** [comment] 2019-09-30 16:34
This isn't the same as https://github.com/dgraph-io/dgraph/issues/4048 ?

**Comment by mangalaman93** [comment] 2019-10-09 02:08
This is duplicate of #4048, closing this.

**Closed by mangalaman93** 2019-10-09 02:08 UTC
Labels: area/upsert, kind/enhancement, priority/P1, status/accepted
