### ISSUE TITLE
predefined rule for edges

### ISSUE THREAD

**Issue by yupengfei** [dgraph-io/dgraph#2870] opened 2019-01-04 04:36 UTC
## Experience Report

Note: Feature requests are judged based on user experience and modeled on [Go Experience Reports](https://github.com/golang/go/wiki/ExperienceReports). These reports should focus on the problems: they should not focus on and need not propose solutions.

### What you wanted to do

When import millions of nodes, I had to write code to insert their edges,  if we support grammer works like

MATCH (employee:Employee {employeeID: row.EmployeeID})
MATCH (manager:Employee {employeeID: row.ReportsTo})
MERGE (employee)-[:REPORTS_TO]->(manager);

and then I can predefine both the schema and the rules for generate edges automaticly. Then I can only insert items and leave the insertion of edges to dgraph. 

### What you actually did

I had to insert the edges myself, when I have tens of tables, the work is annoying.

**Comment by MichelDiz** [comment] 2019-01-05 01:45
Hi yupengfei,

Thanks for you report.

Can you share more information about what you are doing? I'm working on your report.

The code you are using to add Edges. What language is it? Can you share it?

Can you explain this query a bit? I understand what it does, but I can not understand it in the context of millions of nodes. All millions of nodes already have unique IDs or are they all the same?

BTW, Dgraph BulkLoad now supports JSON files. If it can helps.

**Comment by yupengfei** [comment] 2019-01-05 04:04
Hi,
   I am working on a real-time recommend system, and for now, our system works on MySQL and MongoDB. I read the data from a MongoDB by tail the oplog, and then write the data into DGraph, with a fork of [transporter](https://github.com/compose/transporter) maintained by myself. There are so many tables, such as the operation log of the customers, the blog and reply they post. When a new document is written to MongoDB, I will write a copy to DGraph, with all edges it relates.  For example, when someone post a new reply, there should be an edge to the user who write this reply and an edge to the blog which it reply to. Now I have to maintain this edges by hand, it will be convenient if DGraph support that.

   The grammar I referred is from neo4j, I known that DGraph  is designed very different from neo4j, but if it provides something like that, I will be very thankful.

   As mentioned above, I can not load all data once, it is document by document, so bulk load may not help.

**Comment by gitlw** [comment] 2019-01-14 21:44
Hi @yupengfei 

Thanks for using Dgraph.
I'm not sure whether I totally understand your request. Even if there is such a rule in Dgraph, how would it know which employee should report to which other employee when there are lots of employees in the DB. Conceptually you still need to provide the A -- reportsTo --> B relationship one by one to the DB for it to understand. 

Maybe I misunderstood your feature request, if so, can you please provide a sample input, or even better if you can provide a sample code that you need to accomplish this task now.
Thanks!

**Comment by yupengfei** [comment] 2019-01-17 02:43
@gitlw 
Sorry for reply late, I think if I can define a schema that 
_a person node have a property named A with value a must have a link b with a post node have a property named B with value a._

Then I can predefine the schema, then insert person nodes and post nodes, without insert the link explicitly, the links can be generated automaticly. Since there are some many kind of links, insert links is annoying.

**Comment by manishrjain** [comment] 2019-01-17 02:52
Instead of Dgraph doing link generation automatically, you could run a periodic loop, which can run this query, and create the links.

```
{
  uidA(func: has(A)) @filter(eq(A, "a")) { uid }
  uidB(func: has(B)) @filter(eq(B, "a")) { uid }
}
```

Then once you have these results, you can create a mutation which can join the two. I'm not sure if it's worth Dgraph running this logic for you.

Also, this sounds like a duplicate of #2438 .

**Comment by yupengfei** [comment] 2019-01-17 03:49
@manishrjain 
Yes, it works, but in my scene, I have many MySQL tables(about one hundred) with many foreign keys, if dgraph can create links automaticly after I define some schema, it would great, I can write a few line of code to sync MySQL data to dgraph in real time, MySQL for online business and dgraph for recommendation engine. 

But for now, I have to write so much more code to deal with links.

**Comment by manishrjain** [comment] 2019-01-17 04:13
For now, that functionality seems beyond the scope of Dgraph.

In fact, you could just replace your MySQL DB with Dgraph, and then you wouldn't need to do this one-way streaming.

**Closed** 2019-01-17 04:14 UTC
Labels: feature, wontfix

**Comment by MichelDiz** [comment] 2019-01-17 16:07
Hey @yupengfei this https://github.com/dgraph-io/dgraph/issues/2848 could be useful for your migration. You would only need to provide an endpoint that provides JSON or export your SQL data to JSON file. Is not the same, but could be helpful for migration using LiveBulk or Bulkloader.

**Comment by yupengfei** [comment] 2019-01-18 02:02
@MichelDiz I am using [canal](https://github.com/siddontang/go-mysql#canal) to sync MySQL data to dgraph, our system has been running on MySQL for five years,   it is impossible to migrate.
