### ISSUE TITLE
Running a number of mutations in parallel causes dgraph to refuse connection

### ISSUE THREAD

**Issue by sungwoncho** [dgraph-io/dgraph#989] opened 2017-05-29 02:14 UTC
Version: 0.7.7
OS: macOS Sierra

-----

Reproduce:

1. Download and unzip lifehacks.stackexchange.com.7z from [here](https://ia800500.us.archive.org/22/items/stackexchange/)
2. Run this script to send about 50k mutations by running 1000 goroutines in a given moment. https://github.com/dgraph-io/graphoverflow/blob/21a9ac4b961de603cecdd8d98695870a485e781a/votes/main.go#L59

    go run votes/main.go --dir=/Users/mikecho/dev/tmp/lifehacks --dryrun=false

3. After running for some time, the script exits with

    http://localhost:8080/query: dial tcp [::1]:8080: getsockopt: connection refused

-----

* If the limiter is decreased to `100`, sometimes, but not always, all the mutations run without `connection refused` error.
* The error message does not give enough information about what the issue might be.

**Comment by sungwoncho** [comment] 2017-06-06 00:22
I was able to reproduce it in the following system using Dgraph version `0.7.7`.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

$ free -m
              total        used        free      shared  buff/cache   available
Mem:          15290       11697         164          56        3428        3171
Swap:             0           0           0


$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       61100
-n: file descriptors                1000000
-l: locked-in-memory size (kbytes)  64
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 61100
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited

```

---

Error message varies. Sometimes I get 

    2017/06/06 00:20:45 Post http://127.0.0.1:8080/query: dial tcp 127.0.0.1:8080: i/o timeout

**Comment by janardhan1993** [comment] 2017-07-12 01:33
I can reproduce this. Looking into it.

**Comment by janardhan1993** [comment] 2017-07-12 04:21
Sung tried the same on master and couldn't reproduce. Closing the issue now

**Closed by janardhan1993** 2017-07-12 04:21 UTC
Labels: bug, ready
