### ISSUE TITLE
DateVal is not processing properly on mutation

### ISSUE THREAD

**Issue by sirkon** [dgraph-io/dgraph#3200] opened 2019-03-25 09:47 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

v0.0.13

- Have you tried reproducing the issue with latest release?

yeah, sure

- What is the hardware spec (RAM, OS)?

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
…
```
```
MemTotal:       16326928 kB
MemFree:         1709668 kB
MemAvailable:    7785724 kB
…
```

- Steps to reproduce the issue (command/config used to run Dgraph).

You may use [this](https://docs.dgraph.io/get-started#docker-compose) docker compose info. Then [set up](https://docs.dgraph.io/get-started#adding-indexes) an index

And a program I used:

```go
package main

import (
	"context"
	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
	"log"
	"time"
)

func main() {
	conn, err := grpc.Dial("localhost:9080", grpc.WithInsecure())
	if err != nil {
		log.Fatal(err)
	}

	dgraphClient := api.NewDgraphClient(conn)
	client := dgo.NewDgraphClient(dgraphClient)

	resp, err := client.NewTxn().Mutate(context.Background(), &api.Mutation{
		Set: []*api.NQuad{
			{
				Subject:   "_:tmp",
				Predicate: "release_date",
				ObjectValue: &api.Value{
					Val: &api.Value_DateVal{
						DateVal: time.Now().AppendFormat(nil, "2006-01-02"),
					},
				},
			},
		},
	})
	if err != nil {
		log.Fatalf("failed to insert: %s", err)
	}
	log.Printf("inserted %d items", len(resp.Uids))
}
```

- Expected behaviour and actual result.

I should get successful mutation. Got `rpc error: code = Unknown desc = parsing time "" as "2006": cannot parse "" as "2006"` instead. I could use `api.Value_StrVal` instead and this works. Still, it is a bit strange date vale doesn't work for date mutations. 

PS you could do much better with dates. Using bytes for date is one strange decision. There's `oneof` specifically for these kind of tasks.

**Comment by srfrog** [comment] 2019-03-25 17:47
Thanks for reporting this. This is a duplicate of #3166 which has a PR (#3169) with a fix already. I will close this one. Please refer to the older issue.

Related: #3166

**Closed by srfrog** 2019-03-25 17:47 UTC

**Comment by srfrog** [comment] 2019-03-25 17:49
Also, we store all values as bytes. But for dates we are storing them as time vals. Null dates use zero-time values. This is a recent change that might not be in the latest release yet.
