### ISSUE TITLE
Weird dgraph behavior with nested struct: the struct is returned depending on its values

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#3667] opened 2019-07-13 05:23 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
Dgraph version   : v1.0.15
Commit SHA-1     : ff5ee1e2
Commit timestamp : 2019-05-30 15:46:55 -0700
Branch           : HEAD
Go version       : go1.12.5

Same issue with master:
Dgraph version   : master
Commit SHA-1     : 60b2b152
Commit timestamp : 2019-07-12 15:20:28 -0700
Branch           : master
Go version       : go1.12.5

- Have you tried reproducing the issue with latest release?
Yes

- What is the hardware spec (RAM, OS)?
Core i7 Skylake, 32GB ram, Windows 10. Dgraph runs in docker using docker for windows

- Steps to reproduce the issue (command/config used to run Dgraph).
Assuming dgraph is available, set the `DGRAPH_ADDR` variable to dgraph zero's address. Then execute the following code:
```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

func main() {

	dgraphAddr := os.Getenv("DGRAPH_ADDR")

	d, err := grpc.Dial(dgraphAddr, grpc.WithInsecure())

	if err != nil {
		log.Fatalf("Error opening connection to Dgraph server: %s", err)
	}

	dg := dgo.NewDgraphClient(api.NewDgraphClient(d))

	err = dg.Alter(context.Background(), &api.Operation{
		DropAll: true,
	})

	if err != nil {
		log.Fatal(err)
	}

	type School struct {
		Name string `json:"name,omitempty"`
	}

	type ProfilePicture struct {
		Type   string    `json:"type,omitempty"`
		Coords []float64 `json:"coordinates,omitempty"`
	}

	// If omitempty is not set, then edges with empty values (0 for int/float, "" for string, false
	// for bool) would be created for values not specified explicitly.

	type Person struct {
		Uid            string         `json:"uid,omitempty"`
		Name           string         `json:"name,omitempty"`
		Age            int            `json:"age,omitempty"`
		Married        bool           `json:"married,omitempty"`
		Raw            []byte         `json:"raw_bytes,omitempty"`
		Friends        []Person       `json:"friend,omitempty"`
		ProfilePicture ProfilePicture `json:"profilePicture,omitempty"`
		School         []School       `json:"school,omitempty"`
	}

	// While setting an object if a struct has a Uid then its properties in the graph are updated
	// else a new node is created.
	// In the example below new nodes for Alice, Bob and Charlie and school are created (since they
	// don't have a Uid).
	p := Person{
		Name:    "Alice",
		Age:     26,
		Married: true,
		ProfilePicture: ProfilePicture{
			Type:   "Point",
			Coords: []float64{1, 3},
		},
		Raw: []byte("raw_bytes"),
		Friends: []Person{{
			Name: "Bob",
			Age:  24,
		}, {
			Name: "Charlie",
			Age:  29,
		}},
		School: []School{{
			Name: "Crown Public School",
		}},
	}

	op := &api.Operation{}
	op.Schema = `
		age: int .
		married: bool .
	`

	ctx := context.Background()
	if err := dg.Alter(ctx, op); err != nil {
		log.Fatal(err)
	}

	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("input json: ", string(pb))
	mu.SetJson = pb
	assigned, err := dg.NewTxn().Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}

	// Assigned uids for nodes which were created would be returned in the assigned.Uids map.
	puid := assigned.Uids["blank-0"]
	const q = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			profilePicture
			raw_bytes
			married
			friend {
				name
				age
			}
			school {
				name
			}
		}
	}`

	variables := make(map[string]string)
	variables["$id"] = puid
	resp, err := dg.NewTxn().QueryWithVars(ctx, q, variables)
	if err != nil {
		log.Fatal(err)
	}

	type Root struct {
		Me []Person `json:"me"`
	}

	var r Root
	err = json.Unmarshal(resp.Json, &r)
	if err != nil {
		log.Fatal(err)
	}

	// R.Me would be same as the person that we set above.
	// fmt.Printf("Me: %+v\n", r.Me)

	fmt.Println("result json: ", string(resp.Json))
}
```
This produces the following output (which we expect):
```
input json:  {"name":"Alice","age":26,"married":true,"raw_bytes":"cmF3X2J5dGVz","friend":[{"name":"Bob","age":24,"profilePicture":{}},{"name":"Charlie","age":29,"profilePicture":{}}],"profilePicture":{"type":"Point","coordinates":[1,3]},"school":[{"name":"Crown Public School"}]}
result json:  {"me":[{"name":"Alice","age":26,"profilePicture":{"type":"Point","coordinates":[1,3]},"raw_bytes":"cmF3X2J5dGVz","married":true,"friend":[{"name":"Bob","age":24},{"name":"Charlie","age":29}],"school":[{"name":"Crown Public School"}]}]}
```

On line 67, update the string "Point" to "Pointa":
```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

func main() {

	dgraphAddr := os.Getenv("DGRAPH_ADDR")

	d, err := grpc.Dial(dgraphAddr, grpc.WithInsecure())

	if err != nil {
		log.Fatalf("Error opening connection to Dgraph server: %s", err)
	}

	dg := dgo.NewDgraphClient(api.NewDgraphClient(d))

	err = dg.Alter(context.Background(), &api.Operation{
		DropAll: true,
	})

	if err != nil {
		log.Fatal(err)
	}

	type School struct {
		Name string `json:"name,omitempty"`
	}

	type ProfilePicture struct {
		Type   string    `json:"type,omitempty"`
		Coords []float64 `json:"coordinates,omitempty"`
	}

	// If omitempty is not set, then edges with empty values (0 for int/float, "" for string, false
	// for bool) would be created for values not specified explicitly.

	type Person struct {
		Uid            string         `json:"uid,omitempty"`
		Name           string         `json:"name,omitempty"`
		Age            int            `json:"age,omitempty"`
		Married        bool           `json:"married,omitempty"`
		Raw            []byte         `json:"raw_bytes,omitempty"`
		Friends        []Person       `json:"friend,omitempty"`
		ProfilePicture ProfilePicture `json:"profilePicture,omitempty"`
		School         []School       `json:"school,omitempty"`
	}

	// While setting an object if a struct has a Uid then its properties in the graph are updated
	// else a new node is created.
	// In the example below new nodes for Alice, Bob and Charlie and school are created (since they
	// don't have a Uid).
	p := Person{
		Name:    "Alice",
		Age:     26,
		Married: true,
		ProfilePicture: ProfilePicture{
			Type:   "Pointa",
			Coords: []float64{1, 3},
		},
		Raw: []byte("raw_bytes"),
		Friends: []Person{{
			Name: "Bob",
			Age:  24,
		}, {
			Name: "Charlie",
			Age:  29,
		}},
		School: []School{{
			Name: "Crown Public School",
		}},
	}

	op := &api.Operation{}
	op.Schema = `
		age: int .
		married: bool .
	`

	ctx := context.Background()
	if err := dg.Alter(ctx, op); err != nil {
		log.Fatal(err)
	}

	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("input json: ", string(pb))
	mu.SetJson = pb
	assigned, err := dg.NewTxn().Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}

	// Assigned uids for nodes which were created would be returned in the assigned.Uids map.
	puid := assigned.Uids["blank-0"]
	const q = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			profilePicture
			raw_bytes
			married
			friend {
				name
				age
			}
			school {
				name
			}
		}
	}`

	variables := make(map[string]string)
	variables["$id"] = puid
	resp, err := dg.NewTxn().QueryWithVars(ctx, q, variables)
	if err != nil {
		log.Fatal(err)
	}

	type Root struct {
		Me []Person `json:"me"`
	}

	var r Root
	err = json.Unmarshal(resp.Json, &r)
	if err != nil {
		log.Fatal(err)
	}

	// R.Me would be same as the person that we set above.
	// fmt.Printf("Me: %+v\n", r.Me)

	fmt.Println("result json: ", string(resp.Json))
}
```
The `profilePicture` nested struct is no longer returned when we query dgraph:
```
input json:  {"name":"Alice","age":26,"married":true,"raw_bytes":"cmF3X2J5dGVz","friend":[{"name":"Bob","age":24,"profilePicture":{}},{"name":"Charlie","age":29,"profilePicture":{}}],"profilePicture":{"type":"Pointa","coordinates":[1,3]},"school":[{"name":"Crown Public School"}]}
result json:  {"me":[{"name":"Alice","age":26,"raw_bytes":"cmF3X2J5dGVz","married":true,"friend":[{"name":"Charlie","age":29},{"name":"Bob","age":24}],"school":[{"name":"Crown Public School"}]}]}
```

I find that if I change the fields in the `ProfilePicture` struct, this also happens. If I change the `coordinates` field in the `ProfilePicture` struct to only contain 1 value, this also happens.

I ran into this issue debugging an app I am working on and it seems to be quite weird. It feels like there's some sort of internal handling/special treatment for the struct.

**Comment by martinmr** [comment] 2019-07-15 23:29
This isn't really a bug. For handling geolocation data we use this library: https://github.com/twpayne/go-geom. It provides a bunch of types but currently we only support point, polygon, and multipolygon. 

When you change the type value to "pointa", Dgraph does not recognize that as a valid geo type. When you change the coordinates to only have one value, Dgraph does not recognize that as a valid coordinate since it needs two values (latitude and longitude). So in these cases, Dgraph is inserting the structs for which it can generate triples and ignoring the rest, which is the expected behavior.

Dgraph docs: https://docs.dgraph.io/master/query-language/#geolocation

**Comment by F21** [comment] 2019-07-15 23:37
So, are generic nested structs simply unsupported in dgraph? For my use-case I do not use a geolocation type, but rather a struct that looks like this:

```go
type ProfilePicture struct {
	ID      string
	ContentType string
	Height      uint64
	Width       uint64
}
```

**Comment by martinmr** [comment] 2019-07-15 23:53
Dgraph does not support structs. It supports JSON so as long as your struct is marshaled into proper JSON you should be fine. Your example above should work.

With regards to the geo location data, it seems like we might be trying to implicitly convert some data to geo location data. I'll keep looking into that since that is not very obvious behavior. But your use-case should be supported.

**Comment by martinmr** [comment] 2019-07-15 23:53
I am reopening this to keep looking into the geo data conversion issue.

**Comment by F21** [comment] 2019-07-16 00:07
Here's some updated code demonstrating the problem:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

func main() {

	dgraphAddr := os.Getenv("DGRAPH_ADDR")

	d, err := grpc.Dial(dgraphAddr, grpc.WithInsecure())

	if err != nil {
		log.Fatalf("Error opening connection to Dgraph server: %s", err)
	}

	dg := dgo.NewDgraphClient(api.NewDgraphClient(d))

	err = dg.Alter(context.Background(), &api.Operation{
		DropAll: true,
	})

	if err != nil {
		log.Fatal(err)
	}

	type School struct {
		Name string `json:"name,omitempty"`
	}

	type ProfilePicture struct {
		ID          string `json:"id,omitempty"`
		ContentType string `json:"contentType,omitempty"`
		Height      uint64 `json:"height,omitempty"`
		Width       uint64 `json:"width,omitempty"`
	}

	// If omitempty is not set, then edges with empty values (0 for int/float, "" for string, false
	// for bool) would be created for values not specified explicitly.

	type Person struct {
		Uid            string          `json:"uid,omitempty"`
		Name           string          `json:"name,omitempty"`
		Age            int             `json:"age,omitempty"`
		Married        bool            `json:"married,omitempty"`
		ProfilePicture *ProfilePicture `json:"profilePicture,omitempty"`
	}

	// While setting an object if a struct has a Uid then its properties in the graph are updated
	// else a new node is created.
	// In the example below new nodes for Alice, Bob and Charlie and school are created (since they
	// don't have a Uid).
	p := Person{
		Name:    "Alice",
		Age:     26,
		Married: true,
		ProfilePicture: &ProfilePicture{
			ID:          "someid",
			ContentType: "image/png",
			Height:      100,
			Width:       100,
		},
	}

	op := &api.Operation{}
	op.Schema = `
		age: int .
		married: bool .
	`

	ctx := context.Background()
	if err := dg.Alter(ctx, op); err != nil {
		log.Fatal(err)
	}

	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("input json: ", string(pb))
	mu.SetJson = pb
	assigned, err := dg.NewTxn().Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}

	// Assigned uids for nodes which were created would be returned in the assigned.Uids map.
	puid := assigned.Uids["blank-0"]
	const q = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			profilePicture
		}
	}`

	variables := make(map[string]string)
	variables["$id"] = puid
	resp, err := dg.NewTxn().QueryWithVars(ctx, q, variables)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("result json: ", string(resp.Json))

	const q2 = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			profilePicture {
				id
				contentType
				height
				width
			}
		}
	}`

	resp2, err := dg.NewTxn().QueryWithVars(ctx, q2, variables)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("result json2: ", string(resp2.Json))
}
```

In the case of nested structs, do I need to query for it's subfields for them to show up? I noticed that when I do that, they are returned as a list of fields, which is contrary to what they are saved as (see the output of `result json2`) .

**Comment by martinmr** [comment] 2019-07-16 00:17
Thanks. There seems to be a strange problem with that struct. For some reason School works just fine even when nested but I can't get ProfilePicture to work.

**Comment by F21** [comment] 2019-07-16 00:30
For school, I am seeing the same result:

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/dgraph-io/dgo"
	"github.com/dgraph-io/dgo/protos/api"
	"google.golang.org/grpc"
)

func main() {

	dgraphAddr := os.Getenv("DGRAPH_ADDR")

	d, err := grpc.Dial(dgraphAddr, grpc.WithInsecure())

	if err != nil {
		log.Fatalf("Error opening connection to Dgraph server: %s", err)
	}

	dg := dgo.NewDgraphClient(api.NewDgraphClient(d))

	err = dg.Alter(context.Background(), &api.Operation{
		DropAll: true,
	})

	if err != nil {
		log.Fatal(err)
	}

	type School struct {
		Name string `json:"name,omitempty"`
	}

	type ProfilePicture struct {
		ID          string `json:"id,omitempty"`
		ContentType string `json:"contentType,omitempty"`
		Height      uint64 `json:"height,omitempty"`
		Width       uint64 `json:"width,omitempty"`
	}

	// If omitempty is not set, then edges with empty values (0 for int/float, "" for string, false
	// for bool) would be created for values not specified explicitly.

	type Person struct {
		Uid     string  `json:"uid,omitempty"`
		Name    string  `json:"name,omitempty"`
		Age     int     `json:"age,omitempty"`
		Married bool    `json:"married,omitempty"`
		School  *School `json:"school,omitempty"`
	}

	// While setting an object if a struct has a Uid then its properties in the graph are updated
	// else a new node is created.
	// In the example below new nodes for Alice, Bob and Charlie and school are created (since they
	// don't have a Uid).
	p := Person{
		Name:    "Alice",
		Age:     26,
		Married: true,
		School: &School{
			Name: "test",
		},
	}

	op := &api.Operation{}
	op.Schema = `
		age: int .
		married: bool .
	`

	ctx := context.Background()
	if err := dg.Alter(ctx, op); err != nil {
		log.Fatal(err)
	}

	mu := &api.Mutation{
		CommitNow: true,
	}
	pb, err := json.Marshal(p)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println("input json: ", string(pb))
	mu.SetJson = pb
	assigned, err := dg.NewTxn().Mutate(ctx, mu)
	if err != nil {
		log.Fatal(err)
	}

	// Assigned uids for nodes which were created would be returned in the assigned.Uids map.
	puid := assigned.Uids["blank-0"]
	const q = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			school
		}
	}`

	variables := make(map[string]string)
	variables["$id"] = puid
	resp, err := dg.NewTxn().QueryWithVars(ctx, q, variables)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("result json: ", string(resp.Json))

	const q2 = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			school {
				name
			}
		}
	}`

	resp2, err := dg.NewTxn().QueryWithVars(ctx, q2, variables)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("result json2: ", string(resp2.Json))
}

```

**Comment by martinmr** [comment] 2019-07-16 00:38
So I found what the "error" was. I keep forgetting about this but when you query a node of type uid, you need to specify what fields you want to get.

This query will work:

```
const q2 = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			school {
				name
			}
		}
	}`
```

but this one won't return any results for school:

```
const q2 = `query Me($id: string){
		me(func: uid($id)) {
			name
			age
			school
		}
	}`
```

The geolocation issue is still happening but as long as your nested structs don't have geolocation data you should be fine.

**Comment by F21** [comment] 2019-07-16 00:39
The problem with querying for the subfield is that it returns as a list of schools, whereas it was saved as a nested object directly.

```json
input json:  {"name":"Alice","age":26,"married":true,"school":{"name":"test"}}
result json:  {"me":[{"name":"Alice","age":26,"school":[{"name":"test"}]}]}
```
Is this expected behavior?

**Comment by martinmr** [comment] 2019-07-16 00:46
Yes, forgot to mention I had to change the struct field ProfilePicture to take a list.

In the current version (1.0.16), all uid predicates return a list so this is expected.

In version 1.1, scheduled for this month, one can specify the schema as `school: uid .` to enforce a single object (the JSON will return an object instead of a list) or as `school: [uid] .` to allow multiple predicates. If you were using 1.1 you'd still be seeing this issue since the second option is chosen when the schema is not provided to avoid overwriting data.

So for now this is expected. When the new version is released you'll be able to enforce single UID predicates. For now, just change the type of the nested objects to a list.

**Comment by F21** [comment] 2019-07-16 00:47
That makes sense. Thanks for your help!

**Comment by martinmr** [comment] 2019-07-16 01:09
I found the code that checks for geolocation data in the method mapToNquads. I will add documentation to make this explicit to our users. Other than that I don't think there's much more to do with this issue.

**Comment by campoy** [comment] 2019-07-16 16:55
Create an issue tracking the documentation needs and close this one, @martinmr

Thanks for helping @F21

**Closed** 2019-07-16 17:11 UTC
