### ISSUE TITLE
Add non nullable types to return empty arrays for missing relations

### ISSUE THREAD

**Issue by sebastian-walter** [dgraph-io/dgraph#2337] opened 2018-04-16 08:53 UTC
According to the GraphQL specs it is possible to define non nullable types: http://facebook.github.io/graphql/October2016/#sec-Types.Non-Null 

According to this source here, this can also be applied for lists: https://graphql.org/learn/schema/#lists-and-non-null

This feature is very helpful when dealing with missing relations, e.g. here:

```
{
      objectives(func: uid(XXXX))
          uid
          lead {
              uid
              fullName
    }
}
```

The query result looks currently like this:
```
  "data": {
    "objectives": [{
        "uid": "XXXXX"
    }]
},
```

But this would simplify the handling in the frontend since you don't have to deal with the undefined case anymore:
```
  "data": {
    "objectives": [{
         "uid": "XXXXX",
        "objective_lead": []
    }]
  },
```

Since this could be done by changing the schema, it would have no effect for existing users of dgraph.

**Comment by labs20** [comment] 2018-04-18 17:07
I think this can be usefull, as returning not found predicates as empty would be too, like if you're mapping a result to a Vue data, for instance. But I think that a flag of sorts should be required to set such behaviour.

**Comment by manishrjain** [comment] 2019-01-16 02:47
This seems like something we can easily introduce to GraphQL+-. Should be an easy change at our end.

**Comment by martinmr** [comment] 2019-02-04 23:11
Non-nullable in graphQL has a slightly different meaning than what the first comment is proposing. It does not mean that an empty value will be returned. It means that trying to return a nil value will cause an error and said error will be pushed to the parent. If the parent is non-nullable as well, it will propagate the error.

See https://blog.apollographql.com/using-nullability-in-graphql-2254f84c4ed7 for some examples.

We will still add non-nullable types to Dgraph but they will not behave as stated in the first comment.

**Comment by martinmr** [comment] 2019-02-04 23:18
Closing as this is a duplicate of #2972.

**Closed by martinmr** 2019-02-04 23:18 UTC
Labels: easy, enhancement
