### ISSUE TITLE
Alpha crashes with fault address in groupby.go

### ISSUE THREAD

**Issue by jarifibrahim** [dgraph-io/dgraph#3642] opened 2019-07-09 14:07 UTC
### What version of Dgraph are you using?
727b246b5147d5c652e4e752938d20d402722cc0

### Have you tried reproducing the issue with latest release?
Yes

### What is the hardware spec (RAM, OS)?
N/A

### Steps to reproduce the issue (command/config used to run Dgraph).
1. Run zero using 
```
dgraph zero -w /home/ibrahim/m2_drive/flock_backup/zero1/zw -o 0 --idx=1 --my=localhost:5080 --replicas=1 --logtostderr -v=2 --bindall
```
2. Run alpha using
```
dgraph alpha -p /home/ibrahim/m2_drive/flock_backup/alpha1/p -w /home/ibrahim/m2_drive/flock_backup/alpha1/w -o 100 --my=localhost:7180 --lru_mb=1024 --zero=localhost:5080 --logtostderr -v=2
```
4. Apply the following diff on flock agent's main.go
```diff
diff --git a/main.go b/main.go
index c2cf6ec..91e8da0 100644
--- a/main.go
+++ b/main.go
@@ -52,8 +52,8 @@ id_str: string @index(exact) @upsert .
 created_at: dateTime @index(hour) .
 hashtags: [string] @index(exact) .
 
-author: uid @count @reverse .
-mention: uid @reverse .
+author: [uid] @count @reverse .
+mention: [uid] @reverse .
 `
 
        cDgraphTweetQuery = `
```
3. Run flock agent
```
go run main.go -a ":9180"
```
4. Apply the following to flock client's main.go (without this change some of the queries in flock were failing)
```diff
diff --git a/client/main.go b/client/main.go
index c1eab19..5913475 100644
--- a/client/main.go
+++ b/client/main.go
@@ -547,7 +547,7 @@ type querySix struct {
 
 func (q *querySix) getParams(dgr *dgo.Dgraph) error {
        // we subtract 41 hours because that's the latest data we get from twitter
-       curTime := time.Now().Add(-41 * time.Hour)
+       curTime := time.Now().Add(-100 * time.Hour)
 
        query := fmt.Sprintf(`
 {
@@ -619,7 +619,7 @@ type querySeven struct {
 
 func (q *querySeven) getParams(dgr *dgo.Dgraph) error {
        // we subtract 41 hours because that's the latest data we get from twitter
-       curTime := time.Now().Add(-41 * time.Hour)
+       curTime := time.Now().Add(-100 * time.Hour)
 
        query := fmt.Sprintf(`
 {
@@ -693,7 +693,7 @@ type queryEight struct {
 
 func (q *queryEight) runQuery(dgr *dgo.Dgraph) error {
        // we subtract 41 hours because that's the latest data we get from twitter
-       curTime := time.Now().Add(-41 * time.Hour)
+       curTime := time.Now().Add(-100 * time.Hour)
 
        query := fmt.Sprintf(`
 {
@@ -787,7 +787,7 @@ type queryNine struct {
 
 func (q *queryNine) getParams(dgr *dgo.Dgraph) error {
        // we subtract 41 hours because that's the latest data we get from twitter
-       curTime := time.Now().Add(-41 * time.Hour)
+       curTime := time.Now().Add(-100 * time.Hour)
 
        query := fmt.Sprintf(`
 {

```
5. Run flock client
```
go run main.go -a ":9180"
```
### Expected behaviour and actual result.
After a few seconds alpha crashes. Here's the stack trace of alpha https://gist.github.com/jarifibrahim/d517efefd7f7c334a9bb50552041cc11

**Comment by martinmr** [comment] 2019-07-12 21:55
@jarifibrahim Can you check if the following change to groupby.go in line 225 helps?

Change from
```
ul := child.uidMatrix[i]
```

to
```
if i >= len(child.uidMatrix) {
  continue
}
ul := child.uidMatrix[i]
```

I think that would stop the crash but I am not sure if it's the right solution, or why uidMatrix does not have enough entries.

**Comment by jarifibrahim** [comment] 2019-07-15 11:12
@martinmr The change stopped the crash.

**Comment by martinmr** [comment] 2019-07-15 19:27
ok.still not sure of the root cause but i'll open a PR with the fix. We have similar checks in our codebase so this should be fine.

**Comment by martinmr** [comment] 2019-07-15 20:33
My bad, the crash is in the next line while trying to access `ul.Uids`. So `ul` is nil. I am guessing the error is not happening every time so it looked like my original suggestion fixed it. For now, I'll open a PR to check that ul is non-nil.

**Comment by martinmr** [comment] 2019-07-15 20:41
https://github.com/dgraph-io/dgraph/pull/3670

**Comment by martinmr** [comment] 2019-07-15 23:12
Fix has been submitted so closing this for now. Feel free to reopen if you happen to see it again but the original segfault should be gone now.

**Closed by martinmr** 2019-07-15 23:12 UTC
Labels: area/facets, kind/bug, priority/P1, status/accepted
