### ISSUE TITLE
Line numbers on query parse errors

### ISSUE THREAD

**Issue by ddibiase** [dgraph-io/dgraph#1523] opened 2017-09-24 16:44 UTC
Having a heck of a time trying to debug lines that are failing in my queries. Sometimes I get lexText errors or strconv parse errors and have no idea what line to reference them on. Would love this to come back in the gRPC and REST error messages.

As discussed on Slack, elbow-jason suggested:
```or even a “there was a problem here: <some_text>” with some text for +-40 chars or something similar```

**Comment by ddibiase** [comment] 2017-09-25 03:49
I suppose for gRPC requests the line number wouldn't make sense, so perhaps simply reading out the nquad that failed would be helpful.

**Comment by peterstace** [comment] 2017-09-25 04:19
Duplicate of #1505. This will go into the next release.

Btw, that's the solution we went for -- just adding the failing NQuad to the error message so it's clear which one is the problem.

**Closed by peterstace** 2017-09-25 04:19 UTC
