### ISSUE TITLE
reverse edge not deleted with S P *

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1271] opened 2017-07-28 00:32 UTC
I'm on

```
Dgraph version   : v0.8.0-dev
Commit SHA-1     : 59e8a58
Commit timestamp : 2017-07-27 17:58:25 +1000
Branch           : master
```

I ran

```
curl localhost:8081/query -XPOST -d $'
mutation {
  schema {
    testedge : uid @reverse .
    name : string @index(exact) .
  }
  set {
    _:bill <name> "Bill" .
    _:frank <name> "Frank" .
    _:bill <testedge> _:frank .
  }
}'
```

and got `"uids":{"bill":"0x2","frank":"0x3"}`

Then
```
curl localhost:8081/query -XPOST -d $' 
mutation {
  delete {
    <0x2> <testedge> * .
  }
}'
```

now the edge is gone in the forward direction, but

```
curl localhost:8081/query -XPOST -d $' 
{
  q(func: eq(name, "Frank")) {
    _uid_
    ~testedge { 
      _uid_ 
      name 
    }
  }
}' | python -m json.tool | less
```

still finds the reverse edge.

**Comment by MichaelJCompton** [comment] 2017-07-28 00:36
same on
```
Dgraph version   : v0.8.0-dev
Commit SHA-1     : fe21a84
Commit timestamp : 2017-07-27 10:03:15 +1000
Branch           : release/v0.8.0
```

**Comment by pawanrawal** [comment] 2017-07-28 01:40
This is the intended behavior. `S P *` deletion only deletes the posting list corresponding to the given S and P. We don't maintain what all posting lists (with predicate ~P) contain this Subject, so deleting incoming edges to a node doesn't scale for us.

**Comment by manishrjain** [comment] 2017-07-28 01:52
This is a bug. We must fix this.

**Comment by pawanrawal** [comment] 2017-07-28 02:37
Hey @MichaelJCompton 

Thanks for filing this. Should have researched more before commenting. The issue has been fixed now.

**Closed** 2017-07-28 02:37 UTC
Labels: bug, in progress

**Comment by rebootcode** [comment] 2018-05-22 20:44
Oh! and I just encountered this error - and found, it is still a BUG and this bug is literally killer 😢

**Comment by manishrjain** [comment] 2018-05-25 21:33
Can you file a new issue?

**Comment by rebootcode** [comment] 2018-05-26 04:56
@manishrjain - you bro , already did - https://github.com/dgraph-io/dgraph/issues/2409
