### ISSUE TITLE
Ratel links broken

### ISSUE THREAD

**Issue by ekkis** [dgraph-io/dgraph#2323] opened 2018-04-10 02:05 UTC
I'm running the Ratel dashboard and if I click on the question mark icon on the left toolbar, it displays some links where to get help but none of them are clickable.  same thing when clicking on the Messages icon

**Comment by gpahal** [comment] 2018-04-10 05:17
Which OS and Browser are you using? I am not able to reproduce it on Linux Chrome.

**Comment by gpahal** [comment] 2018-04-10 06:31
These are simple links which open in a new tab. We don't have anything special there. Does it show a link if you hover over them? Or does it allow copying link address on right click?

**Comment by gpahal** [comment] 2018-04-10 06:32
One reason might be: https://github.com/dgraph-io/dgraph/issues/1972

**Comment by ekkis** [comment] 2018-04-10 19:33
yes, the problem is because of the overlay.  it doesn't allow clicking on the links below it

**Comment by gpahal** [comment] 2018-04-11 09:40
I am closing this issue as it is a duplicate of https://github.com/dgraph-io/dgraph/issues/1972

**Closed by gpahal** 2018-04-11 09:40 UTC
Labels: ratel
