### ISSUE TITLE
Slash GraphQl password set does not work with capital letters in email address

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/dgraph#5699] opened 2020-06-22 10:23 UTC
### What version of Dgraph are you using?
Slash GraphQl

### Have you tried reproducing the issue with the latest release?
N/A

### What is the hardware spec (RAM, OS)?
N/A

### Steps to reproduce the issue (command/config used to run Dgraph).
I have been invited to the beta version via my email address, which contains capital letters. Following the link from the invitation brings me to a screen to set my password. On entering the password and clicking "Change Password" I get an error:
![grafik](https://user-images.githubusercontent.com/44700269/85277002-f22cec80-b482-11ea-93f7-346941c73037.png)

### Expected behaviour and actual result.
The password should be set.

The problem is that my email address contains capital letters. This produces the following request URL: `https://api.cloud.dgraph.io/user/{EMAIL_ADDRESS}/set-password`

With capital letters in it, it returns HTTP 404, with all lowercase it returns HTTP 200.

**Comment by OmarAyo** [comment] 2020-06-22 13:33
Hi @EnricoMi 

I will try to reproduce your issue, thanks for bringing it up.

Best,
Omar

**Comment by OmarAyo** [comment] 2020-06-22 14:39
Hi @EnricoMi,

I see that you also reported this issue in https://discuss.dgraph.io/t/first-login-to-slash-graphql/7314 and my colleague @akashjain971 has already reproduced it and a fix is on the way.

That said I am closing this ticket as a duplicate of that discuss post.

Best,
Omar

**Closed by OmarAyo** 2020-06-22 14:39 UTC
