### ISSUE TITLE
fatal error: fault. unexpected fault address.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/dgraph#4291] opened 2019-11-19 05:28 UTC
### What version of Dgraph are you using?
master (1ee42ef40)

### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
64 GB. Ubuntu Linux.

### Steps to reproduce the issue (command/config used to run Dgraph).

1. Run Dgraph cluster (1 Alpha, 1 Zero)
2. Run queries and mutations. I was using this load test: https://github.com/igormiletic/dgraphtest/tree/5fa9b0cd1aebe430dd1a5ce2ee4bb636c4eda2ae.
3. Dgraph Alpha process exits with a segfault in the logs. The full log is attached:
[alpha.txt](https://github.com/dgraph-io/dgraph/files/3862029/alpha.txt)

   ```text
   unexpected fault address 0x7f213c5bbdbb
   fatal error: fault
   unexpected fault address 0x7f213c65fddb
   fatal error: fault
   [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f213c5bbdbb pc=0xe40959]
   
   goroutine 520447 [running]:
   runtime.throw(0x1739db8, 0x5)
   	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc040e34860 sp=0xc040e34830 pc=0x93cfe2
   runtime.sigpanic()
   	/usr/local/go/src/runtime/signal_unix.go:401 +0x3de fp=0xc040e34890 sp=0xc040e34860 pc=0x95322e
   github.com/dgraph-io/dgraph/protos/pb.(*Posting).Unmarshal(0xc0a1472000, 0x7f213c5bbdbb, 0xe, 0x7ba44243, 0x0, 0x0)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:15309 +0x69 fp=0xc040e34988 sp=0xc040e34890 pc=0xe40959
   github.com/dgraph-io/dgraph/protos/pb.(*PostingList).Unmarshal(0xc092bb1560, 0x7f213c5bb7e9, 0x640, 0x7ba44815, 0x0, 0x26)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:15917 +0x513 fp=0xc040e34aa0 sp=0xc040e34988 pc=0xe43dd3
   github.com/dgraph-io/dgraph/posting.ReadPostingList.func1(0x7f213c5bb7e9, 0x640, 0x7ba44815, 0x7ba44815, 0xc0a0e66bd0)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:176 +0x74 fp=0xc040e34af8 sp=0xc040e34aa0 pc=0x131cc64
   github.com/dgraph-io/badger.(*Item).Value(0xc044a70dc0, 0xc040e34c00, 0x0, 0x0)
   	/home/dmai/go/pkg/mod/github.com/dgraph-io/badger@v0.0.0-20190917133922-cbdef65095c7/iterator.go:111 +0x1bd fp=0xc040e34ba0 sp=0xc040e34af8 pc=0x114eb7d
   github.com/dgraph-io/dgraph/posting.ReadPostingList(0xc0167403c0, 0x1e, 0x1e, 0xc07021c460, 0x0, 0x64, 0x100)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:174 +0x224 fp=0xc040e34c48 sp=0xc040e34ba0 pc=0x1317c44
   github.com/dgraph-io/dgraph/posting.getNew(0xc0167403c0, 0x1e, 0x1e, 0xc00009d500, 0x0, 0x0, 0x0)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/posting/mvcc.go:217 +0x225 fp=0xc040e34d70 sp=0xc040e34c48 pc=0x1318265
   github.com/dgraph-io/dgraph/posting.(*LocalCache).getInternal(0x0, 0xc0167403c0, 0x1e, 0x1e, 0xc016740301, 0x1e, 0x1e, 0x14)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/posting/lists.go:233 +0x350 fp=0xc040e34de0 sp=0xc040e34d70 pc=0x1316ab0
   github.com/dgraph-io/dgraph/posting.(*LocalCache).Get(...)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/posting/lists.go:267
   github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings.func1(0x0, 0x1, 0x0, 0x945e26)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/worker/task.go:635 +0x23e fp=0xc040e34f80 sp=0xc040e34de0 pc=0x13df54e
   github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings.func2(0xc0659c0420, 0xc07021c3c0, 0x0, 0x1)
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/worker/task.go:751 +0x3a fp=0xc040e34fc0 sp=0xc040e34f80 pc=0x13e097a
   runtime.goexit()
   	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc040e34fc8 sp=0xc040e34fc0 pc=0x96d9b1
   created by github.com/dgraph-io/dgraph/worker.(*queryState).handleUidPostings
   	/home/dmai/go/src/github.com/dgraph-io/dgraph/worker/task.go:750 +0x3c4
   ```

**Comment by animesh2049** [comment] 2019-11-20 13:26
There seems to be something fishy in the stack trace.
>github.com/dgraph-io/dgraph/protos/pb.(*Posting).Unmarshal(0xc0a1472000, 0x7f213c5bbdbb, 0xe, 0x7ba44243, 0x0, 0x0)
/home/dmai/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:15309 +0x69 fp=0xc040e34988 sp=0xc040e34890 pc=0xe40959

Here I am not able to understand the arguments that are passed to `Unmarshal`. I wrote a similar code and saw that the arguments are being passed in a different fashion.
###   Code snippet
```
type Person struct {
	name string
	age  int
}

//go:noinline
func (p *Person) printAge(data []byte) error {
	panic("OOOOOOOOOO")
	fmt.Println(p.age)
	return nil
}

func main() {
	p := Person{name: "Animesh", age: 24}
	arg := []byte{}
	_ = p.printAge(arg)
}
```
### Stack trace
```
panic: OOOOOOOOOO

goroutine 1 [running]:
main.(*Person).printAge(0xc00007ef38, 0xc00007ef37, 0x0, 0x0, 0xc000020178, 0x0)
	/home/animesh/go/src/temp/test.go:14 +0x39
main.main()
	/home/animesh/go/src/temp/test.go:22 +0x69
exit status 2
```
First arguement(`0xc00007ef38`) is address of `p`, second argument(`0xc00007ef37`) is address of `arg`, third and fourth arguments are size and capacity of `arg`. Not sure about fifth and sixth arguments.
But in the stack trace provided fourth argument(`0x7ba44243`) doesn't seem to be the capacity of the byte array.

**Comment by animesh2049** [comment] 2019-11-20 13:41
There seems to be something fishy in the stack trace.
>github.com/dgraph-io/dgraph/protos/pb.(*Posting).Unmarshal(0xc0a1472000, 0x7f213c5bbdbb, 0xe, 0x7ba44243, 0x0, 0x0)
    /home/dmai/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:15309 +0x69 fp=0xc040e34988 sp=0xc040e34890 pc=0xe40959

Here I am not able to understand the arguments that are passed to Unmarshal. I wrote a similar code and saw that the arguments are being passed in a different fashion. I wrote a simple test.
```
diff --git a/protos/pb/pb.pb.go b/protos/pb/pb.pb.go
index 0eaafc25..ff336c88 100644
--- a/protos/pb/pb.pb.go
+++ b/protos/pb/pb.pb.go
@@ -15294,6 +15294,7 @@ func (m *KVS) Unmarshal(dAtA []byte) error {
        return nil
 }
 func (m *Posting) Unmarshal(dAtA []byte) error {
+    panic("OOOOO")
        l := len(dAtA)
        iNdEx := 0
        for iNdEx < l {
diff --git a/protos/pb/pb_test.go b/protos/pb/pb_test.go
new file mode 100644
index 00000000..1d324a0f
--- /dev/null
+++ b/protos/pb/pb_test.go
@@ -0,0 +1,8 @@
+package pb
+
+import "testing"
+
+func TestUnmarshal(t *testing.T) {
+       p := &Posting{}
+       p.Unmarshal([]byte{})
+}
```
The patch above produced this stack trace
```
--- FAIL: TestUnmarshal (0.00s)
panic: OOOO [recovered]
	panic: OOOO

goroutine 7 [running]:
testing.tRunner.func1(0xc000104100)
	/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0x8f9900, 0xa6c250)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/dgraph-io/dgraph/protos/pb.(*Posting).Unmarshal(0xc000048ec0, 0xc000048ebf, 0x0, 0x0, 0x4fe68d, 0xb7d760)
	/home/animesh/go/src/github.com/dgraph-io/dgraph/protos/pb/pb.pb.go:15298 +0x39
github.com/dgraph-io/dgraph/protos/pb.TestUnmarshal(0xc000104100)
	/home/animesh/go/src/github.com/dgraph-io/dgraph/protos/pb/pb_test.go:7 +0x83
testing.tRunner(0xc000104100, 0x9f2778)
	/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:960 +0x350
exit status 2
FAIL	github.com/dgraph-io/dgraph/protos/pb	0.005s
```

First arguement(`0xc000048ec0`) is address of p, second argument(`0xc000048ebf`) is address of argument(*byte array*), third and fourth arguments are size and capacity of arg. Not sure about fifth and sixth arguments.
But in the stack trace provided fourth argument(`0x7ba44243`) doesn't seem to be the capacity of the byte array.

**Comment by danielmai** [comment] 2019-11-21 18:53
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x7f213c5bbdbb pc=0xe40959]

The error message (`addr=0x7f213c5bbdbb`) is only about the second arg.

**Comment by animesh2049** [comment] 2019-11-27 09:27
I was not able to reproduce this issue.

**Comment by sleto-it** [comment] 2020-01-23 10:34
Hi @MichelDiz please could you try to reproduce this?
If you cannot reproduce we will close and reopen in case later

Many Thanks,

**Comment by MichelDiz** [comment] 2020-01-23 19:37
I tried, I got a bunch of errors trying to run the repo files. And I have no experience with Scala to fix it.

**Comment by sleto-it** [comment] 2020-02-24 06:22
We did some additional tests:
- we were able to reproduce the issue (using the load test mentioned in the initial description) on an old 1.1 version, but not on 1.2.1 and on master

We are closing this issue for now. If you see this again in a more recent release, please comment and we will reopen

Many thanks,

**Closed by sleto-it** 2020-02-24 06:22 UTC
Labels: area/crash, kind/bug, status/accepted, status/needs-attention
