### ISSUE TITLE
HTML output in graph window for bad query

### ISSUE THREAD

**Issue by kjnsn** [dgraph-io/dgraph#848] opened 2017-04-18 08:26 UTC
To reproduce, run the following bad query on play.dgraph.io:
```
{
  
  
	actor(id: 0xcbcefccffb9eb400) {
    ~performance.actor {
    name@en
  }
  }
}```

**Comment by sungwoncho** [comment] 2017-05-16 07:49
I could not reproduce using the given query. However I can confirm that this happens when server is down, resulting in `404` Not Found in the UI.

Next release will fix this issue.

**Comment by pawanrawal** [comment] 2017-05-17 00:52
We are thinking of doing the release by Friday. @sungwoncho can this fix go in before that?

**Comment by sungwoncho** [comment] 2017-05-17 00:56
@pawanrawal ok, let's aim for the release by this Friday.

**Comment by manishrjain** [comment] 2017-07-05 04:48
Is this still a thing?

**Comment by manishrjain** [comment] 2017-07-08 03:58
Closing this.

**Closed** 2017-07-08 03:58 UTC
Labels: bug
