### ISSUE TITLE
Data not persisting

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/dgraph#3291] opened 2019-04-14 22:25 UTC
There seems to be an issue where I create data on DGraph. Whilst the server is running, everything operates as if data persists.

However, when I shut down DGraph and restart it, the (some of the) data is gone.

I think it may be related to: https://github.com/dgraph-io/dgraph/issues/3290 but I was assured that it is unrelated.

Here are some logs that I see **after** I restart DGraph:

```
Starting a new membership stream receive from localhost:5080.
I0414 22:10:32.387890      33 draft.go:372] Skipping snapshot at 61, because found one at 61
I0414 22:10:32.393225      33 groups.go:710] Received first state update from Zero: counter:95 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"localhost:7080" last_update:1555279832 > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:1103 > > tablets:<key:"dgraph.type" value:<group_id:1 predicate:"dgraph.type" space:40 > > tablets:<key:"node" value:<group_id:1 predicate:"node" space:15 > > tablets:<key:"node.created_at" value:<group_id:1 predicate:"node.created_at" space:37 > > tablets:<key:"node.hashid" value:<group_id:1 predicate:"node.hashid" space:37 > > tablets:<key:"node.owner" value:<group_id:1 predicate:"node.owner" space:29 > > tablets:<key:"node.parent" value:<group_id:1 predicate:"node.parent" space:29 > > tablets:<key:"node.search_synopsis" value:<group_id:1 predicate:"node.search_synopsis" space:59 > > tablets:<key:"node.search_title" value:<group_id:1 predicate:"node.search_title" space:49 > > tablets:<key:"node.searchable" value:<group_id:1 predicate:"node.searchable" space:45 > > tablets:<key:"node.xdata" value:<group_id:1 predicate:"node.xdata" space:27 > > tablets:<key:"user" value:<group_id:1 predicate:"user" space:210 > > tablets:<key:"user.code" value:<group_id:1 predicate:"user.code" space:256 > > tablets:<key:"user.created_at" value:<group_id:1 predicate:"user.created_at" space:307 > > tablets:<key:"user.email" value:<group_id:1 predicate:"user.email" space:490 > > tablets:<key:"user.name" value:<group_id:1 predicate:"user.name" space:445 > > tablets:<key:"user.password" value:<group_id:1 predicate:"user.password" space:432 > > tablets:<key:"user.validated" value:<group_id:1 predicate:"user.validated" space:322 > > snapshot_ts:40003 checksum:9373435897747303801 > > zeros:<key:1 value:<id:1 addr:"localhost:5080" leader:true > > maxLeaseId:30000 maxTxnTs:50000 maxRaftId:1 cid:"4d78608e-e57b-492c-af20-0202c2b6c6cf" 
W0414 22:10:32.396559      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 _predicate_ 20002  0 0}
W0414 22:10:32.398756      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.created_at 20002  0 0}
W0414 22:10:32.399391      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.email 20002  0 0}
W0414 22:10:32.400218      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{2 user.email 0 
                                                                                                                 �f\a�S/~�m���/�`i��n4b�Yc��K 0 0}
W0414 22:10:32.400855      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.password 20002  0 0}
W0414 22:10:32.401749      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user 20002  0 0}
W0414 22:10:32.402348      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.code 20002  0 0}
W0414 22:10:32.403107      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.name 20002  0 0}
W0414 22:10:32.403861      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{2 user.name 0 
                                                                                                                j�
                                                                                                                  ��HBi;��(�A����Ȱ_D3)
                                                                                                                                      �d 0 0}
W0414 22:10:32.404726      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.validated 20002  0 0}
W0414 22:10:32.405051      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{2 user.validated 0 	 0 0}
I0414 22:10:36.008815      33 node.go:85] 1 is starting a new election at term 6
I0414 22:10:36.008929      33 node.go:85] 1 became pre-candidate at term 6
I0414 22:10:36.008964      33 node.go:85] 1 received MsgPreVoteResp from 1 at term 6
I0414 22:10:36.009058      33 node.go:85] 1 became candidate at term 7
I0414 22:10:36.009096      33 node.go:85] 1 received MsgVoteResp from 1 at term 7
I0414 22:10:36.009192      33 node.go:85] 1 became leader at term 7
I0414 22:10:36.009236      33 node.go:85] raft.node: 1 elected leader 1 at term 7
I0414 22:10:36.014370      33 mutation.go:148] Done schema update predicate:"_predicate_" value_type:STRING list:true 
I0414 22:10:36.255015      33 mutation.go:148] Done schema update predicate:"dgraph.type" value_type:STRING directive:INDEX tokenizer:"exact" list:true 
I0414 22:10:36.389485      33 groups.go:755] Leader idx=0x1 of group=1 is connecting to Zero for txn updates
I0414 22:10:36.389695      33 groups.go:764] Got Zero leader: localhost:5080
starting lemma-chain...
I0414 22:10:45.107015      33 server.go:284] Received ALTER op: schema:"\n\t\tuser: bool .\n\t\tuser.name: string @index(hash) .\n\t\tuser.email: string @index(hash) .\n\t\tuser.password: password .\n\t\tuser.code: string . \n\t\tuser.created_at: dateTime .\n\t\tuser.validated: bool @index(bool) .\n\n\t\tnode: bool .\n\t\tnode.hashid: string @index(hash) . \n\t\tnode.owner: uid @reverse . \n\t\tnode.parent: uid . \n\t\tnode.xdata: string . \n\t\tnode.searchable: bool @index(bool) . \n\t\tnode.search_title: string @index(term) .\n\t\tnode.search_synopsis: string @index(fulltext) .\n\t\tnode.created_at: dateTime .\n\t" 
I0414 22:10:45.107129      33 server.go:704] Got Alter request from "127.0.0.1:37826"
I0414 22:10:45.111589      33 server.go:367] Got schema: [predicate:"user" value_type:BOOL  predicate:"user.name" value_type:STRING directive:INDEX tokenizer:"hash"  predicate:"user.email" value_type:STRING directive:INDEX tokenizer:"hash"  predicate:"user.password" value_type:PASSWORD  predicate:"user.code" value_type:STRING  predicate:"user.created_at" value_type:DATETIME  predicate:"user.validated" value_type:BOOL directive:INDEX tokenizer:"bool"  predicate:"node" value_type:BOOL  predicate:"node.hashid" value_type:STRING directive:INDEX tokenizer:"hash"  predicate:"node.owner" value_type:UID directive:REVERSE  predicate:"node.parent" value_type:UID  predicate:"node.xdata" value_type:STRING  predicate:"node.searchable" value_type:BOOL directive:INDEX tokenizer:"bool"  predicate:"node.search_title" value_type:STRING directive:INDEX tokenizer:"term"  predicate:"node.search_synopsis" value_type:STRING directive:INDEX tokenizer:"fulltext"  predicate:"node.created_at" value_type:DATETIME ]
E0414 22:10:45.114872      33 draft.go:521] Lastcommit 40007 > current 10004. This would cause some commits to be lost.
```

**Comment by pjebs** [comment] 2019-04-14 22:26
I am using latest commit from master of Docker and building it myself.

**Comment by danielmai** [comment] 2019-04-15 18:01
> `W0414 22:10:32.398756      33 mvcc.go:121] Existing >= Commit [40007 >= 40007]. Skipping write: &{0 user.created_at 20002  0 0}`

After a restart Dgraph will replay the write-ahead logs from the latest snapshot. This will apply the latest writes if necessary. If the write already exists, then the above warning log appears. But you'll be able to query for any data you've written already irrespective of the warnings.

Please share a series of mutations and queries that show that queries don't return the expected results based on the mutations. Otherwise, this is not an issue. These logs after a restart are normal.

**Comment by pjebs** [comment] 2019-04-15 21:22
The last line seems to imply that data is lost:
```
E0414 22:10:45.114872      33 draft.go:521] Lastcommit 40007 > current 10004. This would cause some commits to be lost.
```

**Comment by danielmai** [comment] 2019-04-15 21:26
The log is normal when replaying the write-ahead log after a restart since the latest commit on disk is later than what's in the WAL.

**Comment by pjebs** [comment] 2019-04-15 23:23
I have DGraph running in background of docker container. In the same container I have another application running (my REST API) in foreground.

If I send SIGINT (Ctrl+C on mac), it quits my application. I believe docker will then stop the container. Will this possibly cause DGraph to not save my data correctly?

**Comment by pjebs** [comment] 2019-04-15 23:23
I'm just exploring and trying to figure out if this is a bug in DGraph or my side.

**Comment by danielmai** [comment] 2019-04-15 23:45
A single SIGINT cleanly shuts down the Dgraph instance. You can try out some scenarios involving mutations, queries, and restarts and see how they play out for yourself. e.g., you can start Dgraph, run a mutation, run a query, restart Dgraph, and then run the same query. The query responses should be the same.

I'll close this issue since this is not reporting an issue with Dgraph. For further questions create a topic at https://discuss.dgraph.io.

**Closed by danielmai** 2019-04-15 23:45 UTC

**Comment by pjebs** [comment] 2019-04-16 00:31
@danielmai I can't help but think it's a DGraph issue. I ran the same docker image simultaneously where both share the same mounted data directory. 

When I create a mutation in 1 container and then query for it, it appears in that container. But the second container can't see the mutation.

I tried the same experiment on second container and same issue from the first container.

**Comment by danielmai** [comment] 2019-04-16 00:46
Can you share the Docker configuration and commands you ran that reproduces what you're seeing?
