### ISSUE TITLE
Join cluster fail

### ISSUE THREAD

**Issue by catroot** [dgraph-io/dgraph#2075] opened 2018-02-01 13:32 UTC
I`m about to add hosts to my zero instance, but got this:

```
2018/02/01 17:32:03 oracle.go:375: No healthy connection found to leader of group 2
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
2018/02/01 17:32:03 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
2018/02/01 17:32:13 oracle.go:375: No healthy connection found to leader of group 3
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:13 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
2018/02/01 17:32:23 oracle.go:375: No healthy connection found to leader of group 2
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.168:9080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2018/02/01 17:32:23 pool.go:168: Echo error from 192.168.8.174:9080. Err: rpc error: code = Unimplemented desc = unknown service intern.Raft
```

All nodes are fresh nightly builds.

Additionaly, when i pass --idx=4 parameter i got this on zero node:
```
2018/02/01 17:51:58 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:58 zero.go:412: Connected
2018/02/01 17:51:58 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:51:58 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:58 zero.go:412: Connected
2018/02/01 17:51:58 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:51:58 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:58 zero.go:412: Connected
2018/02/01 17:51:58 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:51:58 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:58 zero.go:412: Connected
2018/02/01 17:51:58 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:51:58 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:58 zero.go:412: Connected
2018/02/01 17:51:59 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:51:59 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:51:59 zero.go:412: Connected
2018/02/01 17:52:01 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:52:01 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:52:01 zero.go:412: Connected
2018/02/01 17:52:04 zero.go:322: Got connection request: id:4 addr:"192.168.8.174:9080"
2018/02/01 17:52:04 raft.go:531: While applying proposal: Invalid address
2018/02/01 17:52:04 zero.go:412: Connected
```

**Comment by unknown321** [comment] 2018-02-01 14:03
Are you sure you are using right ports to connect? They were changed a couple of days ago, see https://github.com/dgraph-io/dgraph/commit/998b870f2767df889f4a5e878346f5d87d67def8. You should also post command line parameters you are using to launch the nodes.

**Comment by catroot** [comment] 2018-02-01 15:15
Dgraph zero startup:
`dgraph zero --port_offset -2000 --my 192.168.8.172:3080`

Dgraph server startups:
`dgraph server --memory_mb 1048 --zero 192.168.8.172:3080 --my 192.168.8.172:9080`
`dgraph server --memory_mb 1048 --zero 192.168.8.172:3080 --my 192.168.8.173:9080`
`dgraph server --memory_mb 1048 --zero 192.168.8.172:3080 --my 192.168.8.174:9080`

Nowhere to stuck here.

**Comment by sboorlagadda** [comment] 2018-02-01 22:36
@catroot Are you running all the three `dgraph servers` on a single host?

**Comment by pawanrawal** [comment] 2018-02-01 22:41
Yeah, my port should be `7080` as you already figured out @catroot.

**Comment by catroot** [comment] 2018-02-02 08:16
@sboorlagadda no, there are different ones.
@pawanrawal yes, it works now. But without --my option it wont:
```
dgraph server --memory_mb 1048 --zero 192.168.8.172:3080
2018/02/02 12:14:48 groups.go:86: Current Raft Id: 0
2018/02/02 12:14:48 gRPC server started.  Listening on port 9080
2018/02/02 12:14:48 HTTP server started.  Listening on port 8080
2018/02/02 12:14:48 worker.go:99: Worker listening at address: [::]:7080
2018/02/02 12:14:48 pool.go:118: == CONNECT ==> Setting 192.168.8.172:3080
2018/02/02 12:14:48 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:48 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:48 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:48 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:49 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2018/02/02 12:14:51 groups.go:102: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address

```

**Comment by catroot** [comment] 2018-02-02 14:10
After deleting all data filders on all server and zero nodes while trying to load data again:
```
 dgraph live -r 21million.rdf.gz --zero 192.168.8.172:3080

Processing 21million.rdf.gz
Total Txns done:        0 RDFs per second:   14981 Time Elapsed: 2s, Aborts: 0
2018/02/02 18:07:13 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [860000]
Total Txns done:        0 RDFs per second:    9994 Time Elapsed: 4s, Aborts: 1
2018/02/02 18:07:15 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [860000]
2018/02/02 18:07:15 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [860000]
Total Txns done:        0 RDFs per second:    8330 Time Elapsed: 6s, Aborts: 3
2018/02/02 18:07:17 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [870000]
2018/02/02 18:07:17 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1310265] cannot be greater than lease: [870000]
2018/02/02 18:07:17 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [870000]
Total Txns done:        0 RDFs per second:    7498 Time Elapsed: 8s, Aborts: 6
2018/02/02 18:07:19 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [890000]
2018/02/02 18:07:19 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1310265] cannot be greater than lease: [890000]
2018/02/02 18:07:19 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1640361] cannot be greater than lease: [890000]
2018/02/02 18:07:19 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [890000]
Total Txns done:        0 RDFs per second:    6998 Time Elapsed: 10s, Aborts: 10
2018/02/02 18:07:22 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [890000]
2018/02/02 18:07:22 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1470516] cannot be greater than lease: [890000]
2018/02/02 18:07:22 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1310265] cannot be greater than lease: [890000]
2018/02/02 18:07:22 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [890000]
2018/02/02 18:07:22 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1640361] cannot be greater than lease: [890000]
Total Txns done:        0 RDFs per second:    6665 Time Elapsed: 12s, Aborts: 15
Total Txns done:        0 RDFs per second:    5713 Time Elapsed: 14s, Aborts: 15
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [890000]
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1310265] cannot be greater than lease: [890000]
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1470516] cannot be greater than lease: [890000]
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [890000]
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1620620] cannot be greater than lease: [890000]
2018/02/02 18:07:24 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1640361] cannot be greater than lease: [890000]
Total Txns done:        0 RDFs per second:    5624 Time Elapsed: 16s, Aborts: 21

```

**Comment by catroot** [comment] 2018-02-03 07:38
And finally segmentation violation exception. After somehow data was loaded i leaved my cluster for a night to have some sleep and what we have on the next morning?
```
2018/02/03 09:20:20 predicate_move.go:152: Sent 7 number of keys for predicate type.property.reverse_property
2018/02/03 09:28:17 predicate_move.go:152: Sent 9 number of keys for predicate gross_revenue
2018/02/03 09:36:27 predicate_move.go:152: Sent 8 number of keys for predicate song.films
2018/02/03 09:44:31 predicate_move.go:152: Sent 4 number of keys for predicate company_role_or_service.companies_performing_this_role_or_service
2018/02/03 09:52:39 predicate_move.go:152: Sent 4 number of keys for predicate topic_server.webref_cluster_members_type
2018/02/03 10:00:27 predicate_move.go:152: Sent 4 number of keys for predicate content_rating.rating_system
2018/02/03 10:08:24 predicate_move.go:152: Sent 5 number of keys for predicate locations
2018/02/03 10:16:35 predicate_move.go:152: Sent 4 number of keys for predicate filming
2018/02/03 10:24:24 predicate_move.go:152: Sent 2 number of keys for predicate festival.date_founded
2018/02/03 10:32:21 predicate_move.go:152: Sent 2 number of keys for predicate personal_appearance.type_of_appearance
2018/02/03 10:33:47 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2018/02/03 10:40:23 predicate_move.go:152: Sent 2 number of keys for predicate content_rating.minimum_accompanied_age
2018/02/03 10:48:21 predicate_move.go:152: Sent 3 number of keys for predicate pre_production
2018/02/03 10:53:20 groups.go:296: Asking if I can serve tablet for: pre_production
2018/02/03 10:53:29 groups.go:453: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/02/03 10:53:30 groups.go:453: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2018/02/03 10:56:26 predicate_move.go:152: Sent 3 number of keys for predicate pre_production
2018/02/03 10:59:12 node.go:400: WARN: A tick missed to fire. Node blocks too long!
2018/02/03 11:04:36 predicate_move.go:152: Sent 2 number of keys for predicate cut.runtime
2018/02/03 11:12:24 predicate_move.go:152: Sent 2 number of keys for predicate collection.films_in_collection
2018/02/03 11:20:23 predicate_move.go:152: Sent 2 number of keys for predicate crew_gig.crewmember
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc0ce47]

goroutine 1392452 [running]:
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Item).Value(0x0, 0xc4200e4520, 0xc4200e4520, 0x1, 0x0, 0x1a0ba00)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/iterator.go:85 +0x37
github.com/dgraph-io/dgraph/worker.movePredicateHelper(0x1a16000, 0xc463198a20, 0xc433bde300, 0x5, 0x2, 0x0, 0x0)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/predicate_move.go:139 +0x642
github.com/dgraph-io/dgraph/worker.(*grpcWorker).MovePredicate(0xc420064e90, 0x1a16000, 0xc463198a20, 0xc4bb04c0c0, 0xc420064e90, 0xc4bb02e0d0, 0xc4bb033968)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/worker/predicate_move.go:286 +0x23b
github.com/dgraph-io/dgraph/protos/intern._Worker_MovePredicate_Handler(0x12afa20, 0xc420064e90, 0x1a16000, 0xc463198a20, 0xc4bb02e070, 0x0, 0x0, 0x0, 0x7fa710845688, 0x100000000000000)
        /home/travis/gopath/src/github.com/dgraph-io/dgraph/protos/intern/internal.pb.go:2700 +0x276
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4257b9080, 0x1a19500, 0xc42013a480, 0xc4c0640140, 0xc4201504e0, 0x1a002c8, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:900 +0x9d3
google.golang.org/grpc.(*Server).handleStream(0xc4257b9080, 0x1a19500, 0xc42013a480, 0xc4c0640140, 0x0)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:1122 +0x1528
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420076530, 0xc4257b9080, 0x1a19500, 0xc42013a480, 0xc4c0640140)
        /home/travis/gopath/src/google.golang.org/grpc/server.go:617 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/src/google.golang.org/grpc/server.go:615 +0xa1

```
The node which tied to engulf all data died. Amen.

**Comment by pawanrawal** [comment] 2018-02-09 01:34
> 2018/02/02 18:07:15 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1010001] cannot be greater than lease: [860000]
> 2018/02/02 18:07:15 batch.go:133: Error while mutating rpc error: code = Unknown desc = Uid: [1370131] cannot be greater than lease: [860000]

Dgraph live stores a mapping fo `xid` => `uid` in `x` folder. Delete that as well. The above errors are caused because you deleted `p` and `w` directories on the server but did not delete the `x` directory before reloading data.

> I guess there is no fault-tolerance since predicates get moved between nodes once in 5 min. No shards, no replicas, no quorum, no fault tolerance.

Dgraph Zero takes in a `--replicas` flag. I'd suggest reading [the docs](https://docs.dgraph.io/deploy/#understanding-dgraph-cluster) to learn more about sharding and replication. If you think something isn't clear let us know and we can improve it.

Is the panic error that you shared in the last comment reproducible with the latest version (1.0.3)? Can you share some steps to reproduce if it is?

**Comment by pawanrawal** [comment] 2018-02-12 01:19
@catroot I was able to reduce the panic and have created an issue at #2112. I have a fix that I will merge soon.

**Comment by pawanrawal** [comment] 2018-02-12 02:38
I have a fix in https://github.com/dgraph-io/dgraph/pull/2114. I will update the nightly binaries once the fix has been merged.

**Comment by pawanrawal** [comment] 2018-03-06 06:34
Closing this for now. Feel free to reopen if you are still seeing any of these issues with `master`.

**Closed by pawanrawal** 2018-03-06 06:34 UTC
Labels: investigate
