### ISSUE TITLE
Unable to find dir: stat /home/vagrant/dgraph/m: no such file or directory

### ISSUE THREAD

**Issue by pluradj** [dgraph-io/dgraph#136] opened 2016-07-14 17:21 UTC
Following directions for [running single instance](https://wiki.dgraph.io/Beginners_Guide#Single_Instance_3), I ran into this:

```
$ mkdir ~/dgraph
$ dgraph --mutations ~/dgraph/m --postings ~/dgraph/p --uids ~/dgraph/u
2016/07/14 17:18:45 num_cpu: 2. prev_maxprocs: 2. Set max procs to num cpus
2016/07/14 17:18:45 Unable to find dir: stat /home/vagrant/dgraph/m: no such file or directory
```

Creating `~/graph/m` resolves the issue.

**Comment by mohitranka** [comment] 2016-07-14 17:39
Closing this issue.

**Comment by manuel-delverme** [comment] 2016-08-09 15:56
still happening, update the wiki example if it's not a bug

from the wiki:
```
$ mkdir ~/dgraph
$ dgraph --mutations ~/dgraph/m --postings ~/dgraph/p --uids ~/dgraph/u
```
to
`$ mkdir -p ~/dgraph/m`

**Comment by manishrjain** [comment] 2016-08-10 01:03
Looks like it's still an issue. Reopening.

**Comment by pawanrawal** [comment] 2016-09-21 05:45
Cannot reproduce in `v0.4.4`. @ashwin95r could you verify this too on a fresh instance? We can close this then.

**Comment by ashwin95r** [comment] 2016-09-21 07:14
Verified on my machine. Cannot reproduce on master. The directories are created if missing. So closing this.

**Closed by ashwin95r** 2016-09-21 07:14 UTC
Labels: bug
