### ISSUE TITLE
wrong results in term matching

### ISSUE THREAD

**Issue by MichaelJCompton** [dgraph-io/dgraph#1001] opened 2017-06-01 05:11 UTC
On play.dgraph.io run

```
{
  me(func: allofterms(name@en, "neve")) {
    name@en
  }
}
```

Some of the results are "Buddy Goes West", "The Name of the Rose" and "Aliens".

Same goes for anyofterms, but not FTS.

**Comment by MichaelJCompton** [comment] 2017-06-01 06:23
Another example.

I'm looking for the movie 'Eat Drink Man Woman'

```
{
	edmw(func: allofterms(name@en, "Eat Drink Man Woman")) {
    name@en
  }
}
```
returns no results

but
```
{
	edmw(func: allofterms(name@en, "Eat Drink")) {
    name@en
  }
}
```
finds the movie

while
```
{
	edmw(func: allofterms(name@en, "Man Woman")) {
    name@en
  }
}
```
finds other things with 'man' and 'woman', but not this movie.

**Comment by pawanrawal** [comment] 2017-06-02 05:00
This was caused by a bug in the filtering logic for uids when predicate had a lang tag. The fix was has been merged to `release/v0.7.7` and `master`.

**Closed by pawanrawal** 2017-06-02 05:00 UTC
