### ISSUE TITLE
Allow variable value to parameters in @recurse directive

### ISSUE THREAD

**Issue by amandalmia14** [dgraph-io/dgraph#3848] opened 2019-08-22 04:32 UTC
In this example - https://github.com/dgraph-io/pydgraph/blob/master/examples/simple/simple.py

At the method,   
```
def query_data(client):
```

you have mentioned  ```variables = {'$a': 'Alice'}```, but is it possible to pass multiple data, like ```depth``` along with the name?

```
query = """query get_all($a: string, $b: integer) { get_all(func: anyoftext(name@en, $a))@recurse(depth: $b) {
        uid
        name@en
        normalizes_to {name@en normalizes_to {name@en}}
        ~normalizes_to {name@en normalizes_to {name@en}
     }
variables = {'$a': keywords, '$b': 5}
```
where ```keywords``` is  a list of words and ```depth``` is an integer.
If I do that I am getting an error,  as 

```Exception: Values and keys in variable map must be strings```

If I hard code in the query, 

```
query = """query get_all($a: string) { get_all(func: anyoftext(name@en, $a))@recurse(depth: 5) {
        uid
        name@en
        normalizes_to {name@en normalizes_to {name@en}}
        ~normalizes_to {name@en normalizes_to {name@en}
     }
variables = {'$a': keywords}
```

It works  !!

Please follow the discuss.dgraph.com thread in order to know the current status. [Link](https://discuss.dgraph.io/t/configuring-depth-in-the-variables-when-passing-through-the-query/4751/8)

I got to know that currently dgraph team doesn't support depth value to be passed as a variable argument.

@mangalaman93 Can you please tag to the concern person for this issue? Thanks

**Comment by mangalaman93** [comment] 2019-08-22 04:59
The problem here is that Dgraph currently does not support passing a variable value for depth argument in @recurse. It is perfectly fine to pass multiple data (all string encoded, Dgraph does parsing based on the type provided).

Meaning -
```
query = """query get_all($a: string, $b: integer) { get_all(func: anyoftext(name@en, $a))@recurse(depth: $b) {
        uid
        name@en
        normalizes_to {name@en normalizes_to {name@en}}
        ~normalizes_to {name@en normalizes_to {name@en}
     }
variables = {'$a': keywords, '$b': 5}
```

This doesn't work because you are expected to pass `5` in string i.e. `"5"`. Dgraph will convert it into integer value `5`.

Here, the feature request is to support variable arguments to parameters in `@recurse`, something that we could potentially support in future.

**Comment by campoy** [comment] 2019-09-13 18:46
Closing as duplicate of #3301 and marking it as popular.

**Closed by campoy** 2019-09-13 18:46 UTC
Labels: area/querylang, area/querylang/recurse, area/querylang/vars, kind/feature, priority/P2
