### ISSUE TITLE
Deletions don't appear inside of a transaction until commit

### ISSUE THREAD

**Issue by hherman1** [dgraph-io/dgraph#3721] opened 2019-07-24 20:44 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.16

- Have you tried reproducing the issue with latest release?
No

- What is the hardware spec (RAM, OS)?
Running inside of a docker container on Mac, host machine has 16GB ram. Running on Mac OS X Mojave

- Steps to reproduce the issue (command/config used to run Dgraph).
I'm using the docker-compose.yml from the get started page and the Java client. To repro the issue first commit some data to Dgraph. The data I used all have an edge called something like "edge". Then open a new transaction and at the beginnig run a query like:

Query 1:
```
{
    data(func: has(edge)) {
        uid
    }
}
```

To fetch all the data that exists of the type you added. Then issue deletes for all of the uids returned from this query (inside the same transaction) using the JSON syntax of the form: 

```
{
    "delete": [
        { "uid": <result>}, ... repeat
    ]
}
```

Finally, still inside the original transaction, without issuing a commit, reissue the first query.

If you commit this transaction then in a new transaction issue query 1, you get the expected outcome.

- Expected behaviour and actual result.
Expect that the first time you call query 1 you would see many uids from the system, and the second time you would not. However, until you commit the query the deletes are not visible inside of your transaction.

**Comment by martinmr** [comment] 2019-07-24 21:41
Just to clarify, I'll rewrite the operations in the order I understood them. Let me know if I got something wrong.

- Transaction 1
  - Add data.
  - Commit.
- Transaction 2 (started after 1 is committed)
  - Query data (data is seen)
  - Use query to delete data
  - Run query but get the same results as before
  - Run query and get the same results before the deletion.
  - Commit
- Transaction 3
  - Run query, deletes are applied.

If this timeline is correct, then this is not a bug but rather an inconvenience caused by the internal design of Dgraph of which we are already aware. Most likely the data you added in transaction 1 created some indices, but the delete in transaction 2 deleted the data but not the indices so it's possible to get query results that seem inconsistent. It's not until you commit a transaction that all the changes both to the data and the indices will be applied. In general, the recommended and supported flow of operations inside a transaction is create - read -mutate - commit/abort. Multiple read - mutate pairs of operations on the same data inside the same transaction can lead to stuff like this.

Let me know if the timeline above is right. Also, I believe this limitation can probably be addressed better in the documentation so I'll open a PR to better clarify this situation there.

**Comment by martinmr** [comment] 2019-07-24 21:52
Actually, I took a look at your query and it's using the `has` function, which does not use any indices. The previous issue I remember seeing related to seeing changes within the same transaction only applied to secondary indices (https://github.com/dgraph-io/dgraph/issues/3103).

@manishrjain: @danielmai and I ran some example transactions and the changes within the same transaction cannot be seen by it (regardless whether they are sets or deletes). Should this be the case? 

@hherman1 For now only do one read and mutate per transaction just to be safe.

**Comment by hherman1** [comment] 2019-07-24 21:56
Thanks for the prompt reply @martinmr, and confirming that the timeline you posted is accurate. Also, I may be misunderstanding the docs but shouldn't the delete syntax I use also delete from indices? (see `S * *` in https://docs.dgraph.io/mutations/#delete or https://docs.dgraph.io/mutations/#deleting-edges for the JSON version)

Appreciate the docs PR. Also perhaps it makes sense to update the https://docs.dgraph.io/mutations/#deleting-edges documentation to clarify that the JSON call with no predicates specified will delete both edges and literal values (which for my use case is the desired behavior, but I had to test it to verify thats what happens).

**Comment by martinmr** [comment] 2019-07-24 22:21
The delete syntax deletes the indices but the change is not applied until the transaction is committed. Which is what issue #3103 was about.

But in your case, you are using the `has` function, which does not use indices so I am still not sure if the same logic applies. I'll wait for @manishrjain to confirm before modifying the docs.

With regards to the delete JSON syntax, I'll see if I can make the docs clearer. What you saw is the intended behavior.

**Closed** 2020-04-06 17:35 UTC
Labels: area/operations
