### ISSUE TITLE
Multiple groot users

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/dgraph#3354] opened 2019-05-02 00:41 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
master

- Have you tried reproducing the issue with latest release?
yes

- Steps to reproduce the issue (command/config used to run Dgraph).
I ran the snapshot test in a loop ten times and one of the runs failed due to an ACL error. To reproduce the error do the following.

- Run this command from the repo root `cd ./dgraph && docker-compose up`
- In a separate terminal run `for i in $(seq 1 10); go test -v ./worker -run=TestSnapshot -count=1; done`

- Expected behaviour and actual result.
Tests pass. One of the tests failed with the following error.

```
2019/05/01 17:23:19 rpc error: code = Unknown desc = Authentication from address 172.19.0.1:37700 failed: error while querying user with id groot: Found multiple users: {"user":[{"uid":"0x20dc","dgraph.xid":"groot","password_match":true},{"uid":"0x252f","dgraph.xid":"groot","password_match":true}]}
```

My suspicion is that when DropAll at the start of the test happens the groot user might not correctly deleted.

**Comment by gitlw** [comment] 2019-05-08 01:16
I tried the for loop twice, i.e. a total of 20 runs of the test, and couldn't reproduce the problem.
Closing this issue for now.

**Closed by gitlw** 2019-05-08 01:16 UTC
Labels: bug
