### ISSUE TITLE
Mutation with multiple deletions aborts

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#1958] opened 2017-12-26 15:48 UTC
Run the following two mutations in Dgraph UI (running Dgraph 1.0.1)

```
{ set {
  _:node <typePerson> "" .
  _:node <__typename> "Person" .
  _:node <name> "Tim" .
  _:node <children> _:node0 .
  _:node0 <parents> _:node .
  _:node0 <typePerson> "" .
  _:node0 <__typename> "Person" .
  _:node0 <name> "Jerry" .
  _:node0 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node0 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <children> _:node1 .
  _:node1 <parents> _:node .
  _:node1 <typePerson> "" .
  _:node1 <__typename> "Person" .
  _:node1 <name> "Olivia" .
  _:node1 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node1 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <children> _:node2 .
  _:node2 <parents> _:node .
  _:node2 <typePerson> "" .
  _:node2 <__typename> "Person" .
  _:node2 <name> "Paul" .
  _:node2 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node2 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node <updatedAt> "2017-12-26T15:36:16.466Z" .
}}
```

Then (substituting `uids`)

```
{ delete {
  <node> <children> <node0> .
  <node0 > <parents> <node> .
  <node> <children> <node1> .
  <node1> <parents> <node> .
}}
```

**Comment by janardhan1993** [comment] 2017-12-26 22:40
@dpeek : Can you also share your schema ?

**Comment by dpeek** [comment] 2017-12-26 22:56
```
dob: dateTime @index(hour) .
lastActiveAt: dateTime @index(hour) .
name: string @index(exact,term) .
title: string @index(exact) .
employed: bool @index(bool) .
time: int @index(int) .
age: int @index(int) .
height: float @index(float) .
partner: uid .
children: uid .
parents: uid .
createdAt: dateTime @index(hour) .
updatedAt: dateTime @index(hour) .
```

**Comment by dpeek** [comment] 2017-12-26 22:58
I'm running in docker with this `docker-compose.yml`:

```
version: '3'

services:
  zero:
    image: dgraph/dgraph:v1.0.1
    command: dgraph zero --port_offset -2000 --my=zero:5080
    restart: on-failure
    volumes:
      - dgraph:/dgraph
  server:
    image: dgraph/dgraph:v1.0.1
    command: dgraph server --my=server:7080 --memory_mb=2048 --zero=zero:5080
    restart: on-failure
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
  ui:
    image: dgraph/dgraph:v1.0.1
    command: dgraph-ratel
    restart: on-failure
    ports:
      - 8081:8081
volumes:
  dgraph:
```

**Comment by janardhan1993** [comment] 2017-12-27 01:22
@dpeek : I couldn't reproduce this, can you please list down the steps you did.

**Comment by dpeek** [comment] 2017-12-27 11:43
Very strange. Turns out it has nothing to do with multiple deletions – any deletion results in an aborted transaction. Weirdly, other mutations and queries work fine (*most* of my test suite is passing, only deletion cases are failing which is how we got here).

I suspect I've got my docker-compose configured incorrectly, I'm really just guessing when it comes to docker. There are a bunch of errors during startup, perhaps they will point you at what I'm doing wrong...

```
Starting dgraphql_zero_1 ...
Starting dgraphql_zero_1
Starting dgraphql_ui_1 ...
Starting dgraphql_ui_1
Starting dgraphql_server_1 ...
Starting dgraphql_server_1 ... done
Attaching to dgraphql_ui_1, dgraphql_zero_1, dgraphql_server_1
ui_1      | 2017/12/27 11:39:47 Listening on port 8081...
zero_1    | Setting up grpc listener at: 0.0.0.0:5080
zero_1    | Setting up http listener at: 0.0.0.0:6080
zero_1    | 2017/12/27 11:39:47 node.go:233: Found Snapshot, Metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:15332 Term:18 XXX_unrecognized:[]}
zero_1    | 2017/12/27 11:39:47 node.go:248: Found hardstate: {Term:31 Vote:1 Commit:15541 XXX_unrecognized:[]}
zero_1    | 2017/12/27 11:39:47 node.go:260: Group 0 found 209 entries
zero_1    | 2017/12/27 11:39:47 raft.go:400: Restarting node for dgraphzero
server_1  | 2017/12/27 11:39:48 gRPC server started.  Listening on port 9080
server_1  | 2017/12/27 11:39:48 HTTP server started.  Listening on port 8080
server_1  | 2017/12/27 11:39:48 groups.go:94: Current Raft Id: 1
server_1  | 2017/12/27 11:39:48 worker.go:99: Worker listening at address: [::]:7080
server_1  | 2017/12/27 11:39:48 pool.go:118: == CONNECT ==> Setting zero:5080
zero_1    | 2017/12/27 11:39:48 pool.go:118: == CONNECT ==> Setting server:7080
zero_1    | 2017/12/27 11:39:48 raft.go:567: INFO: 1 became follower at term 31
zero_1    | 2017/12/27 11:39:48 raft.go:315: INFO: newRaft 1 [peers: [1], term: 31, commit: 15541, applied: 15332, lastindex: 15541, lastterm: 31]
zero_1    | Running Dgraph zero...
zero_1    | 2017/12/27 11:39:48 zero.go:316: Got connection request: id:1 addr:"server:7080"
zero_1    | 2017/12/27 11:39:48 zero.go:412: Connected
server_1  | 2017/12/27 11:39:48 groups.go:117: Connected to group zero. Connection state: member:<id:1 addr:"server:7080" > state:<counter:15337 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"server:7080" leader:true last_update:1514301497 > > tablets:<key:"__typename" value:<group_id:1 predicate:"__typename" space:54970 > > tablets:<key:"_dummy_" value:<group_id:1 predicate:"_dummy_" space:19 > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" space:57501 > > tablets:<key:"address" value:<group_id:1 predicate:"address" space:582 > > tablets:<key:"age" value:<group_id:1 predicate:"age" space:6978 > > tablets:<key:"children" value:<group_id:1 predicate:"children" space:5783 > > tablets:<key:"config" value:<group_id:1 predicate:"config" space:707 > > tablets:<key:"createdAt" value:<group_id:1 predicate:"createdAt" space:73660 > > tablets:<key:"dob" value:<group_id:1 predicate:"dob" space:778 > > tablets:<key:"emails" value:<group_id:1 predicate:"emails" space:313 > > tablets:<key:"emergencyContact" value:<group_id:1 predicate:"emergencyContact" space:1339 > > tablets:<key:"employed" value:<group_id:1 predicate:"employed" space:7468 > > tablets:<key:"height" value:<group_id:1 predicate:"height" space:7165 > > tablets:<key:"lastActiveAt" value:<group_id:1 predicate:"lastActiveAt" space:850 > > tablets:<key:"name" value:<group_id:1 predicate:"name" space:62710 > > tablets:<key:"parents" value:<group_id:1 predicate:"parents" space:7381 > > tablets:<key:"partner" value:<group_id:1 predicate:"partner" space:7842 > > tablets:<key:"schema" value:<group_id:1 predicate:"schema" space:7380 > > tablets:<key:"time" value:<group_id:1 predicate:"time" space:13924 > > tablets:<key:"title" value:<group_id:1 predicate:"title" space:890 > > tablets:<key:"type" value:<group_id:1 predicate:"type" space:709 > > tablets:<key:"typeEmail" value:<group_id:1 predicate:"typeEmail" space:280 > > tablets:<key:"typePerson" value:<group_id:1 predicate:"typePerson" space:27757 > > tablets:<key:"typeSchemaUpdate" value:<group_id:1 predicate:"typeSchemaUpdate" space:423 > > tablets:<key:"updatedAt" value:<group_id:1 predicate:"updatedAt" space:73746 > > tablets:<key:"version" value:<group_id:1 predicate:"version" space:639 > > > > zeros:<key:1 value:<id:1 addr:"zero:5080" leader:true > > maxLeaseId:100000 maxTxnTs:120000 maxRaftId:1 >
server_1  | 2017/12/27 11:39:48 draft.go:140: Node ID: 1 with GroupID: 1
server_1  | 2017/12/27 11:39:48 node.go:233: Found Snapshot, Metadata: {ConfState:{Nodes:[1] XXX_unrecognized:[]} Index:25595 Term:29 XXX_unrecognized:[]}
server_1  | 2017/12/27 11:39:48 node.go:248: Found hardstate: {Term:32 Vote:1 Commit:25609 XXX_unrecognized:[]}
server_1  | 2017/12/27 11:39:48 node.go:260: Group 1 found 14 entries
server_1  | 2017/12/27 11:39:48 draft.go:657: Restarting node for group: 1
server_1  | 2017/12/27 11:39:48 raft.go:567: INFO: 1 became follower at term 32
server_1  | 2017/12/27 11:39:48 raft.go:315: INFO: newRaft 1 [peers: [1], term: 32, commit: 25609, applied: 25595, lastindex: 25609, lastterm: 32]
server_1  | 2017/12/27 11:39:48 groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.
zero_1    | 2017/12/27 11:39:48 raft.go:1070: INFO: 1 no leader at term 31; dropping index reading msg
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"dob" value_type:DATETIME directive:INDEX tokenizer:"hour"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"lastActiveAt" value_type:DATETIME directive:INDEX tokenizer:"hour"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"exact" tokenizer:"term"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"title" value_type:STRING directive:INDEX tokenizer:"exact"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"employed" value_type:BOOL directive:INDEX tokenizer:"bool"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"time" value_type:INT directive:INDEX tokenizer:"int"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"height" value_type:FLOAT directive:INDEX tokenizer:"float"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"partner" value_type:UID
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"children" value_type:UID
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"parents" value_type:UID
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"createdAt" value_type:DATETIME directive:INDEX tokenizer:"hour"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"updatedAt" value_type:DATETIME directive:INDEX tokenizer:"hour"
server_1  | 2017/12/27 11:39:48 mutation.go:152: Done schema update predicate:"type" value_type:STRING directive:INDEX tokenizer:"exact"
server_1  | 2017/12/27 11:39:49 groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.
server_1  | 2017/12/27 11:39:49 groups.go:457: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
zero_1    | 2017/12/27 11:39:49 raft.go:1070: INFO: 1 no leader at term 31; dropping index reading msg
server_1  | 2017/12/27 11:39:50 groups.go:673: Error in oracle delta stream. Error: rpc error: code = Unknown desc = Node is no longer leader.
server_1  | 2017/12/27 11:39:50 groups.go:457: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
zero_1    | 2017/12/27 11:39:50 raft.go:1070: INFO: 1 no leader at term 31; dropping index reading msg
zero_1    | 2017/12/27 11:39:50 raft.go:749: INFO: 1 is starting a new election at term 31
zero_1    | 2017/12/27 11:39:50 raft.go:580: INFO: 1 became candidate at term 32
zero_1    | 2017/12/27 11:39:50 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 32
zero_1    | 2017/12/27 11:39:50 raft.go:621: INFO: 1 became leader at term 32
zero_1    | 2017/12/27 11:39:50 node.go:301: INFO: raft.node: 1 elected leader 1 at term 32
server_1  | 2017/12/27 11:39:51 raft.go:749: INFO: 1 is starting a new election at term 32
server_1  | 2017/12/27 11:39:51 raft.go:580: INFO: 1 became candidate at term 33
server_1  | 2017/12/27 11:39:51 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 33
server_1  | 2017/12/27 11:39:51 raft.go:621: INFO: 1 became leader at term 33
server_1  | 2017/12/27 11:39:51 node.go:301: INFO: raft.node: 1 elected leader 1 at term 33
server_1  | 2017/12/27 11:39:51 groups.go:457: Unable to sync memberships. Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by dpeek** [comment] 2017-12-27 12:00
Ok, I can verify that running dgraph binaries directly works fine.

Ugh, as does the `docker-compose.yml` documented here https://docs.dgraph.io/get-started/

Sorry for the noise, I guess it's something to do with my attempt at creating a docker data volume?

**Comment by janardhan1993** [comment] 2017-12-27 12:19
can you please share your docker-compose.yml, i will try to reproduce the issue tomorrow morning.

**Comment by dpeek** [comment] 2017-12-30 23:26
You can see my docker-compose.yml above :)

**Comment by janardhan1993** [comment] 2018-01-15 06:49
@dpeek Are you facing this issue while deleting uid or scalar edges ?

**Comment by pawanrawal** [comment] 2018-01-24 00:49
@dpeek are you still seeing this issue with the latest version?

**Comment by janardhan1993** [comment] 2018-03-05 12:11
@dpeek I am closing this issue, if you are still seeing the issue or if you are able to reproduce it please feel free to repoen it.

**Closed by janardhan1993** 2018-03-05 12:11 UTC
Labels: investigate
