### ISSUE TITLE
@normalize does not flatten always

### ISSUE THREAD

**Issue by asa511** [dgraph-io/dgraph#4198] opened 2019-10-20 14:58 UTC
#3751 # What version of Dgraph are you using?

v1.1.0

### Have you tried reproducing the issue with the latest release?

NA

### What is the hardware spec (RAM, OS)?

MacOS 10.14.6, 16 GB

### Steps to reproduce the issue (command/config used to run Dgraph).

```
{
  logs(func: uid(0x50)) @normalize {
    userId: uid
    logs: ~log_for(orderdesc: created) {
        logId: uid
        title: title
        createdOn: created
        type_of {
          	typeId: uid                                 
        }
    }
  }
}
```

### Expected behaviour 

```
{
  "data": {
    "logs": [
      {
        "createdOn": "2019-10-20T16:26:12.206897Z",
        "logId": "0x51",
        "title": "normalize does not flatten",
        "typeId": "0x4d"
        "userId": "0x50"
      }
    ]
  }
}
```

###  actual result.

```
{
  "data": {
    "logs": [
      {
        "createdOn": "2019-10-20T16:26:12.206897Z",
        "logId": "0x51",
        "title": "normalize does not flatten",
        "type_of": {
          "typeId": "0x4d"
        },
        "userId": "0x50"
      }
    ]
  }
}
```

The `@normalize` clause was working fine when I was using the following declaration:

```
type_of: [uid] @reverse .
```

It stopped working when I changed it to:
```
type_of: uid @reverse .
```

**Comment by MichelDiz** [comment] 2019-10-20 18:09
I can't reproduce it in master. So probably it is fixed if it was something. Also, there have been some changes recently in `@normalize`.

```
Dgraph version   : 
Dgraph SHA-256   : e15cdaa38af3866ceb56d4b99e46fca946a7d915cb8fef8a089547ba560bee5d
Commit SHA-1     : 
Commit timestamp : 
Branch           : 
Go version       : go1.13.3
```
```xml
<log_for>: uid @reverse .
<type_of>: [uid] .
<title>: string .
<created>: string .
```

```JSON
{
    "set": [{
        "created": "2019-10-20T16:26:12.206897Z",
        "title": "normalize does not flatten",
        "log_for": {
         "user": ""
        },
        "type_of": {
         "type": "test"
        }
      }
    ]
  }
```

```graphql
{
  logs(func: has(~log_for)) @normalize {
    userId: uid
    logs: ~log_for {
        logId: uid
        title: title
        createdOn: created
        type_of {
          	typeId: uid                  
        }
    }
  }
}
```

## Result

```json
{
  "data": {
    "logs": [
      {
        "createdOn": "2019-10-20T16:26:12.206897Z",
        "logId": "0x7535",
        "title": "normalize does not flatten",
        "typeId": "0x7537",
        "userId": "0x7536"
      }
    ]
  }
```

**Comment by asa511** [comment] 2019-10-21 00:06
@MichelDiz Did you also try with the declaration:

```
<log_for>: uid @reverse .
<type_of>: uid .
<title>: string .
<created>: string .
```

plain `uid` instead of `[uid]` for `type_of` predicate.

**Comment by MichelDiz** [comment] 2019-10-21 00:59
Yep, same response, no issues.
![Captura de Tela 2019-10-20 às 21 58 54](https://user-images.githubusercontent.com/6570955/67169914-d4a00400-f384-11e9-99c3-00c4aaaf9d6f.png)

**Comment by danielmai** [comment] 2019-10-21 17:55
This is reproducible on v1.1.0 and master (8a5c2f25136cbf61fdcf7644fcb3ffec77ced426). As @asa511 reported, this happens with predicates with the one-to-one `uid` schema type.

### Steps to reproduce the issue:

1. Run fresh Dgraph cluster.
2. Set the following schema with a `uid` predicate:
   ```
   name: string @index(hash) .
   friend: uid .
   ```
3. Set the following mutation, which connects two nodes to each other using the `friend` predicate:

   ```
   [
     {
       "uid": "_:p1",
       "name": "p1",
       "friend": {
         "uid": "_:p2"
       }
     },
     {
       "uid": "_:p2",
       "name": "p2",
       "friend": {
         "uid": "_:p1"
       }
     }
   ]
   ```

4. Run the following query:

   ```
   {
     everyone(func: eq(name, "p1")) @normalize {
       name1: name
       friend {
         name2: name
       }
     }
   }
   ```
   
   Response:
   
   ```
   {
     "data": {
       "everyone": [
         {
           "name1": "p1",
           "friend": {
             "name2": "p2"
           }
         }
       ]
     }
   }
   ```
   
   `name1` and `name2` should be in the same level without the `"friend"` key in the response.
   
### Steps to get expected response
   
5. To reproduce the **expected** response, re-do the steps but set the schema
   type for `friend` predicate `[uid]`.
   
   Schema:
   
   ```
   name: string @index(hash) .
   friend: [uid] .
   ```
   
   Mutation:
   ```
   [
     {
       "uid": "_:p1",
       "name": "p1",
       "friend": {
         "uid": "_:p2"
       }
     },
     {
       "uid": "_:p2",
       "name": "p2",
       "friend": {
         "uid": "_:p1"
       }
     }
   ]
   ```
   
   Query:
   ```
   {
     everyone(func: eq(name, "p1")) @normalize {
       name1: name
       friend {
         name2: name
       }
     }
   }
   ```
   
   Response:
   ```
   {
     "data": {
       "everyone": [
         {
           "name1": "p1",
           "name2": "p2"
         }
       ]
     }
   }
   ```

**Comment by danielmai** [comment] 2019-10-21 18:32
I'll close this issue since this is fixed in master. The next Dgraph release will contain the fix. For now, you can use the master version as of #4042 if you need this fix. We can also cut a release-candidate version for you if needed.

**Closed by danielmai** 2019-10-21 18:32 UTC
Labels: area/querylang, area/querylang/normalize, kind/bug, status/accepted
