### ISSUE TITLE
use hadoop mapreduce to do bulk import

### ISSUE THREAD

**Issue by xinstein** [dgraph-io/dgraph#2443] opened 2018-06-15 10:43 UTC
The current paradigm allows bulk import to be performed only on a single machine, this seems in contradiction with the design of dgraph (being a distributed graph db). The size of data storable is still constrained by single node capacity. 

On the other hand, live loading could in principle handle this issue, but it is extremely unsuitable for initial import. It, if possible at all, would take at least days for live loader to import my whole database with necessary indexing turned on.

I'm thinking maybe you could provide packages to do bulk loading using popular distributed computing systems.

**Comment by srfrog** [comment] 2019-01-05 03:45
I don't know if we need this. For example, using Apache Beam Go SDK and Dgo we could write a pipeline using Dgraph. Then tie that with the mapreduce runner - https://beam.apache.org/documentation/runners/mapreduce/

IMO hadoop is too limited case, we should be looking at a broader solution with Spark/Beam.

**Comment by manishrjain** [comment] 2019-01-11 03:15
We have an open source contributor looking into distributing bulk loader.

**Comment by manishrjain** [comment] 2019-01-16 03:16
Duplicate of #2628

**Closed by manishrjain** 2019-01-16 03:16 UTC
Labels: feature
