### ISSUE TITLE
Lang tag in orderasc errors

### ISSUE THREAD

**Issue by ashwin95r** [dgraph-io/dgraph#793] opened 2017-04-03 01:22 UTC
This query 
```
{
  me(func:regexp(name, "^[a-zA-z]*[^Kk ]?[Nn]ight"), orderasc: name@en, first:5) {
	name@en
	name@de
	name@it
  }
}
```
returns
`Expecting argument name. Got: lex.Item [15] "@"`

**Comment by tzdybal** [comment] 2017-04-03 01:33
The problem is when using `@lang` notation in ordering at root (in filters everything works fine).

**Comment by tzdybal** [comment] 2017-04-04 09:37
Fix merged to master.

**Closed by tzdybal** 2017-04-04 09:37 UTC
Labels: bug
