### ISSUE TITLE
delete node

### ISSUE THREAD

**Issue by deligent-ant** [dgraph-io/dgraph#4057] opened 2019-09-25 04:15 UTC
I use `{
  "delete" :
    {
       "uid": "0x1"
    }
}` in ratel. 
 but when i query by
 {
  me(func:uid(0x26)){
   uid
   name
  friend{
name}
}`  all the content still exist.

i seem that  delete do not work. i can not delete all eage of a node(S * *)

**Comment by MichelDiz** [comment] 2019-09-25 05:06
If you are using the latest version of Dgraph (v1.1.0) you have to have the Type Schema.
Please, read this blog post https://blog.dgraph.io/post/release-v1.1.0/

**Comment by martinmr** [comment] 2019-09-25 20:08
Yes, that syntax is equivalent to deleting triples of the form `subject * *`. Without type information, Dgraph 1.1 cannot know which predicates to consider.

Closing for now but feel free to reopen or ask around in discuss.dgraph.io or our slack channel if you have more questions.

**Closed by martinmr** 2019-09-25 20:08 UTC

**Comment by AugustHell** [comment] 2019-09-29 10:55
This is somekind weired.
{ "delete" : { "uid": "0x1" } }
should delete anything that got this uid, no matter what type it is.
But atm I'm just struggling, as it just deletes the type information saved in dgraph.type, but all the rest of the data stays in the database and if you don't know all predicates saved with it, you are lost.
There seems to be only one chance to explore this waste by exporting the data and search thru the rdf.
And even if I know the predicates, to get rid of the waste, I have to do several mutations to delete them all one by one? Or is there a way to delete a typed node with all its data?

**Comment by deligent-ant** [comment] 2019-09-29 11:09
> This is somekind weired.
> { "delete" : { "uid": "0x1" } }
> should delete anything that got this uid, no matter what type it is.
> But atm I'm just struggling, as it just deletes the type information saved in dgraph.type, but all the rest of the data stays in the database and if you don't know all predicates saved with it, you are lost.
> There seems to be only one chance to explore this waste by exporting the data and search thru the rdf.
> And even if I know the predicates, to get rid of the waste, I have to do several mutations to delete them all one by one? Or is there a way to delete a typed node with all its data?

i can’t agree more.if i wont delete node ,i have to know all thr predicates,this is not friendly.normally, when delete one item ,just id need.

**Comment by MichelDiz** [comment] 2019-09-29 15:16
The type system has several benefits. But with it, there are several counterparts like that one mentioned.
For me, in the case of deletes, this is a safe way to make sure that those who deletes really know what they are doing. It's like a typed language, it prevents people from making slips. Like TypeScript for example.

If you have full control of the DB, there will be no problems. It can be tricky to get it in the beginning, but over time you get used to it.

But anyway, if you have points to discuss about the Type system. Open up a topic at https://discuss.dgraph.io so we can better analyze the pros and cons.

**Comment by AugustHell** [comment] 2019-09-30 06:47
I like the type system and yes, I'm not in full contol of the DB yet :D I try to dig deeper to get more fine control of and direct access to the data.
But nevertheless how delete <uid> now works, cant be the right solution and is something what a typed language wants to avoid. In my mind there is really a need to overwork it, as it is mentioned all over in tutorials, the documentation and the web.
At least it should not delete anything, if it can't delete all and report back an error with the cause.
