### ISSUE TITLE
Queries to dgraph that runs in testcontainer hang and won't respond after upgrade

### ISSUE THREAD

**Issue by VictorVisoki** [dgraph-io/dgraph#3461] opened 2019-05-23 08:44 UTC
I'm using testcontainers to run dgraph instance in my integration tests,
my tests work with all dgraph versions till **1.0.13**. 

When I try version **1.0.13** and **1.0.14 (latest)**, the test gets stuck on the first query to the database,
and won't get any progress from that point.

The test begins by persisting data into dgraph, this phase completes. It happenes before the first test method runs.
Then, there are tests that query the database. The first one to run hangs as the query result won't return.

Here is the way I define and run the dgraph container (Kotlin):

```
open class TestDgraphGenericContainer(override val init: (containerInfo: InspectContainerResponse) -> Unit = noInitialization) :

    TestContainer("dgraph/dgraph:v1.0.14", init) {

    init {
        withCommand(
            "/bin/sh", "-c",
            "dgraph zero --my=127.0.0.1:5080 & sleep 5 && dgraph alpha --my=127.0.0.1:7080 --lru_mb 1024 --zero 127.0.0.1:5080"
        )
        withExposedPorts(GRPC_PORT, HTTP_PORT)
    }

    val serverHost: String
        get() = containerIpAddress

    val grpcPort: Int
        get() = getMappedPort(GRPC_PORT)

    val httpPort: Int
        get() = getMappedPort(HTTP_PORT)
}
```

I expect my tests to continue working, as the only thing I change is the version from 1.0.11 to 1.0.13 or 1.0.14

**Comment by MichelDiz** [comment] 2019-05-23 14:47
Have you cleanup the path? If this is not a case of actual upgrade, just clean and start from scratch.
Otherwise you should read this https://docs.dgraph.io/deploy/#upgrade-database

**Comment by VictorVisoki** [comment] 2019-05-23 15:11
This is a test that starts a clean container each time it runs. No previous data exists.
So every run is "clean and start from scratch". It is a test I run.
The only "upgrade" here is by starting to use dgraph version 1.0.14 instead of 1.0.11

**Comment by MichelDiz** [comment] 2019-05-23 15:27
Okay, 

So, I can't see where the problem is tho. 
If you say there's no previous data and is starting from scratch the issue resides in something beyond my comprehension. You are doing basic processes that would at first work in any situation. So that lies in another scope.

Please, share logs during the event to give me a clear context of your side.

Cheers.

**Comment by VictorVisoki** [comment] 2019-05-26 14:21
Thank you for the response.

I noticed that there is some kind of correlation between the query projection size and this behavior. 
I have a query that selects a list of properties, almost all are direct - this query never returns (in 1.0.14) and the test is stuck.

When I remove items from the projection and reduce it, it starts working.
In overall I see that for short projections, or results that don't contain data for most of the selected properties, it works.

Here is a log from the dgraph container:
[dgraph_log.txt](https://github.com/dgraph-io/dgraph/files/3220388/dgraph_log.txt)

Here is my projection:
[query_projection.txt](https://github.com/dgraph-io/dgraph/files/3220391/query_projection.txt)

When paused using debugger I can see the state:
Thread  "grpc-default-worker-ELG-1-2" RUNNING

**Comment by MichelDiz** [comment] 2019-05-26 16:00
What is this "query projection"? The format seems like a GraphQL+- query, but isn't at all.

You logs feels okay to me.

**Comment by VictorVisoki** [comment] 2019-05-27 07:28
This projection is part of my query, a valid standard query which I can run both from Ratel and from my java code against dgraph, here it is: 
 
[dgraph_full_query.txt](https://github.com/dgraph-io/dgraph/files/3222350/dgraph_full_query.txt)
(this query and many others are used both in tests and in production)

I remind again that the problem is that once I switch from version 1.0.11 to version 1.0.13 or 1.0.14 the tests stop working,
They hang at the moment a query like such is executed, it does not return ever.

You can see my schema from the dgraph log file, if the query is confusing, I have fields that contain '.' in their name.

**Comment by MichelDiz** [comment] 2019-05-27 14:44
Why do you have a extra nested block with unknown edge?

```
query generated($limit: int, $offset: int) {

  Usp(func: has(_is_Usp), orderasc: name, first: $limit, offset: $offset)
    @filter(regexp(name, /^\Qusp1\E$/i)) {  // <= This block is empty
{ // <= This block is coming from nowhere.
      uid
      description
      changed
      requirements {...}
  }
 }

}
```

>They hang at the moment a query like such is executed, it does not return ever.

Your Query has a `has` function and `regexp` filter. And also a nested block with unknown edge. I think the sum of these factors causes Query to run for a long time. Using `has` your query will go through all the data that has "_is_Usp".

Try to run a more simple Query just to evaluate this hypothesis.

BTW, Why do you use commas between predicates?

**Comment by danielmai** [comment] 2019-05-27 19:49
@VictorVisoki Checking the trace for this query should show what's happening with your query in your test. You can view trace data either from the zPages from Dgraph Alpha or via Jaeger: https://docs.dgraph.io/deploy/#tracing. The query trace data is found under the trace name "Server.Query".

**Comment by VictorVisoki** [comment] 2019-05-28 09:58
1. Regarding { } and blocks - my typo,  please ignore.
2. This query and many others which are being run during tests -  run at no-time on 1.0.11 ! 
This is not a case of query that runs for a long time,  it never returns, never. No matter for how long I will wait. This is something else. 

Also, there is really a tiny amount of data in the test database, only for testing purposes.

I can try to remove commas and look for mistakes in the query, 
but this is not the right approach here, in my opinion, because:
I work with dgraph for a long time and have those tests in CI/CD running on every push,
they run multiple times each day and are working with 1.0.6, 1.0.9, 1.0.11 - you get the point ...

There is definitely some kind of a change in 1.0.13

What other information except query tracing can I provide ?

**Comment by VictorVisoki** [comment] 2019-05-28 13:00
There's output from /z/tracez under the category Server.Query, 
like @danielmai suggested:
  
[dgraph query trace.txt](https://github.com/dgraph-io/dgraph/files/3227716/dgraph.query.trace.txt)

**Comment by campoy** [comment] 2019-09-13 16:35
Hey @MichelDiz,

Could you give an update on this bug or close it if it's not relevant anymore?

**Comment by MichelDiz** [comment] 2019-09-13 19:53
I have no idea, however, if it still a thing @VictorVisoki , please feel free to reopen but first upgrade to v1.1.0 and use Jaeger to trace the query execution.

Thanks @campoy for the ping.

**Closed by MichelDiz** 2019-09-13 19:53 UTC
Labels: kind/question
