### ISSUE TITLE
Predicate move can result in temporarily absent data

### ISSUE THREAD

**Issue by peterstace** [dgraph-io/dgraph#1919] opened 2017-12-13 23:57 UTC
If you suspect this could be a bug, follow the template.

- `master` at `4f5fbfc8`
- 64GB memory, Ubuntu.
- To reproduce: 3 zeros, 6 dgraph servers (split into 2 groups). Run the `bigdata` binary from `peter/bigdata`. After some time an assertion in `bigdata` will fail. The assertion checks that a search for a known `xid` is found. This occurs immediately after (during?) a predicate move.

Instead of giving back no results in the query, the query should give an error.

Log from one of the dgraph zeros (other 2 zeros don't show any in their logs about the move):
```
2017/12/13 20:19:19 wal.go:118: Writing snapshot to WAL, metadata: {ConfState:{Nodes:[1 2 3] XXX_unrecognized:[]} Inde$
:81939 Term:3 XXX_unrecognized:[]}, len(data): 1776
2017/12/13 20:19:24 oracle.go:84: purging below ts:3839219, len(o.commits):130, len(o.aborts):0
2017/12/13 20:19:34 oracle.go:84: purging below ts:3845584, len(o.commits):131, len(o.aborts):0
2017/12/13 20:19:44 tablet.go:165:

Groups sorted by size: [{gid:2 size:18833152} {gid:1 size:20718028}]

2017/12/13 20:19:44 tablet.go:170: size_diff 1884876
2017/12/13 20:19:44 tablet.go:87: Going to move predicate count_g from 1 to 2
2017/12/13 20:19:44 oracle.go:84: purging below ts:3851887, len(o.commits):131, len(o.aborts):0
```

**Comment by janardhan1993** [comment] 2017-12-14 12:48
I think this is probably related to reading a pl which was evicted from lru recently(there's some issue in reading immediately after purging old versions). During predicate move we load a high number of pls which could cause a recently evicted pl to be read again.

**Comment by janardhan1993** [comment] 2017-12-18 01:53
I am not able to reproduce it now, might have been related to the bug in badger.  Closing for now.

**Closed by janardhan1993** 2017-12-18 01:53 UTC
Labels: bug
