### ISSUE TITLE
graphql dgraph doesn't support comment in schema

### ISSUE THREAD

**Issue by dtrckd** [dgraph-io/dgraph#4837] opened 2020-02-22 22:13 UTC
Hi,

It seems that '#' comments are not supported in graphql schema.

### What version of Dgraph are you using?

```
Dgraph version   : v2.0.0-beta                                                                                                                                                                                     
Dgraph SHA-256 : ddd15b75edbacef8a1bfe8ecc383838ec2fdcd87c6586d07db659932dfedacb5                                                                                                                                
Commit SHA-1     : 17ce5d31a                                                                                                                                                                                       
Commit timestamp : 2020-02-20 15:02:16 -0800                                                                                                                                                                       Branch           : v2.0.0-beta                                                                                                                                                                                     Go version       : go1.13.7  
```

### Have you tried reproducing the issue with the latest release?

yes

### What is the hardware spec (RAM, OS)?

Linux  4.19.0-8-amd64  SMP Debian 4.19.98-1 x86_64 GNU/Linux
4 vcpu, 16 Gb Ram

### Steps to reproduce the issue (command/config used to run Dgraph).

`docker run -p 8080:8080 -it -v /mnt/dgraph:/dgraph dgraph/standalone:v2.0.0-beta`

### Expected behaviour and actual result.

```bash
$ echo -e  "type Boo { id: ID! name: String  # Comment \n}" | curl -X POST localhost:8080/admin/schema -d @-
{"errors":[{"message":"couldn't rewrite mutation updateGQLSchema because input:1: Expected Name, found \u003cEOF\u003e\n","extensions":{"code":"Error"}}]}⏎ 
```

Without the comment, it works as expected.

**Comment by marvin-hansen** [comment] 2020-02-23 23:37
@dtrckd 

can you try the following:

1) put your schema in a file called schema.graphql
2) Run docker, as before
3) Use jq & curl to upload the schema:

 >     jq -n --arg schema "$(cat schema.graphql)" '{ query: "mutation updateGQLSchema($sch: String!) { updateGQLSchema(input: { set: { schema: $sch }}) { gqlSchema { schema } } }", variables: { sch: $schema }}' | curl -X POST -H "Content-Type: application/json" http://localhost:8080/admin -d @- | jq -r
 
For some totally weirdo reasons I had a couple of issues with the curl command shown in the current rc/beta documentation, so I tried the previous one with jq and it works every since. My best guess is, this is yet another snafu in the documentation.  

Currently, I'm merging ~8 schemata files with cat into one master schema and upload it to Dgraph. Works perfectly fine with plenty of types, comments, enums, interfaces, and just about everything you can throw at the current Dgraph GraphQL implementation.

**Comment by dtrckd** [comment] 2020-02-24 00:47
Thanks for the tips @marvin-hansen, it helps.

**Comment by MichelDiz** [comment] 2020-02-24 04:42
No need to use jq anymore. The latest beta you can run like
```
curl -X POST localhost:8080/admin/schema -d '@schema.graphql'
```

**Comment by MichaelJCompton** [comment] 2020-02-24 10:35
I think the issue is with curl.  I think `--data-binary` should work instead of `-d`.  I'll update the docs for that. (and maybe also include info on how to do the GraphQL mutation as well)

I'll close this, please reopen if none of the suggestions are working

**Closed** 2020-02-24 10:37 UTC

**Comment by marvin-hansen** [comment] 2020-02-24 17:01
> curl -X POST localhost:8080/admin/schema -d '@schema.graphql'
Throws the following error on Linux and Windows:

> {"errors":[{"message":"couldn't rewrite mutation updateGQLSchema because while parsing GraphQL schema: input:99: expected at least one definition, found }","extensions":{"code":"Error"}}]}

@MichaelJCompton 

> curl -X POST localhost:8080/admin/schema --data-binary '@schema.graphql'

Works 100% on Linux, but fails on Windows 10. Please update the docs.
