### ISSUE TITLE
Error while creating badger while starting Dgraph data server 

### ISSUE THREAD

**Issue by ozeetee** [dgraph-io/dgraph#1887] opened 2017-12-07 03:40 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v0.9.4

- Have you tried reproducing the issue with latest release?
v0.9.4

- What is the hardware spec (RAM, OS)?
Macbook pro, Ram 16 GB, High Sierra 10.13.1

- Steps to reproduce the issue (command/config used to run Dgraph).
1. Was using v0.8.3. Was working fine.
2. Deleted ~/dgraph
3. Installed binaries by running command 
curl https://get.dgraph.io -sSf | bash
4. dgraph zero --port_offset -2000
5. dgraph server --memory_mb 2048 --zero localhost:5080
GOT error : 
Error while creating badger KV WAL store error: manifest has unsupported version: 2 (we support 4)

- Expected behaviour and actual result.
Should not throw error with new fresh installation

**Comment by peterstace** [comment] 2017-12-07 03:53
Hi,

That error indicates that there is an existing data directory from a previous version of dgraph.

What was the directory you were running dgraph from? Can your show a directory listing of that dir? If there are `z`, `w`, `wz` directories there, they should either be deleted (if you don't care about the data), or exported, deleted, and then reimported.

**Comment by ozeetee** [comment] 2017-12-07 20:55
Thanks. I searched and deleted the directories and its working fine now. Isn't dgragh uses **~/dgraph** directory by default ? Do you need to specify dir while running dgraph.

**Comment by peterstace** [comment] 2017-12-07 23:17
Dgraph doesn't use `~/dgraph` by default (although that's the directory used in many of the docker examples).

By default, there are three directories which dgraph server and dgraph zero write to:

- `w` - write ahead log dir for dgraph server
- `p` - postings dir for dgraph server.
- `wz` - write ahead log for dgraph zero.

They are all relative to the directory that you run the dgraph command from. They can be changed using flags when invoking dgraph (look at the output of `--help` for details).

Looks like it's working now for you, so closing.

**Comment by ozeetee** [comment] 2017-12-19 23:27
Again the installation didn't go smooth. Still struggling to start Drgaph after update.

Wanted to update to version `v1.0.0` from previous installed version `v0.9.4`


Followed instruction from : https://docs.dgraph.io/get-started/
Not using Docker so used instruction from section : `From Install Scripts (Linux/Mac)`

Using Macbook pro, Ram 16 GB, High Sierra 10.13.1

Steps Followed : 

1. Stopped Dgraph `v0.9.4`, both `zero` and `server`
2. Restarted my Mac because of system updates.
3. Check `ps -eaf | grep dgraph` to make sure no Dgraph process running.
4. `cd ~/dgraph`
5. Ran install script `curl https://get.dgraph.io -sSf | bash`
6. Installation was successful with message
  `Dgraph binaries v1.0.0 have been installed successfully in /usr/local/bin.`

7. Running `dgraph zero --port_offset -2000` getting following errors in console : 


2017/12/20 12:23:02 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 12:23:02 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure



8. Running `dgraph server --memory_mb 2048 --zero localhost:5080`

2017/12/20 12:24:17 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:17 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:17 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:18 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:18 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:19 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:21 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:24 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:30 groups.go:110: Error while connecting with group zero: rpc error: code = Unknown desc = Invalid address
2017/12/20 12:24:43 Unable to join cluster via dgraphzero
  

9. Error in `Dgraph` zero console: 

2017/12/20 12:24:21 zero.go:316: Got connection request: addr:"localhost:7080"
2017/12/20 12:24:21 raft.go:525: While applying proposal: Invalid address
2017/12/20 12:24:21 zero.go:405: Connected
2017/12/20 12:24:22 oracle.go:375: No healthy connection found to leader of group 1
2017/12/20 12:24:22 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 12:24:22 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 12:24:24 zero.go:316: Got connection request: addr:"localhost:7080"
2017/12/20 12:24:24 raft.go:525: While applying proposal: Invalid address
2017/12/20 12:24:24 zero.go:405: Connected
2017/12/20 12:24:30 zero.go:316: Got connection request: addr:"localhost:7080"
2017/12/20 12:24:30 raft.go:525: While applying proposal: Invalid address
2017/12/20 12:24:30 zero.go:405: Connected

**Comment by peterstace** [comment] 2017-12-20 00:52
I tried to reproduce this by starting up a dgraph v0.9.4, the shutting it down, and then bringing dgraph 1.0 up using the same data directories. I'm not seeing any problems (there is the usual "blip" in the logs where a service is looked for but it doesn't exist - but this quickly resolves itself).

This is what I'm seeing when I bring up dgraph v1.0:

Zero:
```
$ dgraph zero --port_offset -2000
Setting up listener at: 0.0.0.0:5080
Setting up listener at: 0.0.0.0:6080
2017/12/20 11:47:51 node.go:248: Found hardstate: {Term:2 Vote:1 Commit:15 XXX_unrecognized:[]}
2017/12/20 11:47:51 node.go:260: Group 0 found 15 entries
2017/12/20 11:47:51 raft.go:371: Restarting node for dgraphzero
2017/12/20 11:47:51 raft.go:567: INFO: 1 became follower at term 2
2017/12/20 11:47:51 raft.go:315: INFO: newRaft 1 [peers: [], term: 2, commit: 15, applied: 0, lastindex: 15, lastterm: 2]
Running Dgraph zero...
2017/12/20 11:47:51 node.go:127: Setting conf state to nodes:1 
2017/12/20 11:47:51 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 11:47:51 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 11:47:51 pool.go:118: == CONNECT ==> Setting localhost:7080
2017/12/20 11:47:54 raft.go:749: INFO: 1 is starting a new election at term 2
2017/12/20 11:47:54 raft.go:580: INFO: 1 became candidate at term 3
2017/12/20 11:47:54 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 3
2017/12/20 11:47:54 raft.go:621: INFO: 1 became leader at term 3
2017/12/20 11:47:54 node.go:301: INFO: raft.node: 1 elected leader 1 at term 3
2017/12/20 11:48:01 zero.go:310: Got connection request: id:1 addr:"localhost:7080" 
2017/12/20 11:48:01 zero.go:406: Connected
2017/12/20 11:48:01 oracle.go:373: No healthy connection found to leader of group 1
2017/12/20 11:48:01 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 11:48:01 pool.go:167: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure
2017/12/20 11:48:11 oracle.go:373: No healthy connection found to leader of group 1
2017/12/20 11:48:21 oracle.go:84: purging below ts:2, len(o.commits):0, len(o.aborts):0
```
Server:
```
$ dgraph server --memory_mb 2048 --zero localhost:5080
2017/12/20 11:48:01 worker.go:99: Worker listening at address: [::]:7080
2017/12/20 11:48:01 gRPC server started.  Listening on port 9080
2017/12/20 11:48:01 HTTP server started.  Listening on port 8080
2017/12/20 11:48:01 groups.go:94: Current Raft Id: 1
2017/12/20 11:48:01 pool.go:118: == CONNECT ==> Setting localhost:5080
2017/12/20 11:48:01 groups.go:117: Connected to group zero. Connection state: member:<id:1 addr:"localhost:7080" > state:<counter:18 groups:<key:1 value:<members:<key:1 value:<id:1 group_id:1 addr:"localhost:7080" leader:true last_update:1513730515 > > tablets:<key:"_dummy_" value:<group_id:1 predicate:"_dummy_" space:19 > > tablets:<key:"_predicate_" value:<group_id:1 predicate:"_predicate_" > > tablets:<key:"age" value:<group_id:1 predicate:"age" > > tablets:<key:"friend" value:<group_id:1 predicate:"friend" > > tablets:<key:"name" value:<group_id:1 predicate:"name" > > tablets:<key:"owns_pet" value:<group_id:1 predicate:"owns_pet" > > > > zeros:<key:1 value:<id:1 addr:"localhost:5080" leader:true > > maxLeaseId:10000 maxTxnTs:10000 maxRaftId:1 > 
2017/12/20 11:48:01 draft.go:140: Node ID: 1 with GroupID: 1
2017/12/20 11:48:01 node.go:248: Found hardstate: {Term:2 Vote:1 Commit:5 XXX_unrecognized:[]}
2017/12/20 11:48:01 node.go:260: Group 1 found 5 entries
2017/12/20 11:48:01 draft.go:654: Restarting node for group: 1
2017/12/20 11:48:01 raft.go:567: INFO: 1 became follower at term 2
2017/12/20 11:48:01 raft.go:315: INFO: newRaft 1 [peers: [], term: 2, commit: 5, applied: 0, lastindex: 5, lastterm: 2]
2017/12/20 11:48:01 node.go:127: Setting conf state to nodes:1 
2017/12/20 11:48:01 mutation.go:169: Done schema update predicate:"_predicate_" value_type:STRING list:true 
2017/12/20 11:48:01 mutation.go:169: Done schema update predicate:"name" value_type:STRING directive:INDEX tokenizer:"exact" tokenizer:"term" 
2017/12/20 11:48:01 mutation.go:169: Done schema update predicate:"age" value_type:INT directive:INDEX tokenizer:"int" 
2017/12/20 11:48:01 mutation.go:169: Done schema update predicate:"friend" value_type:UID count:true 
2017/12/20 11:48:03 raft.go:749: INFO: 1 is starting a new election at term 2
2017/12/20 11:48:03 raft.go:580: INFO: 1 became candidate at term 3
2017/12/20 11:48:03 raft.go:664: INFO: 1 received MsgVoteResp from 1 at term 3
2017/12/20 11:48:03 raft.go:621: INFO: 1 became leader at term 3
2017/12/20 11:48:03 node.go:301: INFO: raft.node: 1 elected leader 1 at term 3
```

Are you able to replicate the issue consistently when bringing up dgraph v1.0? If so, is it possible for you to send the `w`, `p`, and `wz` directories to me to help me debug the issue?

**Comment by ozeetee** [comment] 2017-12-20 01:44
Sorry bad luck, I just deleted the `w`,`p`, and `wz` directory.  After deleting the dir the server is working fine now. 
I don't know what really happened. I am trying to repo the case again but unable to do it now. Looks like something got messed up while upgrading not really sure. I will keep a watch and again put comment if I see the pop ups again. Will again upgrade the server when new stable build is available and put the comment here again. 
:) Thanks for the help.

**Comment by peterstace** [comment] 2017-12-20 01:53
No worries, yes please let us know if you run into the problem again :)

**Closed by peterstace** 2017-12-20 01:53 UTC
Labels: investigate

**Comment by ps360pa** [comment] 2018-07-27 03:18
Same error here. Yesterday I install dgraph first time. No error occured. Today I start up the dgraph zero again, the error message: 
`2018/07/27 11:11:53 pool.go:161: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:7080: connectex: No connection could be made because the target machine actively refused it."
2018/07/27 11:11:53 pool.go:161: Echo error from localhost:7080. Err: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp [::1]:7080: connectex: No connection could be made because the target machine actively refused it."`
My folder dir is 
> D:.
│  dgraph-ratel.exe
│  dgraph.exe
│
├─p
│      000000.vlog
│      LOCK
│      MANIFEST
│
├─w
│      000000.vlog
│      LOCK
│      MANIFEST
│
└─zw
        000000.vlog
        000008.sst
        MANIFEST
