### ISSUE TITLE
Server Overloaded with Pending Proposals

### ISSUE THREAD

**Issue by MeteHanC** [dgraph-io/dgraph#3382] opened 2019-05-07 14:06 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.14

- Have you tried reproducing the issue with latest release?
Since v1.0.14 is the latest verified release, yes.

- What is the hardware spec (RAM, OS)?
64 GB DDR4, 2 x 4 TB SATA Enterprise hard drive 7200 rpm , Intel® Core™ i7-6700 Quad-Core - Ubuntu 18.04

- Steps to reproduce the issue (command/config used to run Dgraph).
Followed the 'Getting Started' guide. Set up 20480 MB's of RAM for the alpha. Then I start inserting thousands of data concurrently. After some point, insertions stack up and alpha crashes with the error :
 'Error=Server overloaded with pending proposals. Please retry later. Retrying...
Killed'
The thing is I am not even inserting anymore and it acts like this for over 5 days, I think it is still trying to insert the data. Also when alpha is on, it keeps giving this error : 'A tick missed to fire. Node blocks too long!'

- Expected behaviour and actual result.
I am not able to even run a basic query, it timeouts with the error : '": context deadline exceeded"'
Are we able to abort all the pending proposals?

**Comment by danielmai** [comment] 2019-05-15 18:23
Have you tried using the Dgraph Live Loader? It will run mutations by batching 1000 triples per mutation, with 10 concurrent mutations at a time. You could also do something similar in your own loading.

**Comment by Willem520** [comment] 2019-08-20 02:37
I have the same problem,How can I resolve them. I used Spark and dgraph4j to import data

**Comment by Willem520** [comment] 2019-12-25 10:23
I used v1.1.1, but the problem is still existed.the data from kafka,and I use java client to mutate(1000 node per mutation)

**Comment by danielmai** [comment] 2020-01-31 22:30
This sounds like a deadlock. We fixed this issue via #4453. Closing this issue. Feel free to reopen.

**Closed by danielmai** 2020-01-31 22:30 UTC
Labels: area/crash, area/operations, kind/question, status/needs-attention

**Comment by Valdanitooooo** [comment] 2020-08-07 01:49
I have the same problem when using version v20.07.0.
