### ISSUE TITLE
Can't compile dgraph from source code.

### ISSUE THREAD

**Issue by kgardas** [dgraph-io/dgraph#4214] opened 2019-10-24 18:16 UTC
### What version of Dgraph are you using?
github.com HEAD as of Oct 24 2019

### Have you tried reproducing the issue with the latest release?
No

### What is the hardware spec (RAM, OS)?
Two systems:
AMD64 and POWER64le together with Ubuntu 18.04 with Ubuntu provided go 1.10

### Steps to reproduce the issue (command/config used to run Dgraph).
As in README.md:
go get -v github.com/dgraph-io/dgraph/dgraph

### Expected behaviour and actual result.
I expected dgraph to compile well, while result is go complain:

```
[....]
github.com/dgraph-io/dgraph/schema
github.com/dgraph-io/dgraph/xidmap
github.com/dgraph-io/dgraph/conn
# github.com/dgraph-io/dgraph/conn
go/src/github.com/dgraph-io/dgraph/conn/node.go:140:16: not enough arguments in call to n.Applied.Init
        have (nil)
        want (*y.Closer, bool)
go/src/github.com/dgraph-io/dgraph/conn/raft_server.go:164:35: confState.Nodes undefined (type *raftpb.ConfState has no field or method Nodes)
```

**Comment by martinmr** [comment] 2019-10-24 18:35
It looks like you have inconsistent versions of badger and dgraph. This didn't used to be a problem because we vendored badger into dgraph but we just changed dgraph to use go modules,  I would try 1.13 if you can get it in your system but 1.12 should work.

**Comment by martinmr** [comment] 2019-10-24 18:35
by 1.13 I mean go version 1.13.

**Comment by kgardas** [comment] 2019-10-24 19:57
The same issue even with go 1.13. I mean, I've installed go 1.13, extend path by export PATH=`$HOME/sfw/go-1.13/bin:$PATH. This way, go version returns 1.13 and then rm -rf $HOME/go and rerun go get. Still the same issue:
```
github.com/dgraph-io/dgraph/schema
github.com/dgraph-io/dgraph/conn
# github.com/dgraph-io/dgraph/conn
go/src/github.com/dgraph-io/dgraph/conn/node.go:140:16: not enough arguments in call to n.Applied.Init
        have (nil)
        want (*y.Closer, bool)
go/src/github.com/dgraph-io/dgraph/conn/raft_server.go:164:35: confState.Nodes undefined (type *raftpb.ConfState has no field or method Nodes)

karel@power:~$ go version
go version go1.13.3 linux/ppc64le
karel@power:~$ 
```

**Comment by alexkreidler** [comment] 2019-10-24 21:20
I'm running into this exact issue on Go 1.13:

```
$ go get -v -t github.com/dgraph-io/dgraph/dgraph
github.com/dgraph-io/dgraph/conn
# github.com/dgraph-io/dgraph/conn
go/src/github.com/dgraph-io/dgraph/conn/node.go:140:16: not enough arguments in call to n.Applied.Init
	have (nil)
	want (*y.Closer, bool)
go/src/github.com/dgraph-io/dgraph/conn/raft_server.go:164:35: confState.Nodes undefined (type *raftpb.ConfState has no field or method Nodes)
$ go version
go version go1.13 darwin/amd64
```

Please fix, I'd love to build something with Dgraph!

**Comment by martinmr** [comment] 2019-10-24 23:46
I was able to reproduce the issue. I got past that error by doing `export GO111MODULE=on` and running `go get -v -t github.com/dgraph-io/dgraph/dgraph@master` command again. You have to add `@master` because the latest official Dgraph version was not using go modules.

But now we're getting a different error message:
```
# github.com/dgraph-io/dgraph/raftwal
../../../../pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191024224631-2813b34f890e/raftwal/storage.go:56:22: cannot use snap (type "go.etcd.io/etcd/raft/raftpb".Snapshot) as type "github.com/coreos/etcd/raft/raftpb".Snapshot in argument to raft.IsEmptySnap
../../../../pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191024224631-2813b34f890e/raftwal/storage.go:248:30: cannot use *snap (type "go.etcd.io/etcd/raft/raftpb".Snapshot) as type "github.com/coreos/etcd/raft/raftpb".Snapshot in argument to raft.IsEmptySnap
../../../../pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191024224631-2813b34f890e/raftwal/storage.go:324:30: cannot use *snap (type "go.etcd.io/etcd/raft/raftpb".Snapshot) as type "github.com/coreos/etcd/raft/raftpb".Snapshot in argument to raft.IsEmptySnap
../../../../pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191024224631-2813b34f890e/raftwal/storage.go:347:21: cannot use s (type "go.etcd.io/etcd/raft/raftpb".Snapshot) as type "github.com/coreos/etcd/raft/raftpb".Snapshot in argument to raft.IsEmptySnap
../../../../pkg/mod/github.com/dgraph-io/dgraph@v1.1.1-0.20191024224631-2813b34f890e/raftwal/storage.go:383:26: cannot use st (type "go.etcd.io/etcd/raft/raftpb".HardState) as type "github.com/coreos/etcd/raft/raftpb".HardState in argument to raft.IsEmptyHardState
```

We are looking into this.

**Comment by martinmr** [comment] 2019-10-25 22:04
Still looking into this. For now there are a couple of workaround to get over this and the related issue #4216 .

1. Even though `go get` is failing, it downloads dgraph and its dependencies. You can build it by going into the repo and running `make` (or `make install` to install to your `$GOPATH/bin`.
2. Don't depend on dgraph. I am not sure what exactly @alexkreidler is trying to do, but in general, dgraph is not a library so your application does not have to make use of go modules to indicate that there's a dependency on dgraph. For example, if dgraph was required to run tests, one could include the binary or make use of our docker images to spin up a testing environment.

**Comment by martinmr** [comment] 2019-11-05 19:21
I checked this again and `GO111MODULE=on go get ...dgraph@master` is working now.

I think the issue is trying to use 1.1 since go modules were not enabled yet.
Closing this issue since there's no action items left.

The point about trying to avoid depending on Dgraph in the go modules file if you can avoid it still stands. You can take a look at our test scripts to see how we run tests that depend on dgraph without depending on go modules.

**Closed by martinmr** 2019-11-05 19:21 UTC
