### ISSUE TITLE
regexp function do not match all language

### ISSUE THREAD

**Issue by artemklv** [dgraph-io/dgraph#945] opened 2017-05-17 10:14 UTC
example:
`query {
  names(func: regexp(name.title@ru, /^артем*$/i)) {
    name.title
  }
}`
empty result

`query {
  names(func: regexp(name.title@en, /^john*$/i)) {
    name.title
  }
}`
all fine

**Comment by tzdybal** [comment] 2017-05-18 02:47
The source of the problem is that `codesearch` library build trigrams as 3-_byte_ substrings, while we're using 3-_rune_ substrings. Therefore parsed regexp contains some broken Unicode characters (`"\x80т"`, `"\x82е"`, `"\xb0р"`, `"\xb5м"`, `"а\xd1"`, `"е\xd0"`, `"р\xd1"`, `"т\xd0"`), while index contains complete Unicode (`"арт"`, `"рте"`, `"тем"`).

BTW - @artemklv are you sure that your regular expressions are correct? If you want to match "anything starting with `артем`", you should use `/^артем/i` or `/^артем.*$/i` (note the dot (`.`) before asterisk (`*`)).

**Comment by tzdybal** [comment] 2017-05-18 04:42
Changes committed to `release/v0.7.7` (0d73f85154a7c561dbf2efb12ff034da07a2cb88).

**Closed by tzdybal** 2017-05-18 04:42 UTC
Labels: bug
