### ISSUE TITLE
[BUG]: Semicolons break fulltext search

### ISSUE THREAD

**Issue by lithdoh** [dgraph-io/dgraph#8787] opened 2023-04-04 23:39 UTC
### What version of Dgraph are you using?

 dgraph/standalone:latest

Schema: 
```
type Stems  {
	id: ID! 
	link: String! 
	image: String! 
	name: String! @search(by:[fulltext]) 
	length: Int @search 
	rise: Int @search 
	clampDiameter: Float @search 
	steererDiameter: String @search(by:[hash]) 
	color: String @search(by:[hash]) 
	material: String! @search(by:[hash]) 
	price: Float! @search 
	weight: Int @search 
	brand: String! @search(by:[hash]) 
}
```

### Have you tried reproducing the issue with the latest release?

Yes

### What is the hardware spec (RAM, CPU, OS)?

Irrelevant

### What steps will reproduce the bug?

Make any query that uses fulltext search "alloftext" or "anyoftext" that contains one or more semicolons or backslashes.

### Expected behavior and actual result.

When I enter any string containing a semicolon or backslash in the fulltext search, I get the error

“no query string supplied in request”

This is a sample GraphQL query that produces the error

```
query MyQuery {
  queryItems(filter: {name: {alloftext: "text;with;semicolons"}}) {
    id
    name
    price
  }
}
```

The issue does not occur when the same query is used in the Dgraph Cloud Explorer for some reason.
I’m using the Docker dgraph/standalone:latest image.

### Additional information

The full error message was:

`{"errors":[{"message":"no query string supplied in request"}],"extensions":{"tracing":{"version":1,"startTime":"2023-04-04T23:41:00.55157713Z","endTime":"2023-04-04T23:41:00.551966171Z","duration":389041}}}`

**Comment by mangalaman93** [comment] 2023-04-07 11:09
Hi @lithdoh, would it be possible for you to provide the GraphQL schema that you are using. That would help us easily reproduce this issue and hopefully fix it too.

**Comment by lithdoh** [comment] 2023-04-07 19:45
Hi Aman, I have updated the github bug issue with my schema. I have
recently discovered that the backslash character "\" has the same result as
searching with semicolons.

**Comment by mangalaman93** [comment] 2023-04-17 00:56
Everything seems to work for me. I tried the following:

1. Run dgraph from the standalone image
```
docker run --rm -it -p 8080:8080 dgraph/standalone:latest
```

2. Setup schema
```
curl --request POST \
  --url http://localhost:8080/admin \
  --header 'Content-Type: application/json' \
  --data '{"query":"mutation updateGQLSchema($sch: String!) {\n    updateGQLSchema(input: { set: { schema: $sch }}) {\n\t\t\tgqlSchema {\n\t\t\t\tid\n\t\t\t}\n\t\t}\n\t}","operationName":"updateGQLSchema","variables":{"sch":"type Stems  {\n id: ID! \n link: String! \n image: String! \n name: String! @search(by:[fulltext]) \n length: Int @search \n rise: Int @search \n clampDiameter: Float @search \n steererDiameter: String @search(by:[hash]) \n color: String @search(by:[hash]) \n material: String! @search(by:[hash]) \n price: Float! @search \n weight: Int @search \n brand: String! @search(by:[hash]) }"}}'
```

3. Run query:
```
curl --request POST \
  --url http://localhost:8080/graphql \
  --header 'Content-Type: application/json' \
  --data '{"query":"query MyQuery {\n  queryStems(filter: {name: {alloftext: \"text;with;semicolons\"}}) {\n    id\n    name\n    price\n  }\n}\n","operationName":"MyQuery","variables":{}}'
```

I get the following response:
```
{
  "data": {
    "queryStems": []
  },
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2023-04-17T00:55:38.603403852Z",
      "endTime": "2023-04-17T00:55:38.604507486Z",
      "duration": 1103634,
      "execution": {
        "resolvers": [
          {
            "path": [
              "queryStems"
            ],
            "parentType": "Query",
            "fieldName": "queryStems",
            "returnType": "[Stems]",
            "startOffset": 107965,
            "duration": 991551,
            "dgraph": [
              {
                "label": "query",
                "startOffset": 161326,
                "duration": 936808
              }
            ]
          }
        ]
      }
    }
  }
}
``

**Comment by mangalaman93** [comment] 2023-04-17 00:56
Maybe, if you could share the exact steps that you are following, or try the steps that I mentioned here and see whether these steps work for you. Thank you

**Comment by lithdoh** [comment] 2023-04-17 02:35
I tried the steps you mentioned and got the same result:
`"data": {
    "queryStems": []
  },`

But when I tried the same query like this:

`http://localhost:8080/graphql?query={ 
  
   queryStems(order: {asc: name}, first: 25, offset: 0, filter: {name: {alloftext: "text;with;semicolons"}})
   
    { id name price } }`

I got the error: 

`{"errors":[{"message":"no query string supplied in request"}],"extensions":{"tracing":{"version":1,"startTime":"2023-04-17T02:34:22.367479503Z","endTime":"2023-04-17T02:34:22.367862962Z","duration":383584}}}`

**Comment by mangalaman93** [comment] 2023-04-17 06:58
Could you give me exact curl commands that you ran?

**Comment by mangalaman93** [comment] 2023-04-18 11:42
If you ran the following on bash, this clearly won't work:
```
http://localhost:8080/graphql?query=
`{ queryStems(filter: {name: {alloftext: "text;with;semicolons"}}) { id name price } }`
```

**Comment by akon-dey** [comment] 2023-04-18 11:45
It looks like you are using the back quote (`) instead of the single quote
(‘).

**Comment by lithdoh** [comment] 2023-04-19 15:11
The backticks were because I used the code formatter in the Github editor
when I was writing the reply. Now I am replying by email. So the request
URL is

 http://localhost:8080/graphql?query={ queryStems(filter: {name:
{alloftext: "text;with;semicolons"}}) { id name price } }

This is not something that you copy and paste in Bash, you would paste this
in your browser's address bar.

**Comment by mangalaman93** [comment] 2023-04-19 16:57
yeah, I now realize that you are doing it from the browser. The issue is related to this https://github.com/golang/go/issues/25192.

**Comment by mangalaman93** [comment] 2023-04-19 17:44
I am not sure how it would work in the browser because the query part of the URL (everything after the ?) is not allowed to have a `;`. I am closing this issue for now, if there is anything else, please feel free to re-open it. Thanks for the issue and bringing this to our attention.

**Closed by mangalaman93** 2023-04-19 17:44 UTC
Labels: kind/bug

**Comment by mangalaman93** [comment] 2023-04-19 18:17
Could you help us understand your use case a bit more? Why do you want to use semicolons in the function arguments?

**Comment by lithdoh** [comment] 2023-04-19 18:21
It's because I have a search input that filters Stems name and if a semicolon or back slash "\" is entered I get the error.

**Comment by lithdoh** [comment] 2023-04-19 20:04
Here is the code: 
```
export class ExampleHttpDatabase {
  constructor(private http: HttpClient) {}

  baseURL = 'http://localhost:8080/graphql?query=';
  
  getStems(search: string): Observable<Stems[]> {
    const requestURL = this.baseURL + `{ 
      queryStems(filter: {name: ${search ? '{alloftext: \"' + search + '\"}' : '{}'}})
      { link clampDiameter brand color image length material name price rise steererDiameter weight } }`;
    return this.http.get<Stems[]>(requestURL);
  }
}
```

**Comment by mangalaman93** [comment] 2023-04-19 20:54
We found more documentation from the Go stdlib docs https://go.dev/doc/go1.17#semicolons

**Comment by mangalaman93** [comment] 2023-04-19 21:13
One thing that could help here is to URL encode the parameters. Though, I think what you are doing could lead to GraphQL injection and instead you should send the query and the variable in the body. I am not familiar with angular but if you can't figure it out, I can look into it. There should be a way to send the query and the variable in the request body. You can look at the reference here https://dgraph.io/docs/graphql/graphql-clients/endpoint/

**Comment by mangalaman93** [comment] 2023-04-19 21:26
The URL after encoding parameters look like this http://localhost:8080/graphql?query={%20queryStems(filter:%20{name:{alloftext:%20%22text%3Bwith%3Bsemicolons%22}})%20{%20id%20name%20price%20}%20} and it works for me.

**Though, we discourage the use of the GET request because a URL cannot be longer than 2048 chars as well this could lead to GraphQL injection. Instead, one should use the POST request to hit the /graphql endpoint as explained here https://dgraph.io/docs/graphql/graphql-clients/endpoint/graphql-request/**

**Comment by lithdoh** [comment] 2023-04-20 02:23
Wow thanks! That is very helpful. I will research that now.
