### ISSUE TITLE
Alpha node get restarted during some code issue (proc.go:188)

### ISSUE THREAD

**Issue by igormiletic** [dgraph-io/dgraph#4099] opened 2019-09-30 08:27 UTC
Version:

I0930 06:17:27.809113       1 init.go:98] 
Dgraph version   : v1.1.0
Dgraph SHA-256   : 7d4294a80f74692695467e2cf17f74648c18087ed7057d798f40e1d3a31d2095
Commit SHA-1     : ef7cdb28
Commit timestamp : 2019-09-04 00:12:51 -0700
Branch           : HEAD
Go version       : go1.12.7

--- 
Kubernetes 1.13.
Setup is from HA documentation of DGraph. 3 alpha nodes and 3 zero nodes
---

Node get restarted without specific readon:

```
I0930 06:22:36.251570       1 log.go:34] Rolling up Time elapsed: 01s, bytes sent: 14 kB, speed: 14 kB/sec
2019/09/30 06:22:36 Key not found
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.init.ializers
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/errors.go:36
runtime.main
	/usr/local/go/src/runtime/proc.go:188
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
github.com/dgraph-io/dgraph/x.Check
	/tmp/go/src/github.com/dgraph-io/dgraph/x/error.go:42
github.com/dgraph-io/dgraph/posting.(*List).rollup
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:853
github.com/dgraph-io/dgraph/posting.(*List).Rollup
	/tmp/go/src/github.com/dgraph-io/dgraph/posting/list.go:730
github.com/dgraph-io/dgraph/worker.(*node).rollupLists.func3
	/tmp/go/src/github.com/dgraph-io/dgraph/worker/draft.go:1019
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs.func1
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:191
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).produceKVs
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:234
github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*Stream).Orchestrate.func1
	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/stream.go:337
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
```

Expected is not to have node restarting without any valid reason.

**Comment by mangalaman93** [comment] 2019-09-30 10:41
cc @jarifibrahim

**Comment by campoy** [comment] 2019-10-04 20:53
Hey @jarifibrahim, if you can't handle this issue please assign it to someone else.

**Comment by jarifibrahim** [comment] 2019-10-07 06:41
This might not be an issue with Badger. The error states `key not found`. We need to investigate which key was that and if it was actually inserted in badger.

Assigning this to @mangalaman93.

**Comment by animesh2049** [comment] 2019-10-17 10:53
@igormiletic are you still facing the issue ? Can you share steps to reproduce the error?

**Comment by mangalaman93** [comment] 2019-11-12 17:15
Hi @igormiletic, we would like to look into this issue and fix it. Please provide us with more details, logs, steps to reproduce, p directory, sample data. It'd be very helpful.

**Comment by igormiletic** [comment] 2019-11-12 18:58
Hi @mangalaman93 , this was issue that we were facing when node runs out of memory if I remember now. I have no valid test that can send you at the moment. I can try to list steps when this was the case:

1. try to run alpha node with law memory (like 4GB)
2. try to constantly execute mutations which will probably increase during the time (like you create loop to insert 2M nodes in let say 5 minutes)
3. you will realize that Alpha node starts to consume more and more memory
4. once when it hit the limit Kubernetes will kill the node and in some of those cases might happen error that I've reported above.

As I said, we learned to be very strict with memory and I have no valid test case at the moment to send you.

If you want you can try to reproduce it or close the issue, if I come again to this stage I will report you again.

**Comment by mangalaman93** [comment] 2020-01-28 07:15
Closing for now, because I can't reproduce it. Feel free to reopen if required.

**Closed by mangalaman93** 2020-01-28 07:15 UTC
Labels: area/crash, kind/bug, priority/P0, status/accepted
