### ISSUE TITLE
feature request for merge function

### ISSUE THREAD

**Issue by mbudge** [dgraph-io/dgraph#2151] opened 2018-02-21 14:25 UTC
Hi, 

Please can you add a merge function to Dgraph?

It's a bit annoying having to query dgraph to see if the node exists in, by searching for the UID using the node edge value, before creating a new node, each and every-time we want create a new node. 

This requests multiple requests with a transaction, however if Dgraph were to handle this on the server, surely it could increase performance? 

Neo4j merge 
https://neo4j.com/developer/kb/understanding-how-merge-works/

Thanks

**Comment by jimanvlad** [comment] 2018-03-12 09:47
I think @pawanrawal and the team were already working on re-adding this function to the back-end?

**Comment by manishrjain** [comment] 2018-03-12 20:58
Yes. This functionality is on top of our list of things to do. Though, note that we're backlogged, so our progress is a bit slow.

**Comment by mbudge** [comment] 2018-05-21 12:42
It would be good if the merge function could handle type predicates https://docs.dgraph.io/howto/#giving-nodes-a-type

**Comment by campoy** [comment] 2019-07-11 21:20
This is, if I understand correctly, exactly what UPSERT blocks are about!

https://docs.dgraph.io/master/mutations/#upsert-block

The feature will be shipped with Dgraph 1.1 planned for end of July 2019!

**Comment by mbudge** [comment] 2019-07-11 21:48
Amazing.

If only we had known about this 2 years ago.

**Comment by campoy** [comment] 2019-07-12 19:01
Two years ago the feature didn't exist.

**Comment by Kingloko** [comment] 2019-07-16 12:25
Hey, quick question:
I'm hoping to use this feature pretty aggressively once its released (i.e almost every insert will be an upsert).
I was hoping to get a sense from you guys what the relative cost of an "upsert" vs "insert" is. 

I noticed in the example available in the docs, that the query was almost equivalent to a normal insert, but when I pulled dgraph master and tried reproducing the example to verify that I got an error (which is totally fine considering the feature is a WIP).

Thanks!

**Comment by manishrjain** [comment] 2019-07-16 12:56
It works just like a transaction, but avoids at least one network call between the DB and the client. Before, you'd send the query, get the results, decide what to do, send a mutation. Now you just send a mutation, which would do a query and the decision happens at the DB.

**Comment by mangalaman93** [comment] 2019-08-07 21:59
This is a duplicate of #3059, closing. Feel free to reopen if upsert block doesn't satisfy your use case.

**Closed by mangalaman93** 2019-08-07 21:59 UTC
Labels: area/querylang, kind/feature, priority/P1, status/accepted
