### ISSUE TITLE
Convert UUIDs to nodes

### ISSUE THREAD

**Issue by F21** [dgraph-io/dgraph#703] opened 2017-03-15 09:14 UTC
I plan to use dgraph to back a bounded context (service) in an event-sourced system. The bounded context would receive events from a messaging system and turn them into nodes within dgraph.

It would be nice if there was some way to convert UUIDs into nodes.

**Comment by manishrjain** [comment] 2017-03-17 20:18
Duplicate of #600

**Closed by manishrjain** 2017-03-17 20:18 UTC
