### ISSUE TITLE
Low Up Time and too many crash 

### ISSUE THREAD

**Issue by H4midR** [dgraph-io/dgraph#5458] opened 2020-05-18 08:07 UTC
### What version of Dgraph are you using?
latest
### Have you tried reproducing the issue with the latest release?
yes

### What is the hardware spec (RAM, OS)?
64GRAM 24CoreCPU - 100SSD

### Steps to reproduce the issue (command/config used to run Dgraph).
alpha
{
	"my": "localhost:7080",
	"zero": "localhost:5080",
	"lru_mb": 10240,
	"postings": "/db/a0/p",
	"wal": "/db/a0/w"
}

### Expected behaviour and actual result.
this is not good. average uptime is about 200s .
```
I0518 07:57:10.096744    6798 log.go:34] Running for level: 0
I0518 07:57:11.776967    6798 log.go:34] LOG Compact 0->1, del 6 tables, add 1 tables, took 1.680186681s
I0518 07:57:11.777037    6798 log.go:34] Compaction for level: 0 DONE
I0518 07:58:09.557956    6798 draft.go:557] Creating snapshot at index: 1205584. ReadTs: 2340795.
panic: runtime error: slice bounds out of range [:134217739] with capacity 5120

goroutine 5074376 [running]:
github.com/dgraph-io/badger/v2/table.(*blockIterator).setIdx(0xc0266a7600, 0x17)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:89 +0x5                                                                                                                        21
github.com/dgraph-io/badger/v2/table.(*blockIterator).seek.func1(0x17, 0x20)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:139 +0x                                                                                                                        57
sort.Search(0x2e, 0xc003c379d0, 0xd96373)
        /usr/local/go/src/sort/search.go:66 +0x58
github.com/dgraph-io/badger/v2/table.(*blockIterator).seek(0xc0266a7600, 0xc0355e4920, 0x1d, 0x1d, 0x0)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:134 +0x                                                                                                                        b7
github.com/dgraph-io/badger/v2/table.(*Iterator).seekHelper(0xc0266a75f0, 0x351c, 0xc0355e4920, 0x1d, 0x1d)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:241 +0x                                                                                                                        df
github.com/dgraph-io/badger/v2/table.(*Iterator).seekFrom(0xc0266a75f0, 0xc0355e4920, 0x1d, 0x1d, 0x0)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:271 +0x                                                                                                                        13a
github.com/dgraph-io/badger/v2/table.(*Iterator).seek(...)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:287
github.com/dgraph-io/badger/v2/table.(*Iterator).Seek(0xc0266a75f0, 0xc0355e4920, 0x1d, 0x1d)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:397 +0x                                                                                                                        93
github.com/dgraph-io/badger/v2/table.(*ConcatIterator).Seek(0xc0343d3590, 0xc0355e4920, 0x1d, 0x1d)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/iterator.go:492 +0x                                                                                                                        138
github.com/dgraph-io/badger/v2/table.(*node).seek(0xc04d6041a0, 0xc0355e4920, 0x1d, 0x1d)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/merge_iterator.go:9                                                                                                                        5 +0x52
github.com/dgraph-io/badger/v2/table.(*MergeIterator).Seek(0xc04d604160, 0xc0355e4920, 0x1d, 0x1d)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/table/merge_iterator.go:1                                                                                                                        79 +0x8b
github.com/dgraph-io/badger/v2.(*Iterator).Seek(0xc04d602dc0, 0xc0355e4900, 0x15, 0x15)
        /go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200515210839-ef28ef36b592/iterator.go:736 +0x265
github.com/dgraph-io/dgraph/posting.getNew(0xc0355e4900, 0x15, 0x15, 0xc0003e9800, 0xffffffffffffffff, 0x0, 0x0, 0x0)
        /ext-go/1/src/github.com/dgraph-io/dgraph/posting/mvcc.go:346 +0x1a7
github.com/dgraph-io/dgraph/posting.(*LocalCache).getInternal(0x0, 0xc0355e4900, 0x15, 0x15, 0x1, 0x15, 0x0, 0x1)
        /ext-go/1/src/github.com/dgraph-io/dgraph/posting/lists.go:209 +0x342
github.com/dgraph-io/dgraph/posting.(*LocalCache).Get(...)
        /ext-go/1/src/github.com/dgraph-io/dgraph/posting/lists.go:242
github.com/dgraph-io/dgraph/worker.(*queryState).handleValuePostings.func1(0x1770, 0x18fa, 0x100000000000000, 0xc028c                                                                                                                        9b090)
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/task.go:385 +0x1fb
github.com/dgraph-io/dgraph/worker.(*queryState).handleValuePostings.func2(0xc04daf5f80, 0xc04f286600, 0x1770, 0x18fa                                                                                                                        )
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/task.go:494 +0x3a
created by github.com/dgraph-io/dgraph/worker.(*queryState).handleValuePostings
        /ext-go/1/src/github.com/dgraph-io/dgraph/worker/task.go:493 +0x3ee
[Sentry] 2020/05/18 07:58:14 ModuleIntegration wasn't able to extract modules: module integration failed
[Sentry] 2020/05/18 07:58:14 Sending fatal event [0714232f3f3e4737aa05ea9dec53ab2b] to o318308.ingest.sentry.io proje                                                                                                                        ct: 1805390
[Sentry] 2020/05/18 07:58:16 Buffer flushing reached the timeout.
root@vps-hassaniyaqotigmail:/db/a0# dgraph alpha --config /db/a0/config.json
[Decoder]: Using assembly version of decoder
[Sentry] 2020/05/18 07:58:19 Integration installed: ContextifyFrames
[Sentry] 2020/05/18 07:58:19 Integration installed: Environment

```

**Comment by JimWen** [comment] 2020-05-18 08:46
the same problem #5456

**Comment by jarifibrahim** [comment] 2020-05-18 09:27
Duplicate of https://github.com/dgraph-io/dgraph/issues/5456

**Closed by jarifibrahim** 2020-05-18 09:27 UTC
