### ISSUE TITLE
How is variables initialized with @cascade in query

### ISSUE THREAD

**Issue by selmeci** [dgraph-io/dgraph#2331] opened 2018-04-12 09:02 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?

Dgraph version   : v1.0.4-dev
Commit SHA-1     : 6a24586e
Commit timestamp : 2018-04-11 11:51:48 +1000
Branch           : HEAD

- Have you tried reproducing the issue with latest release?

Yes

- What is the hardware spec (RAM, OS)?

16 GB RAM
OS: LMDE 2 "Betsy"
dGraph is run with docker compose

- Steps to reproduce the issue (command/config used to run Dgraph).

For example:
User demo1 does not have any privileges for reading work records on element.

Why this query initialize *WORK_RECORD* variable?
```
{
  var(func: eq(user.id,"demo1")){
    user.privilege {
      PRIVILEGES as privileged.fingerprint
    }
  }
      
  var(func:  eq(element.xid,"b1c5b4b5d85f9037312680e974bd8eaddf03dac7"),first:1) @cascade {
    ~ref.value @filter(has(in.attribute.work_record_on_element) AND NOT has(deleted.at)) {
      required.fingerprint @filter(uid(PRIVILEGES))
      WORK_RECORD as in.element
    }
  }

  workRecordsCount(func: uid(WORK_RECORD)) {
    count(uid)
  }
                        
  workRecords(func: uid(WORK_RECORD)) {
    element.xid
  }

}
```

And why this query does not initialize variable *WR_REL*
```
{
  var(func: eq(user.id,"demo1")){
    user.privilege {
      PRIVILEGES as privileged.fingerprint
    }
  }
      
  var(func: eq(element.xid,"b1c5b4b5d85f9037312680e974bd8eaddf03dac7"),first:1) @cascade {
    WR_REL as ~ref.value @filter(has(in.attribute.work_record_on_element) AND NOT has(deleted.at)) {
      required.fingerprint @filter(uid(PRIVILEGES))
    }
  }
      
  var(func: uid(WR_REL)) {
    WORK_RECORD as in.element
  }

  workRecordsCount(func: uid(WORK_RECORD)) {
    count(uid)
  }
                        
  wr(func: uid(WORK_RECORD)) {
    element.xid
  }

}
```

**Comment by pawanrawal** [comment] 2018-04-16 02:59
Variable initialization should be similar to normal query for the query with `@cascade` directive. This could be a bug where the variable isn't initialized properly when the parent filter doesn't return any results or the child subgraph doesn't return results.

**Comment by pawanrawal** [comment] 2018-04-30 02:26
@selmeci do you get an error with the second query saying that variable `WR_REL` isn't initialized or do you get empty results?

**Comment by selmeci** [comment] 2018-04-30 11:29
Hi @pawanrawal, I get empty results (desired state)

**Comment by campoy** [comment] 2019-07-12 20:59
I was not able to reproduce this issue, which probably means the issue has since then been fixed.

I'll close it, but please reopen if you're able to reproduce it.
If that's the case, could you also provide the relevant subset of your data and schema?

Thanks

**Closed by campoy** 2019-07-12 20:59 UTC
Labels: investigate
