### ISSUE TITLE
Can't always do equality query with fulltext index

### ISSUE THREAD

**Issue by zboralski** [dgraph-io/dgraph#1982] opened 2018-01-03 17:23 UTC
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.1

with the following schema.
```
name: string @index(fulltext, hash, trigram)
```

`eq(name, "test.test.test")`  works 
`eq(name, "test1.test.test")` gives ":Attribute name does not have a valid tokenizer"

**Comment by zboralski** [comment] 2018-01-03 17:27
I guess the documentation wasn't really clear as it says an index is required... I didn't realise I needed both hash and exact.

**Comment by pawanrawal** [comment] 2018-01-03 23:13
You shouldn't need both `hash` and `exact` tokenizers. Anyone of them should be sufficient.

**Comment by peterstace** [comment] 2018-01-03 23:23
I was able to easily reproduce and will take a look and what's going wrong.

**Comment by peterstace** [comment] 2018-01-04 00:54
This is occurring because equality checking chokes when more than 1 token gets returned by the full text tokenizer. So searching for "apple" will work, but searching for "apple pie" won't.

Due to some subtleties in full text tokenization, "test1.test.test" gets broken into 2 tokens, whereas "test.test.test" gets broken into a single token.

Fix inbound soon.

**Comment by peterstace** [comment] 2018-01-04 01:24
PR: https://github.com/dgraph-io/dgraph/pull/1983

**Comment by peterstace** [comment] 2018-01-04 02:28
Fixed in master at a9e4b79

**Closed by peterstace** 2018-01-04 02:28 UTC
Labels: bug
