### ISSUE TITLE
Shortest path queries OOM

### ISSUE THREAD

**Issue by chenyuzhi459** [dgraph-io/dgraph#2802] opened 2018-12-03 09:27 UTC
I want to use shortest query to find relationships between two users through the proucts they purchased or shared. Here is my query block
```
{
      path as shortest(from: 0x24a, to: 0x4) {

        purchase
        ~purchase
        product_share
        ~product_share

      }
      
      path(func: uid(path)) {
        uid
        product_name
        member_name
      }
}
```

But server doesn't return anything but this:
```
Query exceeded memory limit. Please modify the query
```

And server log seens everything is ok:
```
I1203 17:12:01.640244   27778 node.go:84] 2 is starting a new election at term 12
I1203 17:12:01.640281   27778 node.go:84] 2 became pre-candidate at term 12
I1203 17:12:01.640294   27778 node.go:84] 2 received MsgPreVoteResp from 2 at term 12
I1203 17:12:01.640411   27778 node.go:84] 2 [logterm: 12, index: 8797] sent MsgPreVote request to 1 at term 12
I1203 17:12:01.640556   27778 node.go:84] 2 [logterm: 12, index: 8797] sent MsgPreVote request to 3 at term 12
I1203 17:12:01.641571   27778 node.go:84] 2 [term: 12] received a MsgPreVoteResp message with higher term from 3 [term: 13]
I1203 17:12:01.641678   27778 node.go:84] 2 became follower at term 13
I1203 17:12:01.641703   27778 node.go:84] raft.node: 2 elected leader 3 at term 13
I1203 17:12:02.689449   27778 node.go:84] 2 [logterm: 12, index: 8797, vote: 0] cast MsgVote for 1 [logterm: 12, index: 8797] at term 13
I1203 17:12:02.689562   27778 node.go:84] raft.node: 2 changed leader from 3 to 1 at term 13

```

I wonder if it's because I use both positive and negative edgs  in my query that leads to a loop, eg: `purchase` and `~purchase`

**Comment by danielmai** [comment] 2018-12-04 01:51
This does not look like an OOM per-se (in the sense of an out-of-memory killed event). If your expected result set is large, you can set a higher upper bound for the `--query_edge_limit` flag for Dgraph Alpha.

This is not a bug report, so I'm going to close this issue. If you have a follow up question please start a topic at discuss.dgraph.io.

**Closed by danielmai** 2018-12-04 01:51 UTC
