### ISSUE TITLE
Blocked pending query on new database

### ISSUE THREAD

**Issue by mehdiym** [dgraph-io/dgraph#3551] opened 2019-06-11 10:22 UTC
- What version of Dgraph are you using?
1.0.15

- What is the hardware spec (RAM, OS)?
16Go RAM, Linux Debian stable, SSD drive.

- Steps to reproduce the issue (command/config used to run Dgraph).
Run a query (normal or read only), using the Go client, on a quite new database.

- Expected behaviour
I expect the response.

- Actual result
The request get stuck

If I look at debug/vars, I can see dgraph_pending_queries_total equals to 1.

Last log from dGraph is always a bunch of:
```
groups.go:395] Serving tablet for: %predicate_name%
```
Oddly, I can unlock such a pending query by simply loading ratel web UI, without doing any action on it.

This bug happens particularly on a fresh new database, ie. after removing p, w and zw folders.

I can easily reproduce it on my integration tests, it happens on one of the first queries. But after lots of queries, it doesn't seem to happen anymore.
On some tests I first live import a dump, but it doesn't change anything, the bug happens after a few requests.

**Comment by manishrjain** [comment] 2019-06-11 14:24
How are you loading data to Dgraph?

**Comment by mehdiym** [comment] 2019-06-11 14:38
By loading, do you mean (live or bulk) import?

I've tried with and without importing data to dGraph.
I have tests that start from an empty database, and others that start after a live import.
In both cases I can reproduce the bug.

The bug happen on a query, not a mutation. However it always happen after multiple queries/mutations.

**Comment by mangalaman93** [comment] 2019-06-14 04:23
Unable to reproduce it on my system here.

**Comment by mehdiym** [comment] 2019-06-14 13:56
Good news, I cannot reproduce this bug on dgraph master branch.
However I won't switch now to master as it won't live import my dump, it blocks while importing.

**Comment by mangalaman93** [comment] 2019-06-14 14:17
Closing this now!

**Closed by mangalaman93** 2019-06-14 14:17 UTC
Labels: area/testing, kind/bug, status/more-info-needed
