### ISSUE TITLE
Assign single UID to predicate

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#1519] opened 2017-09-22 23:06 UTC
As posted on the [community forum](https://discuss.dgraph.io/t/single-uid-assigned-to-predicate/1787):

It would be useful to be able to assign a `uid` to a predicate directly without adding it to a Posting List. For example, I might have a predicate `teacher`, where it is only ever possible to have one `teacher` at a time. 

At the moment I would have to do the following to update the predicate, which means 2 round trips and is unnecessarily verbose. 

```
mutation {
  delete  {
    <0x4> teacher * .
  }
}

mutation {
  set {
    <0x4> teacher <0x9> .
  }
}
```

Ideally, you would want to be able to specify in the schema that that predicate only accepts a single uid.

```
mutation {
  schema {
    teacher: uid @unary
  }
}
```

It would also have the added benefit of being able to return an object instead of an array when the unary predicate is being queried, as it would know there could only ever be one node/object.

**Comment by manishrjain** [comment] 2017-09-26 02:17
Once we support transactions, this is something that users can handle at their end.

Related issue: https://github.com/dgraph-io/dgraph/issues/1445

**Comment by manishrjain** [comment] 2017-10-19 22:31
Think I was too quick to declare that txns would solve this. It would still require two round trips to first delete the edges, and then set one. So, the idea of having a `@unary` in the schema is a good one.

If it's not too hard to implement, we'll do so.

**Comment by calummoore** [comment] 2017-11-01 11:46
Great news! 

This will be really helpful, as there are a lot of instances where I want to reference a single node in a  one-to-many relationship.

**Comment by calummoore** [comment] 2017-12-20 23:41
Just thinking about this a bit more. 

This feature would also enable efficient lookup of a `uid` by predicate, as there would only ever be one `uid` for a given node/predicate, performing a search would essentially the same as a hash lookup.

You could then add a new index / filter for that as well.

**Comment by AlexDunmow** [comment] 2018-10-22 07:40
Is this still on the cards?

**Comment by manishrjain** [comment] 2018-10-23 01:04
This looks like a duplicate of #2511.

**Comment by manishrjain** [comment] 2019-01-11 03:44
We're working on #2511 .

**Closed by manishrjain** 2019-01-11 03:44 UTC
Labels: feature
